language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
osx_image: xcode8
# command to install dependencies

before_script:
  - wget https://github.com/adamallo/SimPhy/releases/download/v1.0.2/SimPhy_1.0.2.tar.gz -O /tmp/simphy.tar.gz
  - tar -xvf /tmp/simphy.tar.gz
  - chmod +x $PWD/SimPhy_1.0.2/bin/*
  - export PATH=$PATH:$PWD/SimPhy_1.0.2/bin
#  - wget https://cran.r-project.org/src/contrib/outbreaker_1.1-8.tar.gz -O /tmp/outbreaker.tar.gz
#  - R CMD INSTALL --configure-args='CFLAGS="-I/usr/local/opt/gsl/include" LDFLAGS="-L/usr/local/opt/gsl/lib -lgsl -lgslcblas"' /tmp/outbreaker.tar.gz

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pytest rpy2
  - source activate test-env
  - conda install -c r r-igraph
  - conda install -c r r-ape=4.0
  - conda install r-base=3.3.2
  - conda install -c geraldmc r-adegenet
  - pip install ete3
  - pip install pyvolve
  - pip install dendropy
  - pip install codecov
  - pip install coverage
  - pip install pytest-cov
  - pip install pyyaml

# command to run tests
script:
  - python -m pytest --cov=./

addons:
  apt:
    sources:
    - r-packages-precise
    - sourceline: 'ppa:marutter/rrutter'
    packages:
    - r-base
    - r-base-dev

after_failure:
    - cat config.log

after_success:
    - codecov