language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
before_install:
  - sudo add-apt-repository ppa:marutter/rrutter
  - sudo apt-get update
  - sudo apt-get install r-base r-base-dev

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pytest rpy2
  - source activate test-env
  - pip install ete3
  - pip install pyvolve

# command to run tests
script: python -m pytest
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base