 55 638
Haliotis_ TAAATAGTGCGTGTAAAGCACTAGGTTTTCGGTTTGAGGAATTCAATCGATACGTAGACA
Chiton_ol TTCCTCGTTCGCGTAAATCAGGAGGTATTAGTTTTAGGCAATGCAATCGAGGCTTATACA
Chaetoder ATGCTATTCCGTATCAATCATTAGGTTTTCTGTTTGGGGGATGCAATCGAGGCCTACGCG
Greenland ATGCTGTTCAGGATCAAACAGTACGTAATCTGGTTGGGGTACGCAATCGAGGCCTATGCC
Neomenia_ ATCCTCCTCCAGATAAAGCATTACGTTTTCTGTTTGGGAGAAGCAATCGAGGCCTACGCG
Gadila_to CATCTACTGCGGGTAAAGTGTTAGGTTTTCGGTTTAGGGAAGGCAAGCGATGCTTTAACA
Laevipili TTCCTAGTCCGGGTCAAGCAGTAGGTGTTAGGTTTTGGTAAAGCAGTCGAGGCGTACACA
Octopus_v TTACTAGTAGGGGTTAACCACTACCTTCTAGGTTTCACGGAAGCTCTCGAGGCTTACACA
Mercenari TTCCTACTGTGCGCCAATCAATATTTATTGGGGTTTGGGAAGGCAAGCGACGCCTAGACT
Myochama_ TTCCTACTACGGGTAAATCACTATGTGTTCGGGTTGGGGAATGCAAGCGATGCCTAGACG
Astarte_s TTTCTAGTTCGGGTTAAGCATTATGTCTTCGCGATTGGGGATTCAAGGGACGCATAGACA
Neotrigon TTCGTAGTACGGGTAAAACAGTACGTCTTCGGGATGGGAAATGCAATCGAGGCTTAGACA
Pinctada_ TTCCTCGTCCGAGTCAATCAGTAGGTGTTCGGATTCGGGGAGACAATCGAGACTTATACG
Solemya_v TTACTCGTTCGAGTAAAACATCATGTATTGGGAAAGGTTAATCCGATCGAGCCTTAGACA
Ennucula_ TTAGTAGTTCGGTTCAATCATTATGAAATAGGTTTTGGGAATGCTATAGAGGCGTATACA
Doris_ker TTAATAATTCGGGTAAAGCATTACTTGTTTTGCTTGCGGAAAGCTATCGAAGCTAACACC
Pleurobra TTAATAGTGCGAGTAAAGTATTACGTGTTCGGATTACGGACCGCTATCGACGCAAACACC
Fiona_pin TTACTAGTGCGGGCAAAGCATTACGTAATAGGTTATCGGAAAGCTATAGAGGCCAAAGCC
Bathydori TTGATCGTGCGGGTAGAGCCTTATTTATTCGGATTGCGTAATGCTATCGAAGCAAATACA
Architect TTGATAGTACGGGCAAACCACTACTTATTCGGATTTCGGTACGCAATAGAAGCAAACACA
Rissoella TTAATAGTCCGAGTACAGCATTACGCATTGGGCCTCCGTAAAGCCATCGATGCAAATACG
Hydatina_ GTTATAGTCCGAGTAAATCATTACGTATTCGGATTGTGGGAGGCCATCGAAGCGAACACG
Ophicarde TTAATGGTGCGCGTAAAGCATTACGTATTAGGGTTGCGGAAGGCTATCGACGCTAACTCA
Onchidell TTTTTGGTCCGAGTAAAGCATTACGTATTAGGCTTGCGGAACGCTCCCGACGCGAATTCA
Microhedy TTAATTGTGCGGGTACAGCATTACGTATTTGGCTTGCGGAATGCTATTGATGCGAACTCA
Strubelli TTCATAGTCCGCGTAAATCAGTACGTATTCGGCTTCCGCAATGGTATCGACGCAAACTCA
Phallomed TTCATCGTCCGGGTAAAGCATTACGCATTTGGCTTGCGGAATGCTCTCGACGCGAACTCA
Turbonill TTCATAGTTCGCGTAAACCATCATGTATTCGGTTTCCGGAAGGCTATGGACGCAAACTCT
Siphonari TTAATAGTCCGAGTAAAGTATTACGTATTAGGCTTGCGGAATGCCATGGACGCCAACTCA
Biomphala TTAGTAGTCCGGGTAAAGTATTACGTATTCGGCTTGCGGCAAGTTATGGACGCAAACTCG
Oxynoe_vi TTAATGGTCCGACTAAAGGAGTACGTCGTCGGCTTGGGGAAGGCTTTGGACTCGAACTCA
Tylodina_ TTAAAAGTATGGGTAAACCATTACGTCTTTGGGTTCCGGAAGGCTTTCGACGCAAACTCA
Aplysia_c TTAATAGTCCGGGTAAACCAGTACGTTTTTCGCTTGCGGAATGCGATCGACGCGAACTCT
Clione_an TTAATAGTCCGGGTAAACCAGTACGTCTTCGGCTTGCGGAAAGCTATCGACTCGAACTCA
Haminoea_ TTAATAGTCCGGGTAAACCAATACATTATGGGGTTGCGGAAGGCTATCGACGCTAACTCA
Philine_a TTGATATTCCGGGTAAACCAGTATGTTATCGGCTTGCGGAAACCTATCAACGCTTACTCA
Hinea_bra TTAGTAATCCGTTTTAAGCAGTAGGTATCCGGATTCGGTAAAGCTTGCGAGGCATACCCT
Janthina_ TTGGTAGTTCGCTTGAAGCACTAGCTATCGCGATTAGGTAAAGCAATCGAGGCCTACACA
Rubyspira TTGGTCGTACGGTTAAAGCAGTAGGTATCCCGATTAGGCAAAGCAATGGAGGCCTACACT
Littorina TTGGTATTGCGCTTTAATCGGTAGGTTTCCCGTTTAGGTAAAGCAATCGAGGCCTACACT
Polinices TTGGTATTCCGCTTTAATCAGTAGGTATCCCGATTAGGCAAAGCAATCGAGGCCTACACT
Urosalpin TTGGTTGTCCGCTTTAAGCAGTTATTCACCCGAGTGGGTAATGCAATCGAGGCCTACACA
Ilyanassa TTGGTTGTGCGTTTTAAGCGGTTGGTATCCCGATTATGTAAAGCAATCGAGGCCTACACA
Pomacea_d TTAATAGTCCGCTTGAAGCATTAGGTATCCGGATTTGGTAACGCTATCGAGGCCTATACA
Nerita_pe CTTATCGTACGCGTAAAACACTATGTCTTGGGTTTGGGGAAAGCGATCGACGCCTAGGCA
Pyropelta TTAATAGTACGGGTAAATCACAATGTCTTCGGTTTGGGGAAAGCCATCGAGGCGTAGACA
Titiscani TTAATAGTACGTGTAAATCACAATGTCTTCGGCTTGGGGAAAGCCATCGAGGCGTAGACA
Paralepet TTAATAGTACGTGTAAATCACAATGTCTTCGGATTGGGGAAAGCCATAGAGGCGTAGACA
Lottia_gi TTCATGGTCCGGGTAAAAAATTAGGTATTCGGTTTGGGGAAAGCCATTGAGGCTTAGTCG
Perotroch TAAATAGTCGGGGTAAAGCATTAGGTTTTTAGTTTGGGGAAAACACCTGAGGCTTAGACA
Granata_i TATTTAGTCCGGGTAAAGCAATATGTTTTCGGCTTGGGCAAGGCCATCGAGACTTAGACA
Prothalot TAAATAGTGCGATTAAAGCACTAGGTCATCGGTTTCTGGAATTCAATAGAGACTTAGACC
Monodonta TAAATAGTTCGAGTAAAGCACTAGGTGTTCGGATTTTGGGATTCAATCGAGGCTTAGACA
Phasianel TAAATAGTTCGAGTGAAGCACTAGGATTTGGGTTTGTGCAATTCAATCGAAACTCAGACA
Lepetodri TAAATAGTACGAGTAAAGCAATAGTTTTTCGGTTTGGGGAATTCAATTGAGACGTAGACA

          GGACAATGGTCTCTACACGTCTCAGGAAGTGTTCCTGATTTTTGGACTCACATCCATTGC
          GGCCAGTGCTCTCTACACGTTACTAAAAGCGTACCTGAATTCTGTACCCTAATCAATTGG
          GGTCAGGGTTCGCTACAAGTCCGAGAAAGTGTACATGAATTATGCACTCTAATCAATTGC
          GGCAACGGCTGTCTACAAGTCCTAGAGAGTGTCCCTGAAATATGCACCCTCATCAAGTGC
          GGGAAGGGCTCTCTGCACGTCCGAGACAGTGTCCCTGAATTACTCACTCTCATCAATTGG
          TGTAAAGCTTGCCTTCACGTATCAGACAGTTTCCCCGTATTATGCACCATCATCAATAGG
          GGTCAAGGTACTCTGCACTTTGCAGAAAGTGTTTCCGAAGTGTGGACCATGTTAAATGGT
          GGTCATGGCTCTCTACACGTCTCAGAGAGATTTTCTGAATTACGCACAGTCGTGAAATGC
          GATCATGGTTCTCTTCACGAGTCAGATCGGCATCTTGAATTATGGGCTCTGATACACTGT
          GATCATGGTTCACTGCTTGTCTCCGAAGGTGATCTTGAATTATGGTCACTATTGAACTGT
          GAACACGGTTCTCTACACGTCTCAGAAAGTGTTCCTGAATTGGGGACTCTCATCGAATGT
          GACCACGGGTCACTCCAGGTTTCCGACAGTGTCCCAGATTTGTGGACCCTCATCAACTGT
          GAGTATGGCTCATTACAGGTCACACAATGTGTGCCTGAATTTTGGACCCTCCTCAATTGT
          GAGCATGGATCGCTACACGTCTCAGAAAGCGTGCCTGGATTATGGACACTAATAAATTGC
          GAACGTAGGTCTTTACAAGTATCAGATAGAGTCCCAGGGTTACGGACACTCATCAACCGC
          CGCCAGTGCTCTCTGCACGTCGCGGAAATCGTTCCCGAATTTGGGTCACTCATAAAATGC
          GGCCAGTTCTCCCTTCACGTCTCGGAGAGGTTTCCTGCATTTTGGTCACTCCTCAAATGG
          CGCCAGGGGTCGCTCCACGTTTCAGATAGGGTTCCGGAATTTTGTTCACTCATAAAGTGT
          GGCCAGGGTTCCCTCCAGGTCTCTGAAAGGGTTCCGGAATTTTGGTCCCTCATGAATTGT
          GGACAGGGATCCCTCAACATCTCCGAAAGCGTCCCGGAATTTTGGTCACTCATAAATTGT
          TGCGAATGCTCGCTGCATATCTCGGAAAGAGTTCCCGAATTTTGGTCGCTTATAAATTGT
          AGCCAATGCTCTCTTCACGTCTCGCAGAGCGTTGCCGAATTCTGGTCACTCATAAACTGT
          GGCCACTGCTCTCTGCACGTATCGGAAAGGGTGCCGGAATTTTGGTCACTAATAAATTGC
          GGCCAATGCTCCCTGCAAGTCTCGGAAAGGGTGCGGGAATTTTACTCAAAAATTAAGTGC
          GGCCATTGCTCTCTGCACGTCTCGGAAAGGGATCCGGAAGTTTGGTCACTGATACAATGC
          GGACAATGCTCTCTGCATTTCTCGGAAAGGGCGCCGGAACTTTGGTCACTGATCAATTGG
          GCCCAATGGTCTCTGCACGTCTCGGAGAGCGTCCCGGAATTGTGGTCACTAATGAAGTGG
          GGCCGATGGTCTCTACACGGCTCGAAACGGGTGCCGGAATTTTGCTCACTGATGAAATGC
          GGCCAATGGTCTCTAAACGTATCGGAAAGGGTCCCCGAATTTTGGTCACTCATAGATTGC
          GGCCAAAGCTCGCTGCACGTCTCTGACAGAGTCGCCGATTTTTGGTCGCTGATAAATTGC
          AGCCACTGCGCTCTGCAGGTCTCAGAAAGGGTTCCGGATTTTTGTGCGCTGATAAATTGT
          CGCCAATGCTCTCTGCACGTTTCTGACAGGGTTCCCGAATTGTGTTCACTAGTAATCTGC
          GGCCAGAGCCCTCTGCACGTCTCGGAAAGGGTTACGGAATTGTGCTCCCTGAGTAATTGC
          GGTCACAGCCCTCTGCAAGTTTCGGACTGGGTTCCGGAATTCTGTTCCCTGAGAAATTGC
          GGCCAGTGCTCTCTGCATGTCTCGGAAAGTGTTCCGCAATTGAGTTCACTGATAAATTGC
          CACCACTGCTCTCTGCATGTCTGGGAAAGGGTTCCGAAACTGAGTTCACTGATTAAGTGC
          GGACAGTGTTCCATGCACGTCTCAGATAGTGTTCCGGAATTTTGGTCCCTCATATATTGC
          GACCAGTGTTCCCTGCAAGTCTCTAATAGCGTACCTGATTTTTGGTTCCTCATAAATTGG
          GGACAGTGTTCCCTGCAAGTCTCTAATAGTCTTCCGGAGTTGTTGTTCCTCATAAATTGG
          GGGCAGTGTTCCCTGCAACTCTCACATAGTGTTCCTGACTTCTGGTTCCTCATAAATTGG
          GGACAGTGTTCCCTGCAAGTTTCAAATAGTGTTCCGGACTTTTGGTTCGTCATAAATTGG
          GGCCAGTGCTCGCTACAAGTCTCAGAGAGTGTTCCTGAATTTTGCTTGCTCATATATTGG
          GGCCAGTGCTCACTACAAGTTTCAGATAGTGTCCCTGAATTTTGGTTGATGATAAATTGT
          GGCCAGTGCACCCATCAGATCACAGAGAGTGTGCCGGACTTTTGGTCACTCAGAAATTGG
          GGCCAATGCTCTCTACACGTTTCTGAGAGTTTTCCAGAATTTAGGACCATTATCAAGTGC
          GGCCAGTGCTCTCTGCAAGTTTCTGAAAGTGTTCCGGAATTCTGGACAATGATCAATTGC
          GGCCAGTGCTCTCTGCAAGTTTCTGAAAGTGTTCCGGAATTCTGGACAATGATCAATTGC
          GGCCAGTGCTCTCTGCAAGTTTCTGAAAGTGTTCCGGAATTCTGGACAATGATCAATTGC
          GGACAGTGGACCCTCCACGTCTCTGAAAGTGTTCCCGATTTTTGGACACTCATCAAATGG
          GGCCTGTGCTCTCTAAATGTGTCAGATAGCGTTCCTGAATTTTGTACACTCATCGAGTGC
          GGCCAGTGGTCCCTACACGTATCTGGAAGTGTTCCCGATTTATGGACACTCATTAATTGC
          GGCCACTGTTCGCTATACAATACAGGAAGTGTTCCTGATTTTTGGACACTCATGAATTGC
          GGCCACTGCTCTCTACACATTTCAGGAAGTGTGCCTGAGTTTTGGACACTCATTAATTGC
          TGGCATTGGTCACTACAGTTCTCAGGAAGAGTTCCTGATTTTTGGACACTCATTAACTGT
          AGACAGTGCTCACTACACGTCTCAGGAAGAGTTCCGGATTTGTGGACGCAGATTAATTGG

          GAGACGAACATTAGATCCATCGATGTACTTGTCCTTTGAGTGATCCTCGTGGGTTCCGTT
          GAGACTAATATAAGAGCAATTAACATGATTGTTTTTTGTGTCATGCTGGTACGATTGGTT
          GAGACACACATAAGTCAAATGAAAGTCGTGGTGTTATGCGTTATCCTAGTAAGCTTGGTC
          GAAACGAACATAAGGGATATTAAACTCGTGGTGATATGCGTATTCCTAGTAAGTTTGGTA
          GAGACCAACATAAGTCAAATGAAAGTCGTCGTGTTATGCGTTATCCTAGTAAGTTTGATA
          GATACAAAATTAAGTGCTCTCAAAGTAGTCGTGTTATGGGTAATACTTCTGCGATTAGTC
          GAATCTAATATAAGTGCCCTTAAAGTTATTCTATTTTGGGTCATTCTCGTCCGTTTTGCT
          GAGACAAAGTTAAGACCAATGAAAGTAATAGTATTATGGATGCTACTCGTCCGTTTTGAC
          GAGCTGAACATAAGTGCGATCAACGCAATCCTTTTAGGTGTGATCCTATTGCGTATTGTT
          GAGAAGAAAATCCGGGCTATCAAGGTCTTTTTTTTATGGGTCATACTCTTACGTATTGTT
          GAAACGAAAATAAGACCAGTCAAAGTAAATGTTGTATGTGTAATAGTTTTACGTCTTGTT
          GAGACCAAGATAAGTGCAATCAGGGTAATTGTTTTATGCATAATACTGTTCCGTTTTCTA
          GAAACGAAGCTAAGAACAATCCACGTAATTGTCTTTTGCGTCATACTCATGCGTTTTTTA
          GAGACAAATATTAGTGCCATTCACGTAATTGTTTTATGCGTTATTCTGTTGCGTTTTGTT
          GACACGAAGATAAGCGCAATCAATTTGATTGTTATATGGGTTATACTCGTGCGTTTTATG
          GAGACGCAGATTACGGCAATGGACGTAATAGTACTTTGGGTGATTGTCGTCTCCTCTGTT
          GAGACCGAGATTAGTGCCATGAAGGTAATAGTCTTTTGTGTCAATGTTGTACGTTCTGTT
          GAGACAAAGATCAGCGTAATGATAGTTTTCGTTTTTCGTGTGCATGTAGTTAGGTCTGTC
          GATACAAAGATTAGGGCGATGAAAGTGTTAGTTTTCTGTGTGAAAGTCGTGCATTCTGTC
          GACACAAAGATAAGGGCCATGAACGTGTTTGTTTTCTCTGTTAATGTCGTGCGGTCTGTT
          CAAACTAAGATAAGAGCACTGAACGTGATAGTCATTTGGCTGGATGTCGTCCGGTCGGTT
          AAGACCAAGATTAGAGCGATGAAGGTAATAGTTATTTGTCTGAATGTCCTCCGCTCGGTT
          GAGACCAATATGAGAGCCAGGAAAATAATAGTTATTTGTGTGAATCTCGTTCGGTCTGTG
          GAAACGAAGATGAGTGCAATGAAAGTTATAGTTATTTGTGTGAATCTCGTCCGGTCCTTG
          GAGAGGAAGATTAGAGCATTCAAAGTAATAGTCTTTTGTGTGAATGTCGTCCGGTCTGTG
          GAGACGAAGATCGGGGCAATGAAAGTAATTGTCATTTGGGTCAATGTCGTCCGGTCCGTG
          GAGACGAAGATTAGGGCACTGAATGTTATCGTTATATGTGTTAATCTCGTCCGGTCTATG
          GAGACAAAGATGAGCGCAATCAAGGTAATAGTTATATGCGTGAATTTCGTCCGGTCTATC
          GAGACGAATATGAGAGCAATGAACGTTATAGTTATTTGTGTAAACCTCGTCCGGTCAGTG
          GAGATTAAATTGAGTGCGATGAAAGTCATCGTTATTTCTGTAAATCTTGTTCGGGCTGTG
          GAGACTAAGATCAGATCAATCAACGTTATTGTCATTTGGCTTAGACTGGTCCGGCCTATG
          GAGACCCAGATTAGAGCGGTGAATATCATAGTGATCTGTGTGAATCTTGTCCGGTCACTG
          GAGACGCACATGAGGGCAATGAAAGCAATCGTTATTCGGGTAAATCTCGTACGATCCGTG
          GAGACGCAGATTAGCGGAATGAAAGTGATAGTCATTTGTGTAAACCTCATGCGCTCTGTG
          GAGACTAAGATTAGAGCAATGAAAGTAATAGTGATTTGTGCAAATCTTGTCCGGCCCGTC
          AAGACAAAAATTAGCGCAATGAAGGTAATAATAATTTGGGCCAATCTAGTGCGGCCCGTG
          GAGACGACGGTTAGCACACTAAAAGTAATTGTGTTTTATCTAATCCTTGTCTGGTCGGCT
          GAGACGACGATTAGGACGCTAAAAGTGATTCTATTTTGTCTGATGGTTGTGAGGTCTGTC
          GAGACGACGATTAGAACACTAAACGTAATTGTATTCTGTCTGCTAGTTGTCTGGTCTGTT
          GAGACGACGATCAGAACGCTAAAAGTAATTGTATTTTGTCTGCTTGTAGTCTGGTCTGTC
          GAGACGCCGATCAGAACGCTAAAAGTAATTGTATTTTGCTTGCTTGTTGTCTGGTCTGTT
          GAGCCGACAATTAGGACGCTAAATGTCATTGTATTATGTCTGATGATTGTCTGGACTGTT
          GAGTCGATGGTTAGAACGCTTAAAGTGATTGTTTTATGTCTGATGGTTGTATGGACTGTT
          GAGACAACAATTAGAACACTGAAAGTAATTGTCTTTTGTCTGATCGTTGTCTGGTCTGTT
          GAGACCGAGATAGGAGCAATAAACGTAATCGTTGGTTGGGTCCTTGTTGTGGTTGCTGTT
          GAGACCCAGATTAGAGCGATTAAAGTAATCGTCTGTTGTGTGCTTGTTGTGGGCTCTGGT
          GAGACCCAGATTAGAGCGATTAAAGTAATCGTCTGTTGTGTGCTTGTAGTGGGCTCTGGT
          GAGACCCAGATTATTGCGATTAAAGTAATCGTCTGTTGTGCGATTGTAGTGGGCTCTGGT
          GAAACGAATATAAGAGCAATCAAAGGAATGGTGTGCGATTGGATACTAGTGATAACCGTG
          GAGACGAATATTAGAGCAATCAAAGTAATTGTCTTTTGAGTGATTTTCATGCGTTCTGTG
          CAGACAAAGATTAGTGCTATCAAAGTACCTCTCTTTTGAGTGATCCTAGTGGGTTCTGTT
          GAGACGAAGATTAGATCTATGAATGTACTTGTTTTCTGAGTGATTCTCGTCGGTTCGGTT
          GAAACGAAGATTAGATCTGTCAATGTACTTGTTTTCTGAGTGATTCTCGTGGGTTCTGTT
          GAGACTAATATTAGATCTATCAATGTGCTAGTCTTCTGAGTGATGCTCGTAGGATCTGTG
          GATACGACGATCAGGTCTATTAAGGTACTTGTGTTTTGGGTCATTCTAGTGGGGCCGGTT

          ATCAACTGTTTCAAATTTTAAGTATATTTAATAGAGTCTATATCGGTTTTATTGTTGTTT
          TTAAAATGGTTTAAACGTTATATACAGTTGGTAGAGTCAATCGCAGTCTTTTGGTTATTA
          ATCAAATGTTTTCAGTGTTACGTACACTTCATGGATTCAATTGCTGGCTTATGCTTAGTT
          ATAATATGGTTTAACTGCAAACTCCAGTTTATAGAATCAATTGCAGTGTTATGGTTAGTA
          ATCAACTGCTTTAAGTGCTACGTCCATTTTATAGAATCCATTGCAGTGTTATGCTTCATT
          ATCAAATGCATTCACTGCTAAGTACATTTAATAGACTCGATAGCAGTCTTTTCATTAGTA
          ATCGAGTGTTTCAAATGGTAAGTACATTTTATGGACTCAATTGCAGTTTTATGGTTTGTA
          CATAATTGTTTGAAATGCTACGTTCATTTCGTTGAGCCAATACCGGTATTTTGGTTGGTA
          ATTAAACGACGGAAATGGTATGTGGACTTTATGGAATCCATGGCAGTATTTAGGCCAATA
          CTTAAGCGACGGAAGTGTTAAGTGGAATTAAGAGACTCCACAGCAGTCTTATGGTCGATA
          ATAAAGCTTCGACATTGGTAAGTCCAATTAATCGAGTCCATCGCGATCTTCTGCTCGTTC
          ATAAAGAGTCGTAAAGGCTAAGTACACTATATGGAATCCATCGCAGTGTTCTGTTCGTTA
          ATGAACGGTCTTAAATGTCAAGTGCACTTTATAGAGGCTATCGCTGTCTTTTGGTCCTTT
          ATGAAGCGATTAAAAAGCTAAGTAAAGTTGATAGATTCCATTGCGGTATTCTGCCTCTTA
          ATGAAGAGTTTAAACTGCTACGTCAATTTTATTGGATCGATAACGGTATTATGCTTGTTA
          ATAAAGTGTTTCAATTGTTACGTATATTTGATACATCCTATCGCGGTTTTCTGCTTATTT
          AAGAATAGCTTCAAGTGCTATATATATTTTATCCAATCTATCGCTGTCTTCTGCTTATTC
          TTTTATAGATTCAACTGCTATACATATTTTATCCACACCATCGCGGTTTTTTGGTTAATC
          ATAAATAGATTGAAGTGCTATATATATTTCATGCACGCTATTGCTGTGTTCTGGTTATTC
          ATGCATAGATTCAATTGCTATATATATCTTATACACTCGCTAGCTGTTCTCTGGTTATTC
          ATTAATAGGTTCAAATGCTATATTTATTTCATAGATTCTGTTGCGGTTTTATGCTTCTTA
          ATCTATAGCATCAAATGCTATATGTATTTTATACACTCAATTGCCGTTTTATGGTTAGTT
          ATGAATGGATTCAAATGCTATGTATATTTCATCTACTCTATCGCGGTTTTCTGGTTATTT
          ATGAATAGTTTCAATTGCTATATTTATTTCATATACTCTATGGCGGTTATATGCGTATTT
          ATGAAGAGTTTCAATTGCTATATATATCTCATACACTCGATCGCTGTTTTATGGTTCTTT
          ATGAATAGTTTAAAGTGCTATATATATTTCATAGAGACGATGGCAGTTTTATGGTTATTT
          ATGACTAGCTTCAAGTGCTATATATATTTGATACACTCTATCGCGGTTTTATGGTTATTC
          ATAGATAGATTCCAGTGCTACATAGATTTCATTCACTCTATCGCTGTTTTAAGCTCTTTC
          ATGAATAGTTTCAAGTGCTATATATATTTTATAGACTCTTTCGCGGTATTATGGTTAGTT
          CTGAATAGTATCAAATGCTATATGAACTTCATACAGTCGATAGCCGTTTTATGGTTATTG
          ATGAATAGTTTCAAGTCCTATATATATTTCATACACTCTATGGCGATATTATGTTTAGTT
          ATTAATAGCTTAACGTGCTATATATATTTGATACACTCTATCGCGGTGTTATGGTTATTT
          ATGAACAGTTTAAAGTGTTATCTTTATATTATACACTCGATCGCGGTCTTATGGTTATAT
          ATGTACAGATTAAAGTGTTATCTATATATTATCCAGTCCATCCCAGTCTTATGTTTGTTT
          ATGCCTAGCTTCAAGTGCTATATGTATATCATCCACTCCATTGCGGTTTTATGGTTATTT
          ATGAATAGCTTCATCTGCTATATGTATATCATCCACTCCATCGCTGTTATATGTTTCTTT
          CTCAATTGTTTAAAATGCTATGTATATTTCATTGAATCAAGCACCATCTTGCGTTTCTTA
          CTCAACTGCTTCAAATGCTATGTGTATTTAATAGAATCAAGCGCGGTGTTGCGATTGTTA
          ATCAAATGTTCCAAATGCTATCTGTATTTCATAGAATCTAGCGCGGTGTTGCGCTTGTTT
          CTCACATGTTTCAAATGGTATGTCTATTTCATTGAATCAAGCGCGGTGTTGCGATTGTTG
          CTCACATGTTTCAAATGCTACGGCTATTTCATGGAATCAAGCGCTCTGTTGGGATTCTTA
          CTCAATTGGTTCAAATGGTATGGTTATTTCATAGACTCCAGCGCGGTGTTGCGATTATTA
          CTCAATTGGTTCAATTGTTATGGCTATTTCATAGAATCAGGCGCCGTGTCGCGATTATTA
          ATCAATTGTTTCAAATGCTATGTGTATCACATAGAATCTAGCGCGGTCTTTCGGTTATTG
          ATGACTTGTTTTAAATGGTGCGTCAACCTTATAGAAACAATAGCTGTAGCATGGTTGTTC
          ATGAATTGTTTGAAATGGTGCGTATGCTTTCTCGAAACAGTCGCGGTCTTATGGTTGCTT
          ATAAATTGTTTGAAATGGTGCGTATGCTTTCTCGAAACAGTCGCGGTCTTATGGTTGCTT
          ATAAATTGTTTGAAATGGTGCGTATGCTTTCTCGAAACAGTCGCGGTCTTATGGTTGCTT
          ATAAACTGTTTCAATTTCTAAGTTAATTTGATAGAATCTATTGCTGTACACTGGTTCGTT
          ATCAACTGTTTCAAATTTTCTGTCAACTTCGTAGAATCTATAGCGGTGTTGTGGTTGTTT
          ATCAATTGTTTCAAATTCTAACTGTATTTAATCGAGTCGACATCGGAAGTGTTGTTTTTT
          ATCAATTGTTTCAAATTCGAAGTGGATCTGATAGAGTCTATATCGGTCTTATTGTTGTTT
          ATTAATTGGTTCAAATTCTAACTATATTTAATAGAGTCTATATCGGTCTTATTGTTCTTT
          CTCAATTGTTTCAAATTCTGTGTGTATTTAATCGACTCTATTTCGGTGTTATTGTTGTTC
          ATCAAATGTTTGAACTTGTAAGTATATTTAATAAAGTCAATATGGGTATTATTGTTGTTT

          AGAATATTAGCCTTGAAGTCACCCGTAATAACAGTACGATTATTTTTATCAATGGCTTCA
          AATCTGTTAGCATTTGATCCCACGATGATAACCGTAGGCATGTTTCTCTCAGTAGAGACT
          AAAGTAATCCCGTTGGATCCTACAGTAATTACGGTGGGCATATTTCTCTCGATAGAGTCC
          AGAGTAATGGCCTTGGAGCCTACAGTAATAACAGTGGGCATTTTTCTCCCTATAGAGTCC
          AGAGTAATGCCGTTGGACCCTACAGTCATAACAGTTGGCATATGTCTCCCTATCGAGTCG
          AGAGTATTAGCCTTGAAACCTACAGTAATCACGGTCGGGCTCATGTTCTCGATGGCCTGG
          AGAGTAATAGCGTTGAACTCTACGGCTATAACCGTAGGGCTAATTGTCTCAATCGCGTCC
          ATTGTTTTTGCCTTGAAGTCTACCTCTATAGCAGTAGTAGTGTGTGTGTCGTTAGCAACT
          AGCCTGTTAGCCTTGCAAGCCACCTTCATTAAAGTGGGACTATTGGTATCGATCGCGTCC
          AGGCTCTTGTCCTTGAAATCCACGTTTATTAAGGTGGGACTATTGGTATCTATAGCGTCT
          AGAGTCTTAGCCTTGAAGTCGACGGTTATTAACGTGGGACTATTAGTAGCAATGGCGTCG
          AACCTATTCGCCTTTACGTCCCCGGTCATCAAAATGGGACTTTTAGTTTCAATCGCGTCA
          AGGGTATTAGCCTTGAAGTCGACGGTAATTAAAGTCGGACTATTCGTTTCACTGGCATCC
          GGTGTCTTGTCCCTTAACTATACTGTTATGGACGTTGGACCATTTTTATCGATAGCGTCA
          GAAGTTTTATCGTTAAAGTCGCCAGTTATAAATGTTGGACGATTTGTATCACAGGCGTCT
          AGAGTCTTAGCATTGAAGTCTATTGTAATAAGAGTAAGACTATTTCTATCAATCGCTTCT
          AGACTGTTAGCCTTGGAGTCGACCGTTATAAGCGTCAGAATCTTTATTTCAATCGCTCCT
          ATAGTATTAGCATTGAAGTCCACGGTAATAAGGGCCAGACTTTTTATTTCAATCGCGTCT
          AGAGTATTAGCCTTAAAGTCGACGGTTATAAGAGTCAGACTTTTTATTTCAGTCGCGTCT
          AGAGTATTAGCCTTCAAGTCGACGGTGATAAGGGTAAGGCTGTTTATTACAATCGCGTCT
          AGCGTATTGTCGTTAAATTCACCCGTCATGAGTGTCCGCCTACTAATGTCAATGGCGTTT
          AGCGTATTGTCGTTCAAGTCAACGGTGTTGAGTGTCGGCCTGTTGATGTCGATCGCTTAT
          AGAGTATTAGCAGTCGATTCGCCTGTGATAAGTGTTAGCCCGATAATGTCAATCGCATCT
          AGAGTATTTGCATTCGAGTCGTCGGTCATAAGTGTGAGCTTGATTAAGTCAATCTCATCT
          AGAGTCTTAGCATTGGAGTCGACGGTAATAAGAGTGAGTCTGTTTATGTCCATCTCATCA
          AGAGTATTGGCATTCGAATCGACGGTGATAAGTGTGAGCCTGTTTATGTCAATCTCATCA
          AGAGTATTAGCATTGGAGGCGACGGTGATAAGGGTGAGCCTGTTTATGTCAATGACGTCA
          GGTGTATTTGCATTCGAGTCGACGGTGATAAGTGTGAGCCTATTTATCTCAATCGCGTCA
          AGAGTATTAGCATTCGACTCGACAGTGGTAAGTGTGAGGCTGTTGATGTCTATCGCGTCT
          AGAGTGTTGGCATTGGAGTCCCCGGTAATACGTGTAAGCCTGTTTATGTCCATGGCGTCT
          AGAGTATTGGCATTTGAGTCCACTGTGATAAGGCTGGGCATGTTTATGTCAATCGCGTCT
          AGAGTATTGGCATTGAAGTCAACAGTGATAAGTGTGAGGCTATTGATGTCGATCGCATCT
          AGAGTTTTGGCCTTAAAGTCGACGGTAATGAGCGTGCGCCTGTTAATTTCAATCGCCTCC
          AGCGTATTAGCATTAAACTCGACGGTGCTCAGTGTGAGCCTATTAATTTCAATCGCATCC
          AGAGTATTGGCCTTAATTTCGACGGTGATGAGGGTGAGCCTCTTAATCTCAATGGCGTCT
          AGAGTATTGGCCCTGATGTCTACTGTGATGAGCGTGAGCCTTTTAATTTCGATGGCATCT
          AGAGTATTCGCCTTGAAGTCGACCGTGATCACAGTAGGCCTGTTCGTCTCACTAGCTTCA
          AGAGTGTTAGCCTTCAAGTCGACCGTGATCACAGTAGGACTGCTTGTGTCACTACCAGCA
          AGCGTATTGGCCATGAACTCGACCGTGATCACGGTAGGGCTTTTTGTCTCACTATCTTCA
          AGAGTCTTCGCCTTGAAGTCGACCGTCATCACAGTAGGGCTTTTTGTCGCAGTGGCTTCT
          AGGGTCTTAGCCTTGAAGTCAACCGTCATCTCAGTCGGGCTTTTTGTCTCACTAGCGTCA
          AGTGTATTAGCCTTCAATGCGACCGTGATCACGGTACGGCTTTTTGTCTCACTAGCCTCA
          AGAGTATTAGCCTTGAAGGCGACCGTGATCACAGTAGGGCTGTTTGTCTCACTCTCCTCA
          AGAGTCGTCGCACTGAAATCGACCGTGATCAAAGTAGGAATTTTTGTTTCGATAGCGTCA
          AGAGTATTCGCTGTGAAATCGGCGGTTATTACGGTGGGCTTCGTCGTATCCATTGCGTTT
          AGAGTATTAGCAGTCAAGTCGGCGGTGATTACAGTGGGCCAGATCGTTTCGATTGCGTTC
          AGAGTATTAGCAGTAAAGTCGGCGTTGATCACAGTGAGCCAGATCGTTTCGATTGCGTTC
          AGAGTATTAGCAGTGAAGTCGGCGTTGATCTCAGTGAGCCAGATCGTTTCGATTGCGTTT
          AGTAGGTTCGCCTTGAAGTCGACAGGCATTACGGGGGAAATATTTCTCTCCATCACGTCG
          AGAATTTTGGCCTTAAAGTCGACAGTTATCACTGTGGGTTTACTAGTATCAATAGCATCC
          AGAAATTTTACCTTGAAGTCGACGGTAATAACCGTGGGTTTATTTTTCTCCATCGCCTCA
          AGAATCTTAGCGCTGAAGTCACCCGTACTAACAGTCGGATTATTATTATCAATAGCTGCA
          AGAATCTTAGCCTTTAAGTCACCCATACTAACAGTGGGTTTGTTATTGTCAATAGCTTCA
          ACAATATTAGCCTTGAAGTCCGCCGTAATAACCGTGCGATTACTTTTATCAATAGCTTCA
          AGAATATTTGCATGCAAGTCTCCCGTCATAACTGTGGGTTTATTATTGTCAATAGCTTCA

          TTGAAGCACTATACAGGTGTGTAACACATCACTACTGGTCTTAGTTAGAACTTTTAGACA
          TTGAACCACAACACAGGACTTATCCAGATCACACAAGGTCTGCCCTATAGATTGTATACG
          TTGAACCACTACACCGGCCTGCTTCGAATTTCCAATGGACTGACGTACAAATTTTACACA
          TTCAATCACTACACCGGACTGCTGCGAATTACCAATGGTCTTACGCATAAATTTTATACT
          GTTAACCACTACACGGGACTGCTACGAATTACAAATGGACTGACGTACAAATTGTACACA
          TTTAACCACTACCCCGGACTGATACAGATGAGGGAGGGGCTGACTTAGAAATTCTAGCCC
          TTAAATCATTACCCCGGCCTAAGACACATCGCCGAACTGGTGACACAGAAATTCAAGACT
          TTCATCCACTACAAAAGTCTCAGGCTCATTACAGAGCGTATCACCTAGAAATTTTAGCCA
          ATTAACCACCACACACGCGTCATCCAGATTACAGATCGTCTCACTTAGAAACTGTAGACC
          ATGAACCAATACACAGGAGTCATGCAAATAACAGATCGGCTCCCTTAGAAGCTGTAGGCA
          ATAAACAACTATAGAAGAGCCATACAAATGACAGATCGTCTCACTTAGAACTTGTACAAA
          AAAAATTACTACTCGGGCGTCATACACATAACAGACCGTCTCACTTAGAAAGTGTAGGCA
          ATAAACAACTACCCCGGTCTGATTCATATGACAGATCGTCTTACTTAGAAATTTAACACT
          ATCAAACACTACACGAGACTCATCCAAGTGACAAATGGTTTCCCTTAGAAACTGTATACG
          ATAAAACAATACACCGGACTCATACAAGTGACGTATCGTCTTACTTAGAACATGTATACG
          TTGAATCAATACACAGGAGTCATCCACATCACCACTGGCCTCACTTACAAGTTGTATACG
          CTCTACCAACACCCGGTTGTCATTGACATCACAGCGAGTCTTACCTATCAATTATACACT
          TTATACCAAGACCCAGCCGTCATCCAAATAACCGCTGGTCTTACTTATAAGGTATACACT
          TTCCACCGATACCCAGCTGTCATACACATCACAACTGGTCTTACTTAGAAATTATACACC
          TTAAACCAATACCCAGCTGTGATCCAAATCGCCACTGGTCTTACTTAGAAGTTATACACA
          TTACAGCAATACCCGGGTGTAATGCATATCACATCGGGACTTACATAGAAGTTGGAGACC
          TTAAGGCAATACCCAGGCGTCATTCAGATCACCACTGGACTAACTTAGAAGTTATACCCG
          TTGAAACAAGACCCAGGTGTCATACAGATAACAACTGGTCTTTCTTAGAAATTGTACACA
          TTAAAACAAGATCCAGGTGTCATGCATATTACAACTGGGCTTTCCTAGAAGTTATACACA
          TTAAACGAAGACCCAGGCGTCATACAGATTACAACTGGGCTTACTTCTAAGTTATACACA
          TTAAACCATGACCCAGGAGTCATACAGATTACAACCCGGCTTACATAGAAGTTATACTTA
          TTAAACCAAGACCCAGGAGTTATACACATTACAACTGGGCTTACTTATAAGGTATACACA
          TTAAACCAAGAGCCGGGAGTCATACAGATAACAACGGGTCTGACTTATAACCTATACGCA
          TTAAACCAAGACCCAGGAGTCATACAGATCACTACTGGCCTTACTTAGAAGTTGTACACA
          TTAAAACAAGACCCCGGTGTCATCCAGATTACAACGGGGCTCACTTTGAAGTTACACGCA
          TTAAACCAAGACCCAGGAGTCAGCCAGATTACAACTGGCCTTACGTAGAAATTATATACA
          TTCAACGAATCCCCAGGGGTCATTCACATTACCCCTGGGGTAACTTAGAAGTTTTATACC
          TTAAACCAATACCCAGGAGTCATCCAAATGACCACCGGGCTTATATATAACTTCTACGCA
          TTACTTCATTACCCAGGAGTCCTCCAAATAACCCCCGGGGTAATTTAGAACTTCTATACA
          TTTAACCAATACCCAGCAGTCATCCACATAACCACTGTCCTTATCTGGAATCTCTACACT
          TTAAAACAATACCCCGTAGTAATCCACATTACCAATGTCATGATGTCGAATCTTGAGACA
          TTAAACCAATACACGGGTGTGATACACATCACCTCCGGTCTCACTTAGAAGTTGTATACT
          TTAAACCAATACACAGGTGTAATCCACATGACCACCGGACTCACATACAACTTGTATCCG
          TTAAACCAATACACAGGTGTCATGCACATCACGACCGGACTCACCTAGAAATCGTATGCG
          ATAAACCAGTACACAGGTGTAATACACATCACGACGAGACTCACTTAGAAGTTCTATGCG
          TTAAACCAATACACAGGCGTCATACACATCACTACCAGACTCACTTAGAAGTTCTACGCG
          TTGAAAGAGTACACAGGCGTCATACATATCACTACCGGACTCACGTACAAGTTGTACGCC
          TTGAACCACTACACTGGCGTCATGCACATCACTACCGGACTCACTTAGAAGTTGTATGCG
          TTAAACCAATACACAGGTGTCATTCACATCAGCACCGGTCTGACTTACAAGTTGTATACT
          TTAAACTATTACCCGGGTGTCATATACATCACAACTGGCCTCACCAAGAACTTCTATACC
          TTAAACCATTACACGGGTGTCATACACATCACCACTCGCCTCACTCATAAGTTGTACACC
          TTAAACCAATACACGGGTGTCATACACATCACCACTCGCCTCACTCATAAGTTTTACACC
          TTAAACCAATACACGGGTGTCATACATATCACCACTCGCCTCACTCATAAGTTTTACACC
          TTAAACCATTACACTGGTGTTCATCACATCACTACTCGCCTACCTTAGAAATTTTATACA
          GTGAACAATTAAACAGGTGTCAACCACATCACCACTGGCCTAACTTAGAGATTGGATACC
          TTCAACCATTACAGAGGTGTATAACACATCTCCACTGGTCTTACTTAGAAGTTCTACACA
          TTGAACCAGTAAACAGGTGTGCAACATTTCACCACTGGTCTGACCTAGAAATTGTACGCA
          TTGAACCAGTACACAGGCGTGTAACACTTCACTACGGGTCTTACTTACAATTTGTAGGCA
          TTGTACCAGTAAACAGGAGTGTAACATATACCTACTGGTCTTACTTAGAAACTTTAGGCA
          TTGAAGCACAAAACAGGTGTGTAACACATCACAACTGGTCTTACTTAGAAGCTCTAGACC

          TAAATGAAGCAACCAACACCCTCACAGACTACGTCATTGCCTATCTAAACACTTATCTAC
          TAAAGTAATCAACCGGCGCCTCCCCAGACAACACCTTTGCCGCTGTACACCTTAATTTAT
          TAACGTCACCATACGGCACCTCCGCAAACCACCCGATTTGCTCTTTAAACGTTTATCTAT
          AAACGGCAACATACGGCCCCGCCTCACACAATCCGGTTGCCTCTTTAAACGTTAACGTAT
          TAAGGGCAGCATACGGCGCCCCCTCATACTACGCGATTCCCTCTGCAAACACTCATTTAC
          TAAATGAAGCATCCAGCCCAGCCCCATACTACTGCCTTGCCAATATACACGATAATCTAT
          TAAATGCACCAAACCACTCCTCCCCACACTACCACATTCCCGATTTACAATTTTATATAT
          GAAATCCAGGACACCGGAGCTCCGCAGACGACACCATTGCCAAACGAAACATTTATTTAT
          TATATCAATCAAACTACTCCTCCTCTAACCCCTCCTTTTCCATTGTACACGTTAATTTAC
          TACATGAACCAGACGGCTACTCAACAAACGCCTCCATTACCTTTTTAAACGTTAATATAC
          TATATGAACCAAACGGCTCCCACCCACACACCTGCATTGCCCTTGTTAACTTTAATGCAT
          TATATGAACCATAGCGCTCCTCCTCAAACGCCTCCATTGCCATTGTATACTTTTATCTAT
          TAAAAGAACCATACGACGTCTCCACATCCTCCATCACTGCCGATTTAACCTTTAATTTAC
          TAAATGCACGATTCGGCTCCCTCCGAGACGTCTCCATTTCCTATTTACACCTTGATCTAC
          TATGTAACCCATACAGCTCCCACCCAGACGCATCCCTTCCCTATTTAAGCCTTAATTTAT
          TACCTCAAACATACCGCTTCCCCCAACACTACTCCAGTCTCACCTTATACTCTGTTTTAT
          TACCTGAAGCAAACGGCTCCCTCACACACTACTCCATTATCTACTTATACATTGTTTTAT
          TACAAGAAACAAACGGATCCAGCCGACACTGCACCAGTTTCGACATATACTTTGTTTTAT
          TACCTGAAACACACGGCTCCCCCATTCACAACTCCATTTTCTCCATATACATTGTTTTAT
          TACCTGAACCAAACGGCACCTTCATACACTACTCCATTGTCGCCATATACACTTTTTTAT
          TACCTAAAACAAACGGCTCCACCTCATACTACACCTTTATCTCCTTATTCGTTGATATAT
          TACATAAAACAGACGGCTCCTGCTCACACTACTGCATTGTCACCTTATTCTTTGTTTTAT
          TTGCTTAAACAGACGGCCACTTCACACACTACTCCCTTTTCCCCTTATATGTCGATTTAT
          TTACTTAAACAGACGGCGACTTCTCACACTACTCCCTTTTCACCTAATACATCTATTAAT
          TTCCTTAACCATTCGGCGACTTCCGATACCACTCCCTTGCTGCCGTATACATCGTTTTAT
          TTCCTCAAGCAGACGGCTCCTTCACACACCCCTCCCTTTTCTCCTTATACGTCGTTTTAT
          TTCCTTAACCAGACCGCTCCTCCACACACTACTCCATTTTCTCCTCATACTTCGTTTTAT
          TTCCTTAAGCAGACGGCTCCTCCACACACGACCCCTTTGTCCCCTTATACTTCGTTTCAA
          TTCCTTAATCAGACGGCTCCTCCACACGCCACTCCGTTCTCTCCATATACGTCGTTCTAT
          TACCTTAATCCTACGGCTCCTCCACACTCTACTCCCTTCTCACCATATACCTTTCTTTAT
          TATCTTAAACAGACGGCAGCTCCACACACCACTCCTTTGTCTCCATATATGTTGATGTAC
          TATCTCAAACAGGCTGCTCCTCCGCATACTACGCCCTTTTCTCCGAATACGTTGTTCTAT
          TATCTTAAGCAGACTGCTCCCCCGCACACTACTCCCTTGTCTCCCAATACGTTGTTTTAT
          GATCTTCAGCAGACGGCTTCCGCGCACACTACTCCTTTTTCTCCTAATACGTTGTTTCAT
          TATCTTAAGCATACGGCACCACCGCACACGCCTCCCTTTTCTCCTAACACATTGTTATAC
          TATCTTAAGCATACCGCACCACCTCACACTACTCCCTTATCTCCAAATACGATGTTCTAC
          AAAATGAAACATCCAGCCCCTCCACACACCACATCGTTGTCGATGACCACACTGTTTTAT
          AATATGAAGCATCCAGCGCCACCGCACACCGCAACAGTGTCTATATCTACCTTCTTTTAT
          AACATGAAGAAACCGGCGCCTTCTCACACACCAACATTGTCTATTTCTACATTATTTTAT
          AAAAAGAAGCAACCGGCGCCATCACACGCCACAACATTTTCTATTTCTACCTTATTTTAT
          AATATGAAGCAACCTGCCCCATCACACACCACAACATTGTCTATCTCTACATTGTTTTAT
          AAAATGAAGCAACCGGCTCCACCAAACACCACTACATTCTCTATTACTACGTTATTTTAT
          AAAATGAAGCAACCGGCGCCGACTAACACCACCACATTGTCTATTTCTACGTTTTTTTAC
          AAAATGAATCAAACGGCTCCGCCACACACGACAGCTTTGTCTATTGACACGCTCTTTTAT
          TAAATGAAGCACCCTGCACCGACCCAGACGACTTCATTGCCAATCTACACACTCTTTTAC
          TAAATTACGCAAACAGCACCTCCCCATACCACTTCATTACCAATCTACACACTACTTTAT
          TAAATTACGCAAACCGCACCTCCCCATACCACTTCGTTACCACTCTACACACTACTTTAT
          TAAATTACGCAAACCGCACCTCCCCATACCACTTCGTTACCTCTCTACACACTACTTTAT
          TAAGTACAGGGGACGGCGCGTCCACACACTACTCCATTGCCCATATACACTCTTATATAT
          TAAATGAAGCAAACGGCACCACCCCATACGACTCCATTGCCCATGAAAACGCTGATGTAT
          AATATGAAACAAACGTCACCTACTCATACGACGTACTTGCCTATATAAACGCTATTCTAC
          TAAATGAAGCAAACCGCGCGTTCACAGACCACATCATTGCCTGTCTAAACACTAATGTAC
          TAAATGAAGCAAACTGCACGTTCACAGACGACATCATTGCCTATCTAAACCCTAATTTAT
          TAAATGAGGCAAACGGCACCTTCCCAGACGACGTCAGTGCCCATCCAGGCACTAATGTAC
          TAAATGAAACAACCAACACCTTCTCAGACGACATCATTGCCTATCTAAACACTAATGTAC

          CAAATAAACAGGTAACAATACGACGCAAAGATGAACCTTGGATGAATTGACACATAAGAA
          CAATTAGACGGCGTTCACATACAGCCGAAGATTCAACTGGGATGGATCGAGACAGACGAG
          CATTTCAAAGGTTATCAGCAACAGCCTAAGATACAAATGGGCTGTATGGAAACATACGAG
          CAGATGAAGGGTTATCATCACCAGCCCAAAATGCACATGGGATGCATGCAGACCTACGAG
          CATTTTAAAGGTTATCAGCAGCAGCCTAAAATGCAAATAGGATGCATGGAAACATACGAA
          CATTTAAAGGTGGAACATAACGATCCACAAGTGCACCTGGGTTGCATCGAAACTCAAGGC
          CAAGTCGAAGGATATCACAACGAGCCAAAGATTCATCTATGGTGGATCGACTCATACGAG
          CACATAAATGGCTGCCAAAAAGAACCGAACATCAAGCTGCGGAGAATAGACACATACGAG
          CATACAAAAGGGTATAATAACTATACCAAGATGCACCTTGGATGGAATGATACTTACGAG
          CAAATAAAATGCTATCAGAACGATCCAAATTTCTACCTTGGATGGAATGATGCATACGAT
          CAGATAAACGGATATCAAAACGAACCGAAGATCTACCTGGGATGGAAAGATACATACAAA
          CAAATAACAAGGAATCACGACGAGCGAAAGATTTACCTCGGATGTAACGGTTCATACGAC
          CCAATCAAAGGTTATCACAACGATCCCAAGATATACCTCGGTTGGAACGATACCTACCAT
          CATATAAAAGGTTATCACAACGACTCTGAGATCTACCGAGGGTGGATTGAATCTTACGAG
          CAATTTAAAGGCTATCAAAACGATTCGAATAACCATCTCGGGTGGATCGAAACAGACGAA
          CACTTGAAAAGCTAACAGAACGATCCGAATATGCATCTTGGACGTATGGACACGTACGAA
          CAAATTAACAGCTAACACAAGGATCCTAAGATCCATCCTGGGTGAATCGAAACGTACGAA
          CAGATAAATCGATACCATCACGATCCGAAGATCCACCCCGCGTGAGTCGATTCGTACGGG
          CAAATAAAAAGGTAACATAACGATCCTAAAATCCACCCAGCGTGAGTAGAAACGTATGAG
          CATATAAACAGGAAACATAAAGAGCCCAAGACCCACCCAGCATGAGTCGAAACGTACGAG
          CAGTTTAATAGAGATCAAAACGAGCCTAAGATGCAGCTCGGATGCCTCGATACCTACCAT
          CAAATAAATAGGTAACAACACGATCCGGGGATTCACCCAGGATGTATGGAATCGTACGAT
          CAGATAAAAAGCTACCAAAACGATCCCAAGTTCCACCTGGGGTGAATGGACACGTACGAG
          CACATACAAAGCTGCCAAAAAGATCCGAAAATCCACCTGAGGTGAATGGACACGTACGAC
          CACATAAAAAGCTACCAAAAAGATCCGAATATCCACCTGAGATGAATAGATACCTACGAG
          CAAATAAAAAGCTACCAAAAAGATTCAAAGATTCACCTGAGGAGCGTAGTCACGTACGAG
          CACATAAAAATCTACCAAAACGATACCAACATCCAGCTCGGGTGAATAGACACGTACGAT
          CACATAAATAACTACCAAAACGATCCGGAGATCCACCTGGGGTGAATGGAGACGTACGAG
          CAAATAAAAAGCTATCAAAACGATCCGAACATCCACCTGGGGTGCATCGATACGTACGAG
          CAACTGAAAAGCTACCATAATGATCCGAAGATCCACCTGGGGCGTATAGACACGCACGAG
          CAGATAAAAAGCTACCACAACGACCCGAAGATCCAACTGGGGTGAATAGACACGAGCGAG
          CATATCAAGAGCTACCAAAACGATCCAAAGATCCACCTTGGGTGCATTGAAACCTACGAG
          CAGATCAAGATCTGCCAAAACGATCCAAATATCCACCTAGGGTGTACCCATACGTACGAA
          CAGATAAACAGCTACCAAAACGATCCAAATATCCACCTCGGGTGAATCCATCCATACGAG
          CAAGTTAAAAGGTACGAAAACGATCCAAAGATGCACCTGGGGTGAATCCACACGTACGAG
          CACATAAAGAGGTACGAAAATGATCCAAAGTTCCACCTTGGGTGAATCGATACGTACGAG
          CAAATAAAAAGATAAAACAACGACCCCGAGATTTACCTAGGATGAATCGAAAGTTACGAA
          CACATAAAGAGTTAAAAAAAGGAACCAGAGATCTACTTACGAAGTATTCCAACTTATAAA
          CAAATAAAGAGTTAAAAAAACGATCCAGAGATGTACTTAGGATGTATTGAAACTTATAAA
          CAAATAAAAAGTTAAAACAAAGATCCAGAAATATACATAGGTTGCATCGAACCATATAAA
          CAAATAAAGCGTTAAAAGGACGAGCCAGACATCTACTTAGGATGCATTGACACTTATAAA
          CAAATAAAGAGTTATGATAACGATCCAGAGATCTACTTAGGATGCATTGAAACTTATAAA
          CAAATGAAGAGTTATAAAAACGATCCAGAGATCTACTTTGGATGCATTGAAACGTATAAT
          CAAATAGCGAGTTACCAAAATGATTCAGAGATCTACCTGGGATCCATGGACACATACGAA
          CAAATGAAGAGATATCAGAACGAGCCGAATATTCATGTTGTTTGGATCGACCCGTACGGG
          CAAATAAAAAGACATCACAACGATGCAAATCTGCACCTAGGTTGAGTCGACACGTACGAT
          CAAATAAAAAGACATCACAACGATCCAAATCTGCACCTAGGTTTAGTCGACACGTACGAT
          CAAATAAAAAGACATCACAACGATCCAAATCTGCACCTAGGTTTAGTCGACACGTACGAT
          CAATTAAAGGGGAATCAATATGAGCCTAATATTCACCTTGGACGAATTGACCCAGACGAA
          CAAATAAACAGATATCAAAACGATCCGAAAATCGAGCTAGGATGAATTGACACATAAGAC
          CAAATAAAAAGGTAACAATACGAGCCAAAGATACAACTTGGATGAATCGACACATAAGAA
          CAGATATACAGTTACCACTACGACCCAAAGATCCAACTAGGATGAATTAACACATAAGCA
          CAGATAAACAGTTACCAGTACGACCCGAAGATCCACCTCGGATGCATGGACACATATGAA
          CAGATCAAACGTTAACATTAAGATCCACAGATCCACCTAGGATGTATTGAAACATAACAA
          CAAATAAACAGGTAACAATAAGAGCCTAAGATGCACCTAGGATGAATAGACACGTAAGAA

          AACTTTTGAAACCTAGATGTGGGAAACACAAAAAGGCCAAAATTTCAAGTAACCCACTCC
          AAGTTACGAGAAGTTAAAATTGGAGTATCGAAGAGTCGCAATTTTAACATCATGGAGTCC
          AATTTACGTAAAATGAATATAGGAATCACGAATAGACGTAACGTGTATTTGATCCAAACT
          AACTTCCGAAAAATCAACATCGGAATTTCGAAAAGAGGGAATGTGAACTTTATCCAAACT
          AACTTACGTAAAATGAAAATAGGAATTTCGAAGAGACGAACCGTACATTTTATTCAACTT
          AAATTGTGCAACGGAAAAATGGGCTTGTCAAAAAGACGCAACTTCCACATGATCCAAGCA
          AAGATGTGCAACCCAGACATCGTAATCACGAACAGACGCATCTTCCAAATCTTACAATCA
          GAATTTGGTGAACCCGAAATGGGGATCACGAAAAGGCGCAATCTACATATTCTACAAACT
          AATCTCGGGCACCATGAAATAGGAATATCGAAAGGACGAAAGTTTCAAATAATGCAATCC
          AAACTCGGTAATCTGGAAATCGGACTAGCTAATGGACGGAAGTGGCAAATTATTCAGTCA
          AAACTACGTAATCTTAAAATGGGAATAACGAAACGACGGAAGTGCCAAATGATTCACTCC
          AACTTATGTAATCTGGAAATGGGCATCATGAACGTACGCAAGTTTCAAATAATTCATTCT
          AAATTATGTAAACTGGAAATAGGAGTGACGAGTGGCTGCAAATTTCACATCATCAAATCC
          AACTTCTGCAATCTAGGAATGGGGATGACGAAAAGACGGAATTTTCAGATAATACAATCA
          AATTTATGTCATCTAGCAATTGCTATAACGCAAAGACGCAATTTGCAAATTATACAAGCT
          AAGATATGTAAACTAGAGATCGGGATTACGAAAAGCCGCAAACTGAAAATGGTTAAGTAT
          AAGTTCAGTACTCTGGAAATAGGTATCACCAAAAGTCCGAAGTTTAATATGATCCAATAT
          AATTTTTGTAAGATGCAAATAGGTATAAGCAAAAGGCGAAACTTAAAAATAATCCAGTAT
          AAGTTATGTAATATAGAAATCTATATAACCAATAGGCGTAACTTAAAAATCATCCAGTAC
          AAGTTTTGTAAACGGGATGGATGTATAACCAAAAGACGTAACTTAAAAAACATCCAGTAT
          AAGTTCTGGAATCTGGAAATCAGGATCACCAAAGGGCGGAAATTTAACATGATCGACCAA
          AATTTCTGTAAGCTGGAAATCGGAATTACAAAAAGAGGGAATTTTAATTTTCTCCATCAT
          AACATATGGAAACTTGAAATCGGAGTTACCAAGGGACGTAAATTTCATATCATGCACTAT
          AAAATTTGGAAACTTGAAATCGGAGTTACCAAGGGACGGAACTTTAAAATGATCCACTAC
          AAAATATGTAAACTTGAAATTGGGGTTACCAAGAGACGGCAATTCAATCTGATGCACTAC
          AAGATCTGTAAACTCGAAATCGGAGTCACCAAGGGGCGGAACTTCAATATGATTCACTAT
          AAGATATGTAAACTTGAAATCGGTATTACCAAGGGCCGTAACTTTGATGTTATCCAACAT
          AAGAAATGTAACATGGAAATCGGAATAACCAAGGTCGGGTACTTTAAAATTAACCATAAA
          AAGATAGGTAAACTGGACATCGGTATTACCAAGGGACGGAACGTTAATATTATACAATAT
          AAGATGTGTAACCTAGAAATAGGAATTACCAAAGGCCGGAATTTTAATATAATCCACTAT
          AAGATAAGTAAAATTTATATCGGACTTACCAAAGGAAGGAACTTTAATATTATCCACTAT
          AATAACTGCGAACTGGAAATAGGAATATCCAAGAGACGGCAATTTAACATTATCCAGTAT
          AAGATCTGTAAACTGAAAATCGGAATCTCCAAGCGACGAAATTTTCATATTATCCAATAT
          AAGATCTGCAAGCTAGAAATTGGAATGTCCAATAGAAGTAATTTTAACATTATCCAATAT
          AAAGTCTGTAAACTAGAAGTCGGGATATCGAAGAGATGGAACTTTAATATTATTTACTAT
          AAGGTTTGTAAACTCGAAATCGGAATCTCCAACAGACGGAACTTTAATATTATCTACTAT
          AAATTATGTAAACTATATCTCGGCCTAACTAAAAGACGAAATTTTAAAATGCTGCACTAT
          AAATTATGGAATCTCTATCTGGGCATGACCAAAGGCCGAAAATTGAAGATGATGCATTAT
          AACTTCTGGAATCTCTATCTCGGCATAACCAAAGGCCGCAATTTTAACATGATGCATTAT
          AAATTATGGAATCTATACCTAGGAATTACCAATGGCAGCAATTTCAAAATGATGCATTAT
          AAATTAAGCAATCCATATCTTGGCATAACCAAAGGCAGCAATTTTAAAATGATGCACTAT
          AAATTTGGCAATCTCTATCTCGGAATAACAAAAGGCCGTAATTTTAAAATGATGCATTAT
          AAATTATGCAATCGCTATCTGGGCATCACTAAAGGACGCAATATTAAAATGATACATTAC
          AAACTTTGTAATCTATATCTCGGCATAACGAAGAGAGGCAATTTAAAGATCCTGCACTAT
          AAGTTATGTAATCTCGAAATAGGGATTACGAAGGGACGAAACTTAAATATGATCCATTCC
          AAGTTAGGTAATCTAGAAATAGGAATTACGAAAGGGCGAAATTTCAATATGATCCAATCC
          AAGTTGTGTAATCTAGATATAGGAATTACCAAAGGGCGAAAGTTCAATATGATCCAATCC
          AAGTTGTGTAATCTAGATATAGGAATTACCAAAGGGCGGAAGTTCAATATGATCCAATCT
          AAATTATGTAAACTAGAAGTAGGTGTTACTATAAGGCGTGAGTTTCACATCTTGCAATCC
          AAATCCTGTAATCTCAAAATGGGCAAGACAAAGAGCCTGAACTTGGACATCATTCAATCT
          AATTTTTGACACCTCGAAATAGGAAATACAAAAAGGCCCAAGTTACATATTATCCAATCC
          AATTTGTGCAATCTAGAAATCGGAAACACAAAGCGGCCTAAATTTCAATTAATCCAATCC
          AATTTGTGAAATCTGGAATTGGGAAACACAAAGCGGCCCAAATTTCAATTAATCCAATCC
          AAATTCTGTAAGCTAGAAATCGGAAAGACCAAGCGGCCAAAATTACAATTCATCCAATCC
          AAATTATGAGAACTAGACATGGGAAAGACAAACAGGCCCAAAATTCAAATAATCCAATCC

          ATTGGCCAAACATCGGCACAGCTCGCGACGCAGTCATTTTAGAATTTAGAAAATACGAAA
          ATCGGCCACACATCTGCGCATCTGGCGGCACAATCTTTCTATAATTTTGACACTCCGAAC
          ATCGGATACACATCTTCACAGCTGGCGGCACAGTCCATATATAAATTTGAATATCCGAAT
          ATCGGATATACCACTGCACAGCTAGCGCCACAGCCCATTTAGAAATTCGAAAATACAAAC
          GTGGGATACACGTCGGCACAGCTAGCACCACAGTCCATATAGAACTTAGAAAATCCGAAT
          CTTGGAAAGACATCTGCGCAACTAGCTGCACATCCATTATAGAAATTTGATAATCCTATA
          ATGGGCCATACTCCGGCGCACCGGGCGGCACAGTCTTTTTAGAAATATGAGATTCCAAAC
          ATGGGTCACACATCTGCACAGCTGGCTGCCCACCCGTTATAGAAATTCGATAATGAGGAC
          ATGGGCCACACAGCCCCTCAGTTAGCCTCTCATTCATTGTATAAAGTTGAAAAGCCAAAT
          ATGGGCCACACATCTGCGCAGCTGGCGGCTCAGTCGTTTTATAACTTCCACAATCCGAAT
          TTGGGCCAAACGTCGGCGCAGCTTCCGGCACAGTCTTATGATAACTTAAAGAAACCGAAT
          CTGGGCCACACTTCTGCGCACCTCGCAGCCCAATCTTTTTAGAAATTGGAAAATCCAAAA
          ATCGGTCACACATCTTCGCAGCTAGCGGCTCAGTTGTTTCATAAATTTGAGTATCCAAAT
          ATGGGCCAAACATCCGCGCAACTGGCTGCACAGCCTTTTTACAAAGTGGATAACCCAAAA
          ATGGGCCATTCATCCGCGCAGCTCGCTGCCCAGTCTGTCTAGAAATTAGATAATCCAAAT
          ATGGGGAATACCTCAGCGCAGATTGCAACACAATCATTTTAGAATGTTGTATATCCAAAA
          CTTGGGAATACTTCGGCAAAACTGGCGATCCAGTCATTTTAGAAGTTAGTTAAACTAAAT
          CTCGGGAACACTTCGGCAAACCTGGCCACACACCCAGTATACCAATTTATCAAACTAAAT
          CTTGGGAATACATCAGCAAAACTGGCGACAGAGCCATTATAGAAGTTTGTCAATCTGAAT
          CTTGTGAATACCTCTTCAAAACTGGCAACACAGCCATTATAGAAATTAGTCAATCTTAAT
          ATTGGAAATACCTCGGAACAGATAGCGACACATTCCTTTCTAAAATTGGTTAACCTAAAT
          ATTGGGAATACTTCAGCACAGCTAGCGACACAATCATTTCAAAAAGTACTTAACCTAAAC
          ATGGGTAACACGTCGGCACAACTGGCGACACAGTCATTTCATAATTTAATAAATGTAATG
          ATAGGGTATACTTCTTCACAGCTGGCGACGCATTCGTTGCACAATTTAGTCTATGTAACT
          ATGGGGAAGACTTCAGCACATCTAGCGACACAGTCATTTCACAAATTAATAAACCTTACT
          ATGGGTAAGACTTCGGCACAAATGGCGACACAGTCATTTGAGAAATTAATAAATCTAATA
          ATGGGGTACACTTCAGCCGAATTTCCGACTCAGTCTTTGCAGAATTTAGTAATGCTAACT
          ATGGGGTACACTTCGGCCCATCTCGCTCCACAGTCATTGCAAAAATTAGTGAATCTACCG
          ATGGGGTACACTTCTGCCCAACTCGCGACACAGTTCTTGCAGAAGTTTGTAAATCTTACT
          ATGGGGAATACGTCAGCACAACTTGCGTCAGAGTCATTTCAGAATTTGGTAAACCTCCCG
          ATCGGGAAGAGTACAGCACAACTTGCCTCACAGCCAATTCAGAAACTCGTAAATCTAACA
          ATTGGGAATACTTCAGCGCAACTGGCGACACAGTCCTTTCAGAATTTAGTAAATCTAACT
          ATCAGGAAGACTTCAGCACAACTGGCGACACAGTCGTTTCATGAACTAGTACATCTTAAG
          TTAAGGAATACGTCAGCGCATATGGCGACACATTCGGTTCACGGATTACTAAACCTAAAG
          ATAAGGAATAATTCAGCTCAACTCGCACCACAGTCGTTGCAGAAATTTGTGAAGCTCAAA
          ATACGCAATAAGTCAGCTCAACTGGCGACACAGTCATTTCAGAAATTAGTGAACCTCAAT
          ATTCGTGATACATCAGCACAGGTGGCGACGCAGTCATTTTATAAATTAGTCAATACAAAT
          ATTCGCAATACATCCGCCCACCTGGCGACGCAGTCTTTTTAGAAGTTAGTCAAGACAAAG
          ATGCGAAATACATCAGCGCACCTGGCTACGCAGTCCTTTTAGAAGTTAGTCAAAGCAAAC
          ATTCGAAATACAGCAACGCAGCTGGCCACGGAGTCATTTTAGAAGTTAGTCAAAGCGAAG
          ATTCGAAATACCTCGGCGCACCTGGCGACACAGTCATTTTAGAAATTAGACAACACCAAG
          ATTCGCAATACATCAGCGCAGTTGGCGATGCAGTCATTTTAGAACTTCGTTAATACACAG
          ATGCGGAATACATCCGCCCACCTGGCGATGCAGTCATTTCAGAAATTCGTCAATACGGAG
          ATCCGGAATACATCAGCGCAGCTTGCGACGCAGTCATTATAGAAATTAGTCAAGCCTAAG
          TTGGGACACACATCTGACCATCTGGCGTCCCTGTCTTTTTAGAAATTACAAAATACACAC
          ATGGGTCACGCATCTGATCAGCTGGCGACACAGTCCTTTGAGAAATTAGAAAATCCAAAG
          ATGGGTCACGCCTCTGACCAGCTAGCGACACAGTCCTTTGAGAAATTAGAAAATCCAAAG
          ATGGGTCACGCCTCTGACCAGCTAGCGACACAGTCCTTTGATAAATTAGAAAATCCAAAG
          ATCGGGCACACGTCTGCGCTGCTTGCGACACATTCATTTATGAAGTTAGAGAATCCGAAG
          ATGGGCCACACTTCTGCGCAGCTTGCGACGCAGTCATTTTGGAATTTAAATAACCCTAAT
          ATCGGGCAGACTTCTGCGCAGCTGGCAACAAAGCCATTTTAGAACTTAGAAAATGCAAAA
          ATTGGGCAAACTACCCCACATCTCGCAACAAAGTCATTTTACAAATTTGAAAATTCAAAA
          ATGGGGCATACTTCCGTCCATCTCGCAACAAAGTCATTTTACAAGTTAGAAAAGCCAAAA
          ATTGGGCAGACTTCCGCGCAGCTCGCGACAAAGTCAGTTTACAAATTAGAAAATCCAAAC
          GTAGGGCAGACTTCCGCACAACTCGCGACAGAGTCATTTTAGAAATTAGAAAATCCAAAA

          CAATATCTGATGAATCAATTGATAACAAAATAAACTCT
          CAGCACTTGATTAATGTGTGCCTGGCTACATAAACCGT
          GGACATGTCATGAATATGTGGCTAGCGAAGTAAACCGT
          AGACATGTCATGAATATATGTATGGCTAAGTATACGGT
          GGACATGTCATCAATATTTGTCTCGCTAAGTCCACCGT
          CACCATTTAGTAAATTCTTGTATAGCGGACTATACGGT
          CAACATTTTCTTTATACTGATATTGCTAAAGAATGCCT
          TGGTACTTGCTCAAGAATGACCTACCCAAGTAAACCCT
          CATCAACTACTAAAAAACTATACTGCTAAAGAAACCCA
          CAGCAGTTAATCAATTACTATACAGCTAAATAAACCCT
          TATCAGTTAATAAATAAGTATACAGCTAAATTAACCCT
          CACCAAGTACTCAACAAGTATACTGCTATCTAAACCCA
          CAACATTTAATCAATAATTATACAGCGAAGTATGTACT
          TATGATTTAATTAATAAGTACATAGCGAAATATACCCT
          CAGCAGTTAATAAATAATTACGTGGCGAATTATACCCA
          CATTATTTAATAAGCCATTATATAGCGAAATAAGCGCT
          CAGAATCTAGTAAAGCAATATATGGCTAACTAAACTCT
          CAATATTTCATAAATTATTATATAGCTAAATATACGCT
          CGGTATCCAATAAACCATTATATCGCCAAATAAACGCT
          CGGTATCCACTAAATAATTATATAGCGAATTAAACACT
          CAATATCTTATAAATCATTATATTGCGAACGAAGCGCT
          CAGGGTCTAATAAAGGATTATATAGCTAACTAAGCGCT
          CAGTATCTGATAAATCATTATATGTCTGAGTAAGCCCT
          CAATATCTAATCTATCAATATATGTCTAACTATTCTCT
          CATTATTTTATCAACCATTATCTGTCTGAGTAAGCCCT
          CAGTATCTAATAAATCAGTATATCTCTAACTAAGCGCT
          AATTATCTAATAAATCATTATATGTCAAACTAAGCGAT
          CAGTATCTTATAAATCAGTATATCTCCCACTAAGCGCT
          CAGTATCTACTAAATCATTGTATGTCTAAATATGCTCT
          CAGTATCTTATAAACAATTATATATCTAAGTAAGCCCT
          CAGTATCTAATAAACCATTATATAGCAAACTAAGCGAT
          CATTATCTGATGAACCATTATATATCTAACTATGCTCT
          CAGTACCTAATAAACCACTATATATCTAACTATGCGCT
          CAGTATCTAATAAACCATTATATTTCTAACTAACCGCT
          CAGGATCTAATAAACTATTATATATCTAATTAAGCGCT
          CAGGAACTGATAAAACATTATATATCGAATTTCGCGCT
          CAGTATTTAATAAAGCATTACATTGCTAAAGAAACTAT
          CAGTACATGATAAATCAGAAGATGGCACATGAAACTCT
          CAGTATTTAATGAATCATAAGATGGCAAGAGACACTCT
          CACTATTTTATGAAGCATAACATGGCAAAAGAAACGCT
          CAGTATTTCATGACACATAACATGGCAAAAGAAACGCT
          CAGTATTTGATACATCATAACATGGCAACAGACACCCT
          CAGTATTTAATAAATCATAACATGGAGAAAGAGACTCT
          CAGTATTTAATAAAACAGTACATATCTAAAAAAACCCT
          CAATATGTGATGAATCAATATATAGCTAAAAACACCCT
          CAGTATTTCATGAATCAATATATAACTAAGTATACCCT
          CAGTATTTCATGAATCAATATATAACCAAGTTTACCCT
          CAGTATTTCATGAATCAATATATAACCAAGTTTACCCT
          GATTATATCATAAACCGGTCTATTGCGCAATAAACCCT
          CAGTACTTTATCAACCAGTATATATCAAAATAAGCGCT
          CAATATTTAATAAAACTTTAGATAACAAAGCTTACTCT
          CAGTATTTAAGGAAGAATTAGATAAGCAAATAAACTCT
          CAGTATTTAATTAGTCATTAGATAACAAATTAAACTCT
          CAGTATGTAATGAAGCATTAGATAACAAAATAAACTCT
          CAATATATAATGAATCAATACATGACATATCAGACTCT

