 55 619
Haliotis_ TGAGACAAATCTAAATAAATTTGCAACAACGATGGTAATTCTAAATAGGTCTTCAACTTT
Chiton_ol TGAGATAAGTCGAATCATATTTGCAAGAAGGAAGGAAATTATACGTACGTATTATACTTT
Chaetoder TGAGAGAACGATGAACAAATGGGGGACAACGATGGTAAGTCCAAGTACCTACTCAACCTG
Greenland TGAGAGAATGCACATCAAATGGGGAACAACGATGGGAATTCCAAGGACGTATTCAACCTA
Neomenia_ TGAGAGAATGCCGAACAAATGGGGAACAACGATGGAAATTCCAATTACCTGTTCAACCTC
Gadila_to GGGGAGAAATCACAGAATCTGGGCTACAAAGATAGCAGCGCTAAGTATGTTATTAACTTT
Laevipili TGACATAGTTCGAAGCACCTGTGGAACAAAGAAGGTCATCCTAATTACGGGTTCAATTTT
Octopus_v TGAGACCACTCGCATCAGGTTTGCAAACAGGAAGGGAAATCTAAACATGTATTTAACTTT
Mercenari TGAGATAATTCAAACTATATTTGGAACAAGGAAGGATACGCCAAGCACGTATTCAGGTTC
Myochama_ TGTGATAAGTCTAAATATATGTGGAAAAAGGAAAGGTACTCTAACTACGGTATTAACTTT
Astarte_s TGTGAAAAATCTAAGTATATTTGGAACAAGGATCGATATTCTAAGTACGTTGTCTACTTT
Neotrigon AGCGATAAATCTAACTACAGTTGGAACAAGGATGGATATTCTAAATACGTATTCAACCTT
Pinctada_ AGGGAGAATTCTAAAGATATTTGGAACAAAGAAGGAAACTCTCAGTACGTATTCAACTTC
Solemya_v TGGGATAAGTCTAAGTATATTGGCGAGAAGAAAGGTAACCCCGACTACGTATTGTACTTT
Ennucula_ TGTGAAAATTCCAACTATATTCGGAAGAAGGAGGGTAACTTTAACTACGTATTGAAGTTG
Doris_ker TGAGAGAATTGGAAATATATTTGCAACAGTGATGGGCATTCCAAGTACGTGTTCGAATTT
Pleurobra TGGGATAATTCCAAATATGTCTGTAAAAGTGATGGGAATTTTCATTACGTCATCGAGTTG
Fiona_pin GGAGAAAATTCGAAATATATGTGCAAAAGGAAGGGCAACTCTGATAACGTATTCGATTAT
Bathydori TGAGAACATTCGAAATATATTTGTAAAAGTGAGGGGAATTCTCTCTTTGTATTCGAATTC
Architect TGAGAAAATTCGCAAAAAATTTGCAAAAGTGACGGGAGTTCTCTGGTCATATTTGCATTT
Rissoella TGAGAAAATTCGAAATATATCTGCAAAAGTGATGGGAATTCTCACCACGTATTTGAATGC
Hydatina_ TGAGAAAACTCGGAATATATTTGCAATAGTGACGGCAACTCGCAGTACGTCTTCAAAGTC
Ophicarde TGAGAAAAATCCAAATATATATGGAAAAGGGAAGGGAATTCTGAATATGTATTCGAAGTT
Onchidell TGAGAAAATTCCAAATATATATGGAACAGTGATGGGAATTCTCAATACGTATTCGAAGTA
Microhedy TGGGACAAGTCCAAGAACATTTGGAAAACTGATGGAAATGCTTACTACGTTTTTGAAGTT
Strubelli TGAGAAAATTCCAAATATGTATGGGAAACAGATGGAAATCCTCGGTACGTCTTCGAAGTT
Phallomed CGAGGAAATTCCGAATACATATGCAAAAGGGACGGGAAAGCTCATTACGTATTCGAAGTT
Turbonill TGAGAAAATTCCGACTACATATGGAAAAGAGATGGGAAAACGCATTACGTTGTCGAATTT
Siphonari TGTGATAAATCCAAATATATATGGAAAAGGGATGGGTATTCGCAGTACGTATTCGATGTG
Biomphala TGAGACAAGTCAAAATACATTTGGAAAAGAGAAGGGAATTCACATTACGTCGTTGATGTT
Oxynoe_vi TGAGAGAATTCCAACTATATCCGTACTCGAGACGCAAATTCCCAGTACGTATTCGAAGTT
Tylodina_ TGAGAGAATTCCAAGTATTTTTGGAATAGACATGGGAATTCTCAGTACGTATTCCAAGTT
Aplysia_c TGAGAGAAATCCAAGTATTTTTGGAAAAGAGATGGGAATTCTCAAGAAGTATTGGAAGTT
Clione_an TGACAGAAGTCGAATCTTGTGTGCAAAAGACACAGGAATCCCGATTACGTTGTAGGAGTA
Haminoea_ TGAGAGAAGTCTAACTACGTTAGAAAAGGAGATGGTAAATCTCAGTACGTGATAGAAGTC
Philine_a TGAGAGAAGTCTAAAAACTTTAGTAAAGGACAGGGTAATTCTCAGTACGTCTTAGAAGTT
Hinea_bra TGAGAAAATTCTAAGTATATTTGGAATAAGCAAGGAAAGTCTAACTACGTGTGCGAATTA
Janthina_ TGCGAAAATTCTAAGTACATTTGGAACAAGCACGGCAACTCCAAGTATGTGTGCAAACTA
Rubyspira TGCGAAAATTCCAATTATATTTGGAACAAGCAAGGCAAATCTAAGTATGTGTGCAAATTG
Littorina TGCGAAAAGTCTAATTATACTTGGAAAAAGCAGGGCAAATCTAAGTATTTATGCAAATTA
Polinices TGCGAAAATTCTAAGTATACGTGGAAAAAGCATGGCAAATCTAAGTATGTATGCAAATTA
Urosalpin TGCGACAATTCTAATTATATTTGGAACAAGCACGGCAAGTCTCAGAACTTCTGCAAGTTA
Ilyanassa TGCGACAATTCTAATCATACTTGTTACAAGCATGGCAAGTCTCTGAACGTGTGCAAATTC
Pomacea_d TGAGAAAATTCTAAGTATATTTGGAACAAGCATGGTAATTCTAAGTACGTGTTGAAATTA
Nerita_pe TGCGAACACACTAAAGATACTGGAAACAACGATGGTAATTCCAAGTACGTTTTAAAATTT
Pyropelta TGCGATAAATCTCAATATATTGGGAACAAGGATGGTAATTCGAAGTACGTTATTGAATTT
Titiscani TGCGATAAATCTCAATATATAGGGAACAAGGATGGTAATTCGAAGTACGTTATTGAATTT
Paralepet TGCTATGAATCTCAATATATAGGGAACAAGGATGGTAATTCGAAGTACGTTATTGAATTT
Lottia_gi TGAGAGAATACTAAGTACATTTGGAAAAAAGATAGCAAGTCGAAGAAGCTATTATACTTG
Perotroch TGCGAAAATTCTAAATACATCTGGAACATGGCTGGTAATTCTAAGTACCTGTGCAACTTT
Granata_i AGAGAAAATTCTAAATAAATTTGGAACAAGCATGGGAATTCTAAGTATGTGTTGAACTTT
Prothalot TGAGAAAAGTCGAGAAAAATTTGTAACCACGATGGTAAATCAAACTAGGTCCTCGACTTG
Monodonta TGAGAAAAATCTAGAAAAATCTGCAACAACGATGGTAATTCAAATTAGGTGTTAGACTTG
Phasianel TCAGAAAAATCCAGAAAAATTTGCAATAACGAGCGTAAGTCAAAATAGGTATTAAACTTT
Lepetodri TGCCTAAGCTCTAAATAAATTTGGAACAAGGATGGTAATTCTAAATAGGTCTTCAAATTT

          GAACTTAAATGCGGTTGGCGATGTCAAGAAGGCACTGGAAGTTATTAAACCTACGGGGCC
          GCCCTAAACTGTGGCTGGCGGAGTCAGTACTGCCCTGGCAGTTACTATACGTGGCGTGCG
          CCAATGAACCTGGGGTGCCGTAGGCACTACGGCCCTGGGAGCTATTATACATGTGGCGCG
          CCCATTAACCGTGGCTGGCGTAGACAGTACGGCCTTGGTAGCCATTATTCCTGGGGCCCG
          CCCATTAAACGTGGTTGGCGTCGTCATTACGGGCTTGGTAGCTATTATACGTGGGGAGCT
          CCGCTGGAACGGGGATGGCGAAGTCAAAATGGGCCGGTAAGCTATAATACGTGCTGCGCC
          GCGCTGAGACGAGGTTCGCGAGGTCAATATGGCCCTGGAAGCTATTATACATCCGGGGCT
          TCACTACACCGAGGATCGCGAAGACACGAGGGTTCTGGAAGCTAATACACGCCCGGAGCG
          GCACTAAATCGCGGATGGCGAAGACATTACGGCCCCTGCAGCTAATATACTTGCGGGGCA
          GCACTGAAACGCGGATGCCGGAGAAACTCCGGACCCTGTAGGTAATATACCTGGGGCGCC
          GCAATAAATCGTGAGTCGCGAAGGCATTACGGCACCGGCAGGTAATATACCTGCGGGGCA
          GCACTCAAACGAGGATGGCGACACCAATACCGGCCCTACAGGTAATATACTTGCCGGGCT
          GCGGTGAAAGGCGGCTGGCGAAGGCAATACGGTCCAGGCGGCCACTATACATGCTGGGGT
          GCACTAAAGCGAGGTTGTCGAAGACAGTACGGCCCAAGAAGGAAATATTCGTGCGGGGCG
          GCGCTAAAGCGCGGTTGGCGAAGTAAATACGGCCCCGGAAGCGAATATACCCGCGGGTCT
          GACCTAAAACGCGGGTGCCGGTGCGAGCACGGAAGTGGAAGTTATTATACTTGCGGCGCT
          GTACTTAAACGCGGTTGGCGATGCGGAAACGGTCCCCGAAGGTATTACATATGCGGTGCC
          GTACTGAAACGTGGCTGGCGAAGCGGAGACGGTACCCGCAGTTACTATACCTGCTGTGCA
          TTGCTGAAACGCCGGTGGCGACGAGGTGACGGCACTCGAAGCTATAAGACATGCGGTGCA
          GTGCTGAATCGCGGGTGGCGACGAGGAGACGGGACACGTAGTTATCATACATGCGGTGCA
          GAACTAAAATGTGGGTGGCGATGTGAAGATGAAACGCCCAGTTATTATACTTGCGTCGCA
          GAACTAAAACGTGGGTGGCGAGGCGACGAAGGAACCCGGAGGTATTCTACCGGCAGTGCT
          GATCTAAAACGCAGCTGTCGATGCGAGGAGGGAACGCGAAGGTATACTACTTGCTGTGCC
          GATCTGCATCGCGGCCGACGATGCGATGATGGAAAGCGAAGCTATAATACATGCGGTGCC
          AATCTGGAACGCGGCCGGCGATGGGATGATGGAACCCGAAGGTATTATAGTTGCGGTGCG
          GAGCTAAAACGCAGCTGGCGGTGCGAAGACGGCACCCGAAGGTATAATACTCGCAGTTCT
          GATCTGAAACGTGGATGGCGTTGGGAAGATGGAACCCGAAGATATAATACCTGTGGGGCG
          GATCTAAAACGCGGCTGGCGATGCGAAGACGGAACCCGCAGATATAATACTTGCGGTGCG
          GATCTAAAGCGCGGCTGGCGACGCGAACAGGGAACCCGAAGATATAATACCGGCGGAGCG
          GACCTAAAACGCGGCTGGCGATGGGAAGACGGAACCCGAAGGTACTATCCTTGCCGGGTT
          GAGCTGCAACGCGTTTGGCGTTGGCAAGACGGAACCCGAAGGCATTATACTTGCCGTGCG
          GAACTAAAGCGAGGTTGGCGATGCGAACACGTAACGCGCAGGTATAGGACTTGCGGTGCT
          GAACTAAGGCGAGGGTGGCGGTGCGATCACGGAACCCGAAGGTATTATACTTGGGGGGCC
          GAACTTAAGCGGGGGTGGAGGTGTGATGACGGAACACGGAGGTATTATACTCGGCGGGCC
          CAACTAAACCGAGGCTGGCGCTGCGACGACGGAACGCGAAGATATTATGCTTGCAGTGCA
          CATCTCAAGCGAGGGTGGCGCTGCGAAGACGGATCTCGCAGGTATTATACGTGCGGTGCA
          GAACTAGAGATCGGGTGGCGTTGTCAGGGGCGGACATTTAGTTAATATACTTGCGGTCCG
          GATCTAAAGATCAGATGGCGTTTTCAAGGCCGAACCTTAAGCTAATATAATTGTGGTCCG
          GACCTAAAGATTAGGTGGCGTTGGCAAGGCGGAACCTTAGGATAATATACTTGCGGTCCG
          GAACTAAATATCAGGTGGCGTTGGCAAGGCGGATCCTTAAGTTAATATACTTGCGGACCC
          GAGCTCAAGATCAGGTGGCGTTGTCAAGGCGGAACCTTAAGTGAATATACTTGCGGACCG
          CACCTAAATATGGGGTGGCGTTGTCAAGGTGGGCCCTTAAGTTAATATACTTGCAGTCCG
          GAACTAAAGATGGGGTGGCGTTGTCAAGGTGGAACCTTAAGTCAATATACTTGCGGTCCA
          GAACTCAAGAGGGGGTGGCGTTGTCAAGGTGGAACCTTAAGTTAAAGTACTTACGGTGCG
          GAACTTAATAGCGGATGGCGATGTCAGGAAGGGACTGGAGGTTAATATACTTGCGGTCCA
          GAGCTCAAAAGAGGATGGCGATGTCATGACGGGACCGGAGGTTAATATACTTGGGGGCCA
          GTTCTCAAAAGTGGATGGCGATGTCATGACGGAACTGGAGGTTAATATACTTGGGGGCCC
          GTTCTCAAATGTGGATGGCGATGTCATGACGGAACTGGAGGTTAATATACTTGGCGGCCC
          GATCTAAACCGCGGACGTCGCTGCCAAGATGACACTGGTCGTCATTATACTTGCGGGGCC
          CAGCTCAAACCCGGTTGGCGATGTAAAGATGGCACCGGAAGTTAATATACGTGCTGGGCC
          GAACTAAACTGCGGCTGGCGCTGCCAAGAGGGCACCGGAAGTTAAAAAACCTACGGCGCA
          GAACTGAAATACGGTTGTCGAAGTCAAGAAGGAACTCGAAAGTAATAAACGTACGGGGCC
          GAACTGAAATACGGTTGTCGGAGACAAGAAGGTACTGGAAGGTAATAAACCTACGGTGCT
          GAACTGAAGTGCGGGTGTCGTAGTCAAGACGGAACTGGAAGGTAATAAACCTACGGAGCC
          GAACTTAAAAGCCGATGCCCCTGTCAAATCGGCACTGGAAGTTAATAAACATAAGGCGCC

          GATGTCAACTATTTCACTTGTTTCCCCCATGCCTGCGGTTCTGAAAAGTGTACGAGGCTT
          GAAGTGAACCATTTGCCTTGTTGCGCCGATTCTGGCGGTTCACAGGATTGTTCTGGTTTG
          GACGTCAACTATTTTTCATGTTGCCCCTATTCATGTGGTTCATATAATTGGTCAGTCTTT
          GACATCAACTATTTCTCGTGGTGCCCCTACTCCTGCGGTTCGTATAAGTGGTCGCTGGTA
          CACGTCAACTATTTCTCATGTTGCTCCTACTCTTGCGGTTCATACAACTGGTCACTCGTT
          GAGGTTGAATATCTGTCTTGTTGCCCGTATTCGGGAGGTTCTTATAATTGTTCTGGCTTT
          GACTTGAAATATTTCACATGCGGACCCTATTCTTGTGGTCCGTATAACTGGTCTGGCTTG
          AATGTCAATTATATGACGTGTTGTCCATATTCCGGAGGATCGTACAATTGGTCAGGCTGC
          GAGCTCAAGTATTTTACTCGTTGTCCCTACTCTGGTGGATCGTATAACTGGACTTGTTTT
          GAGCTCAACTATTTTACTCGCTGGCCCTATTCTGGAGGGTCTTATAAGTGCGATAGCTTT
          GAGCTCAATTATTTTACTCGTTGCCCCGACTCTGGGGGTTCTTATAATTGTTCATGGTTT
          GAGCTCAAATACTTTACACGATGTCCCAGTTCCCGAGGATCGGATAGATGGTCTTGCTTT
          CAGGTGGAGTATAGCCCTTCCTGCTCCCATTCAGTCGGTTCCAATAATTGCGCTAGCTTG
          GAGGGCAAATCCTTTACTTGGTGTCCCTACTCGGGCGGGTCTTACAAATGTTCATGTTAT
          GACGTCCATCCTTTAACGTGTTCCCCCTATTCGGGTGGTTCTTATATTGGTTCATGCTTT
          GAGGTATATTACTTTAGGTGGGGGCCTTATTCTGGTCGTTCGTATAAATGGTCTTGCTTT
          GATGGCTATTACTTTACGTGGGGTCCATATTCTCGCGGCTCTTATGAATGTTCATGCTTA
          GATGGATATTATTTGACGTGTGGCCGATATTCTGGCGGCTCTTAAAAATGGTCGTGGTTT
          CAGAGGTATTATTTTACATGGGGTTCCGATTCTGGGCGATCTTATAAATGGTCGTGCGTC
          CATAGGTATTATTTTACTTGGGGGCCCTATTCCGGACGGTCATATAAACGGTCGTGCTGT
          GATAGATACTATTTTACGTGCGGCTCCAATTCTGGTCGTTCGCAAAATTGGTCGAGCTTT
          GATGGTTACTATTTGACATGGGGTCCCTATTCAGGCGGTTCTTAAAAGTGGTCCAGCTTT
          GAGGGTTATTATTTAACGTGGGGCCCGTATTCCGGCGGATCTTAAAAGGGTTCGTGCATT
          GATGGTTATTATTTAACGTGTGGCCCGTATTCACGCGGCTCTTATAAGGGATCGTGCATA
          GATGGCTACTATTTAACCTGGGGTCCTTATTCTGGCGGATCTTAAAATGGGTCCTGTTTA
          GATGGCTATTATTTAACGTGGGGCACTTATTCTGGAGGATCTTACAAGGGTTCTAGTTTT
          GAATGTAATGACTTCACGTGGGGCGGGTATTCAGGCGGATCCTAAAACTGGTCATGCTTT
          GACGGGTATTATGTAACGAGCGGCCCTTATTCAGGCGGATCGTACAAGGGGTCGTGCTTG
          AATGGTTATTTTTTATCGTGGGGTCCGTATTCGTGCAGACCTTAAAAGGGGTCTTGCTTT
          GAAGGTTACTACTTAACGTGCGGCCCTTATTCGGTGGGATCTTACAAGGGCTCATGCTTT
          GAGGGCTATTATTTAACGAGGGGCCCATATTCCGGTGGATCAAAAAAGGGGTTGTGCTTT
          GATGGATATTATTTAACCTGGGGCCCTTATTCAGGCGGATCATATAATAGCTCGTGCTTT
          GAAGGTTATTATTTAACGTGGCGTTCTTATTCTGGCGGATCTTAAAATTGGTCGTGCTTC
          GAAGGATATTATTTAACGTGGCGCCCTCATTCCGGGGAATCTTATAAATGGTCATGGGTT
          GAGGGTTATTACATGATGTGGGGTCCTTATGCTGGAGCGACTTAAAAGAGGTCGTGCTTT
          GATGGTTATTACATCATCTGGGGGCCCTCCTCAGGTGCATCGTAAAAGAGGACATGTGTT
          GACGTCTATTATTATGCGTCGTGCCCATACTTAGGGGGTTCTTACAAATGGTCATGCTTC
          GACGTAAAATATTACGCGTCGTGCCCTTATTTAGGGGGGTCATAAAATTGGTCATGCTTT
          GACGTTTATTATTATGCGCCGTGCCCTCATTTTGGGGGTTCATAAAATTGGTCATGCTTT
          GACGTTTATTATTATGCGTGGTGCCCTCATTTCGGGGGTTCATAAAATTGGTCATGTTTT
          GACGTTTATTATTATGCGTCGTGCCCTCATTTAGGGGGTTCATAAAATAGGTCATGCTTT
          GATATTTATTATTATGCCTCGGGCCCGTATTTGGGGGGTTCTTAAAATTGGTCATGCTTT
          GACGTGTATTATTTTGCGTCGTGTCCGTATTGCGGGGGGTCTTAAGATTGGTCATGCTTT
          GACTTGTATTTTTTTACGTCATGCCCTTACTTTAGGGGTTGTCAAAATTGTTCGTGCTTT
          GAGCTAAAATATTTTACATGTTGCCCCTATTCAGGTGGTTCTTACAGTTGGTCGTGGTTT
          GATGTAAATTATTTTTCTTGTTGCCCCTATACAGGCGGCTCTTAAAATTGGTCGTGTTTT
          GATGTAAACTATTTTGCTTGTCGCCCCTATTCAGGCGGCTCTTAAAATTGGTCTTGCTTT
          GATGTAAAGTATTTTGCATGTCGACCCTATTCAGGCGGCTCTTAAAATTGGTCTTGTTTT
          GATGTTAATTATTTAACTTGGTGCCCCTACTCGGGCGGCTCCTACAAGTGGGCGTGCTTT
          CACGTAAAATATTTTACATGTTGCCCCCAGTCCGGCGGTTCTTAAAAGTGCTCGTGGTTT
          AATGTAAACTATTTCACTTGTTGCCCCCATGCCTGCGGTTCTAATAAGTGCTCGTGCCTT
          GTTGTCCAGTATTTCACTTGCTGCCCCCATGCCTGCGGATCTTACAACTGTACATGGCTC
          GATGTTCAGTATTTCACTTGTTGCCCCCATGCTTGCGGTTCTTACAAATGCACGTGGCTC
          GATGTCAACTATTTCACTTGTTGCCCCCATGCATGCGGATCTTAAAAGTGTACGTGGGTT
          GAAGTAAACTACTTCACTTGGTTCCCCCATACATGGGGTTCCTAAAAGTGGACTTGGCTT

          GTATGTAAATATGGTTCTCCACAGTGCCCCATATTGCGTTCTGTCGTCCCGTTTCGAATG
          GTAGGGAAGTATGGAACTCCACAGTGGCCGAGATTACGTCCTGTTATTCCGGTGCGCCTT
          GTGAGTAATTATGGCTCGCCCCAGTGCCCCTTTTTACGTTCTGTGATCCCTATGCGAATT
          GTGAGTAAATATGGCTCGCCACAGTGCCCCATTTTACGATCACTTATTCCTATTTCGATG
          GTCAGTCATTATGGCTCACCCCAGTGCCCCATTTTATGTTCAGTTTTCCCTATGCGGATA
          GTTAGCAACTATGGATCCACCAAGAGGCCGATCTTGCGCTTCTTACTTCCTGTGCGGATT
          TTTGAGAAATATGGCTCTCCCCACGGTCAGATTTTGCGCTCGTTTATGCCTGTTAGGATA
          GTAGGGGACTATGTGACGCCCCAGTGGCCTATGTTACGTTCATTGGTCCCCGTCAGGATC
          GTAGGGAACTATAGTTCGCCGCAATGGCCCATTTGGCGTTCCGTCGTTCCGGTCGGGATA
          GTTGGAAAATACCGTTCTCCTCAATGTCCCACTGGGCGCTCAGTTGTTCCGGTTGGAATA
          GTTAGGAACTACAGACCTCCGCAATGTCCTATTTGGCGATCAGTCGTGCCAGTCGGGATA
          GTTGGGCAGTATAGTTCTCCGCAATGTCCCATCTGGCGTTCAGTGGTGCCCGTCGGGATA
          GTTGGTAATTATAGGTCGCCCCATTGCCCCATTTGGCGTTCAGGGGTACCGGTCCGGATT
          GTCTGCAAATATTGTTCCCCCCAGTGTTCCATCTGGCGGTCTGTAGTTCCTCTCCGCACA
          CTGGGAAAGTATTGTTCTCCGCAGTGTTCCATATTGTGTTCACTTGTTCCTGTTCGCATT
          GTATGTAAGTATGGGTCTCCCCAGTGGCCCATTTTACGTGCGGTTGTGCCTGTTCGCCTT
          GCTTGTAAGCACGGAACTCCACAGTGCCCTATTTCTCGTTCGATTGTCCCGGTCCGTATT
          GTGTGTAAATATGGGCCGCCGCAGTGCTCGGTCTTACGATCGTTCGTAGCTGTCCGGATT
          GTCTGTAAGTATCGATCTCCTCAGTGGCGCATATTGCGATCGCTTGTACCAGTGCGGATG
          GGTTGTAAGTATCGATCCCCCCAGTGGCCCATATTGCGTTCGGTCGTACCTGTCCGTATG
          GTGTGGAATTACGGGTCCCCCCAATGCACAATTTTACGTTCGGTTGTACCAGTCCGAATT
          GTTTGTAATTATGGGTCTCCTCAGTGCCCAATTTTACGATCAGTTGTACCAGTTCGGATA
          GTTTGCAATTATGGCTCAGCCGAGTGCCCCATTCTCTGCTCGGTTGGACCCGTTCAGGTT
          GTTTGTAATTATGGATCTCCCGAGTGCCCCATTCTAGGCTCGGTTGTACCCGTGCAGGTT
          CTTTCTAATTATGGATCTCTCAAGTGTCCAATGCTATGCTCGGTTATGGCCGTAAGGGTT
          GTTAGGAATTATGGATCTCCGGAATGCCCGATTCTATGCTCGGTTATACCTGTTCGGGTT
          GTTTGTAAGTATGGATCTGCCGAGTGCCCAATGGTATGCTCGTTTGTACCAGTTCGCGTG
          CTTTGTAATTATGGGTCTCCCGAGTGCCCTATTCTAAGCCCGGTTGAACCTGTTCGCGTG
          GTATGTAATTATGGATCACCCGAGTGTCCCATTCTATGCCCGGTTGTACCGGTGCGCGTG
          GTTTGTAATTACGGCTCTCCTGAGTGCCCGATCCTACGCTCGGTTGTGCGAGTTCGTATT
          GTCGGTAACTACGGATCTCCCGAGTGTCCTATGCTGCGATCAGTTGTCCCTGTTCGGATC
          GTTTGTAATTATCGATCACCCCGGTGTCCAATTCTGCGTTCGGTGGTACCCGTTCGGATT
          TTTTGTAACAATGGCTCGCCAAAGTGCCCCAGACTACGCTCCGTTGTACCTGTTCGGCTT
          TTTTGTAAGTATGACTCCCCACAGGGCCCAAGACTACGCTCCGTCGTACCAGTTCGGATT
          GTCTGTCAGTATGGCTCTCCTCAGCGCGCCAGTCTGCGCTCGGTCCTACCAGTGCGCATT
          GTTTGCAAGTATGGCTCTCCTCAGCGGGCCAGACTGCGATCGGTTGTATCACTTAGGATT
          GTGTGGAAGTATGGATCTCCGCAGTGTCCAATATTGGGTTCGGTGGTTACTGTCCGGATT
          GTGTGGAATTATGGTTCCCCGCACTGCCCCATATGGGGTTCCGTTGTCACCGTTCGGATT
          GCGTGGAATTATGGATCCCCGCAGTGTCCCATATTGGGTTCCGTCGTTACCGTACGCATT
          GTGTGGAAGTACGGATCACCGCAATGTCCCCTGTTTCGTTCCGTTGTTACCGTACGGATT
          GTGTGGAAGTATGGATCGCCGCAGTGTCCCATAGTTGGTTCCGTTGTTACCGTACGGATT
          GTGTGCAATTATGGATCACCGCAGTGCCCCATTTTGGGATCCGTTGTTACCGTACGGATT
          GTGCGCAATTATGGATCACCCCATTGGTCCATCTTGGGATCCGTTGTCACCGTTCGGATC
          GTGTGTGAGTATGGCTCGCCGCAGCGTCCCATTTTGGGTAGGGTCGTTACAAGACGTATT
          GTAGGGAAATATGGGTCTACCCAATGCCCCATCTTTCCAGCTGTAGTTGCAGTTCGTATT
          GTATGGAACTATGGATGTCCCCAGTGTCCCATATTCCATTCACTCGTGCCTGTTCGAATA
          GTATGGAAGTATGGTTGTCCCCAGTGTCCCATATTGCATTCACTCGTGCCTGTTCGAATA
          GTATGGAAGTATAGTTGTCCCCAGTGTCCCATATGCCATTCACTCGTGCCTGTTCGAATA
          GTGTGGAACTACGGGTCGCCTAAGTGTCGAATATTGCGTTCTGTTGTGCCTTTGCGAATT
          GTTTGGAAATATGGTTCACCCCAGTGTCCCATATTCCGTTCTGTTGTGCCTTTTCGAATT
          GTTTGTAATTAGGGTTCTCCCCAATATACAATATTGCGGTCTGTCGTTCCCTTACGAATC
          GTTTGTAAATAGGGGTCTCCCCATTGTCCCATATTGTGGTCTGTCGTTCCTTTTCGAATT
          GTTTGTAAATATGGCTCTCCACAGTGTCCCATATTGTGTTCTGTCGTTCCATTTAGTATT
          GTTTGTAAACAGGGTTCGCCCCAGTGTCCCATATTATGTTCTGTCGTCCACATTGGAATC
          GTTTGTAATTATGGTGCTCCGCAGTGTCCCATTTTGCGTTCTGTTGTTCGAGTTCGAATT

          TGTCAAACTCTCGCCTATCATGAATGATGGTCAGCAGTATCGGTATGGGCAAGAGTGCAA
          GGTCCAACGATTGCCTATCAGGTATGGAGCTCCGCGTTAACCCTAGGTGCTAGCGTGCAA
          TGTCAGACTCTTGCCTATCAGATCTGTAGATCAGCGATACCCCTGAGTGCAAGTGTCCTA
          TGGCAGACTATGGCCTATCATGTCTGCAGCTCTGGGATAACACTGGGAGCAAGTGTACTA
          TGGCACACTCTCGCCTATCATGTCGGTAGCTCAGCGATAACCTTGGGTGCAAGTCTACTC
          TGTGAAACTCTTGCGTACCAGGTATGAAGTTCTGCTTTAACCCTAGGCGCACGTGTTCAC
          TGGCAGGCTCTCGCTTATCAGGTGTGAATTTCCGCGTTGACGCTAGGGACGAGTATACAC
          CGAAAGACCCTCGACTATCATTTGTGTAGTTCACCGATAACTCTCGGGGCAAGTCTCCAG
          AGTCATACTCTGGCCTACCAGTTATGCCGTACATCATTAACCGTAAGGGCGAGAGTACAA
          GGCCCGGCACTGGCCTATCAATTATGCAGTTCAGCATTAAGACTAAGAGCGAGGGTACAA
          CGCAAAACTCTGCCGTATCACTTCTGCAGTTCAGCCTTGACGCTAAGGGCGAGGGTACAG
          TGTCACACCCTGGCGTACCAGTTTTGTAGATCACCATTAACCCTTAGGGCTAACGTACAA
          TGTCAAACTCTCGCCTATCAGTTATGTAGCGCAGCCTTGGCTGCCGGCGCGTTCGTACAA
          TGTCACGCCGTCGCCTATCAGTTGTGGAGATACGCATTAACTCTAGGTGCGAGTGTACAA
          TGTCAAACTATCTCCTATCAATTGTGAAGTTCTGCGTTGACACTAGGAGCAAGCGTACAA
          TGTCAAACCCTCGCCCAGGAGGTCTGATGTTCACCGTTGGCCCTATGGGCTAGCGTACAA
          TGGCAAACTCGAACCCAGGATGTCTGCTGGTCAGCATTAGCCCTGTGCGCAAGCGTAAAT
          TGTCCAACTCTATCCCAGGAAGTGTGATGGGCAGCATTAGCACTATGCGCAAGCCTACAA
          TGTCGAACACTAACGCAGAATGTCTGTGGGTCCGCGTTTTCGCTATGGCCAAGCATTCAA
          GGTCGTGCCCTAACGCAGGATGTCTGATGGTCAGCTTTTGCGCTATGGTCAAGGATTCAA
          TGGCAAACTCTAACCCAGGAGCTCTGAAGGTCTCCCTTAGCGGTGGGCCCAAGCGTTCAA
          TGTCAAACCCTAACCCAGGAGGTCAGACGGTCTGCGTTAGCGCTCTGCCCCAGCGTGCAC
          AGTCAAACTCTAACCAATGAGGTCTGATGGGCGGCGTTAGCACCGGGCGCACGCGTTCAA
          AGTCAAACTCTAACCCAGGAGGTCTGATGCGCTGCGTTTGCTCTGTGCGCACGCGTACTA
          AGTCAAACTCTAACCCACGAGGTATGATGTGCAGCGTTAGCGCTATGCGCACGCGGACAA
          ACTCAAACTCTAACGCACGACGTCTGATGCGCAGCCTTAGCGCTGGGCCCAGGCGTACAA
          AGTCAAACTCTTACCCATGAGGTCTGTTGTGGAGCCCTACCGCTATGGGCGTGCGTCCAA
          AGTCAAACTCGCACCCAAGAGGTCTGATGCGCCGCCTTGGCGCTGGGGGCAAGCGTTCAT
          AGTCAAACTCTGACCCAGGAGGTATGAAGCGCAGCGTTCACGATGTGCGCGTGCGTACAC
          TGTCAAACACTTGCGCATGATGTATGATGTACAGCGTTGGCGCTATGCGCTCGCGTACAA
          TGTCAAACTCTTACCCAGGATGTTTGACGCGCGTCCTTGGCAGTGCGCGCACGAGTACAA
          TGTCAAACTCTAACCAAGGAGGTTTGTTGGACAACTTTACCACTGTGTGCGCGGTTACAA
          TGCAAGACTCTAACCCAAGAGGTTCGGTGTTTAACGTTAGCGCTGGGGGCACGAGTGCAC
          TGTCAGACTCTAACCCAGGAAGTCCGCTGGTTAACATTAGCACTGTGCGCGCGAGTACAG
          TGCCACACGGTAACTCACGTGCACCGTGGTTCATCCTTAGCACTATGCGCACGGGTTCAA
          CGTCAAACGCTAACTCATCTGGTCCGGGGCTCAACCTTAGCAGTATGCGCACGAGTACAA
          TGCCAATCCCGAGCACATGAGGTCTGTTGTTCAGCCGTTACCCTCTGGGCGAATGTACAA
          TGTCAATCTGGCGCCTATGAGGTCTGATGTTCAGCCGTTACTCTCGGTGCTAGTGTACAA
          TGTCAATCTCGCGCCTATGAGATTTGACGTTCAGCCGTAACTCTCGGGGCTAGTGTTCAA
          TGTCAATCTCGCGCATATGAACTTTGATGTTCAGCCGTAACGCTCGGGGCCAGTGTACAA
          TGTCAATCTCGTGCCTATGAGCTCTGATGGTCTGCCGTAACTCTCGGGGCTAGTGTACAA
          TGTCATTCCCGCTCATATGAGGTTTGATGTTCAGCCGTAACACTCGGGGCTAGAGTGCAA
          TGTCAATCACGCTCCTATGAGGTTTGATGTTCAGCGGTAACCCTTGGATCTAGTGTTCAA
          TGTCAAACGCGAGCCCATCAGATTCGGTGTCCAGCCTTAACTGTCTGGGCGAGCGTACAA
          TGTCAAACTCTCGCCGTGCACGTGCGCAGTGCTGCGTTAGCCCTATGGGCGAGCTTCCAA
          TGTCAAACCCTCGGGTATCAGGTCTGCAGTTCTGCGTTTGCTCTCTGGGCAAGTTTCGAA
          TGTCAAGCTTTCGGGTATCACGTCTGCAGTTCTGCGTTTGCTCTCTGGGCTAGTTTCGAA
          TGTCAAGCTCTCGGGTATCACGTCTGCAGTTCTGCGTTTGCTCTCTGTGCTAGTTTCGAA
          TGGCACGCACTCGCCTATCAAGTGAGGAGGTCTGCATTAGCGCTCTGTACAAGAGTAAAA
          GGTCAAACTCTCGCCTATCAAGTATGAAGGTCTGCATTGTCTGTCCGCGCAAGCTTCCAC
          TGTCAAACTCTAGCCTATCATGTCTGCAGGTCAGCATTTTCAGTATGGGCAAGTGTGCAC
          TGTAAAACTCTGGCATATCATGATAGAGCCTCCGCACTACCCGTATGGGCAAGATTGCAG
          TGTCAAACTCTCGCGTATCATGAATGATCCTCAGCCCTATCCGTATGGGCAGGAGTGCGA
          TGGCTTACGCTCGCCTATTATGAATGGTGGTCCGCCTTATCCGTATGTGCAAGAGTGCAA
          TGGCAAACTCCCGCGGATCAAGAATGCTGGTCTGCGTTTTCCATATGTGCAAGAGTGCAA

          CTGCTGCAGCTGCGATGCCTCCCACGACACCACCCGCAATAGCCAGTGCGATCTCAGACC
          GTTCTCCAGCTTCGATGCCTCCCACGACAAAATCCACACTATACAGTCTGTCCTCTGTCT
          GTTCTACATCTCGGACGCCTCCCCCGTCACAAGGCGCATTATACAGTGCGACCACTGTCA
          GTGCTCCACCTCGGCCGCCTCCCCCGTCACAACGCCCTCTATACCCTGCGACCCCTCACA
          ATTCTACACCTCGGCCGCCTGCCCCGTCACAACGCTCATTATACCCTGCGCGCACTTCCA
          GTCGTGCAGCTGAGGGGTGTACGACGCCAGAACCCTCAGTACACAGTTCGGCCGCTTACG
          GTCGTACACCTACGTTGGCTACCGCGACATTACCCGCATTATACAGTACGGCCGCTAACA
          GTCCGGCATCTTAGATGTTTACCGCGAGAATATACAGACTATACAGTACGGCCTCTTACT
          GTCCTTCAGCTGAGTTGCCGTCCCCACCACAACCCGCATTATACTGTTGGTACACTCACC
          GTCCTGCATCTTCGTTGGCTCCCAAGCCACAAGCCTCAGTATACGGTTGGTCCACTCACC
          GTCTCGCACCTGCGGTGGCTCCCCCGCCACAAGCCTAATTATACAATTCGTCCGCTTATC
          GTCCTACATTTCCGTTGCCTCCCACGCCACAAGTCACACGATACAGTGTGTCCACTCACC
          GTGCTGCATGTTCGTTGGCACCTCCGTCAAAAGCCCCAATACCCAGTTCGCCCACTGACC
          GTGCTGCATCTACGATTTCTTCCCCGACATAACCCGCATTATCCGGTTCGCTCCCTGTCC
          GTCCTAGAGCTCAGTTGGCTACCAAGGAAGAAGCCCCAGAACACTGTACGTGCTATGACC
          ATACTGGAACACCGGTGGATCCCTCAACACAAACCTCACCATACAGTTCGACCATACACG
          ATGCTGCAACAGCGATGGCTGCCCCAACAAAAACCGCAATATACAATGCGGCCACAGCCA
          ATACTCCAGAAACGCTGGCTACCTGAAGACAAGCCACAAACTGCGGTTCGCCCACAGACT
          ATCCTCCAGCAGCGTTGGCTCCCTCAACACAACCCTAAGTATACTGTTCGCACACAGCCC
          ATTCTCCAGCAGCTATGGCTCCCTCAAAACAAACCTAAAGATACGTTCCGCCCACAGACC
          ATTCTGCACCATCGGTGGCTGCCGCATCACAAGCCTCAGCAGACAGTCCGACCTCAAACT
          ATCTTGCAGCATCGATGGCTCCCTCATCAGAAACCCCACAATACAGTCCGACCTCACACC
          ATTCTGAAGCAGCGATGGCTCCCTCTACAGAAACCGCAATATACAGTCCGCCCACAGACC
          ATTATGAAGCAGCGCTGGCTCCCTCTACACAACCCTCAATGTACGGTCCGCCCACAGACC
          ATCCTGAAACATCGATGGCTGCCTCAACACAAACCTCATTATACAGTACGTCCACACACC
          ATGCTGGACCAAGGCTGTCTCCCTCAGCAAAAACCTCAATACACGGTCCGGCCACATACC
          ATTCTGAAGCAGCGATGTCTCCCACAACAAAAACCTCAATACACAGTCCGACCGCACACC
          ATTCTGAAGCAGCGCAGGCTCCCTCACCACAAGCCTCAATATACAGTCCGCCAGCACACC
          TTTCTGAAGAACCGATGCTTGCCTCAGCACAAACCTCAGTATACAGTCCGGCCACACACG
          GTAATGCACCAGCGATGGCTACCTGAACAAAAACCCCACAATGCAGTGCGCCCACTCACC
          CTCCTACAGCAGAGATGGCTCCCTGAACACAACCCTCAATATACAGTCTGTCCACTCACC
          ATTCTACAGCATCGCTGTCTGCCTCAACACAAACCTCAATATACAGTACGCACAGACACC
          ATCCTACAGCAGCGCTGGCTGCCTCAACAAAAAGCGCAGTACACTGTAAGCCCACATACT
          ATACTTCAACAGAGATGGCTACCTAATCAAAACTCCCAATATACAGTATGCCCACATACC
          ATGCTGCAGCAGCGCAGGCTCACACAACACAAACCTCAATATTCAGTCAGCCCACACACT
          ATGCTGCAACAGCGCTGGCTCCCACAACACAAACCTGATTATTCAGTCAGCCCTCACACT
          GTCCTGCAGCAACGAAGACTACCACAACACAACCCACAGTACCCTGTCTCCCCGCAGACC
          GTGCTGCACCAGCGAAGGCTACCTCAAGAAAACCCTCAGTACCCCGTCCCACCACAGACC
          GTACTGCAGCAACGAAGGCTCCCTCATCACAACCCTCGTTACCCTGTCCCTCCACAGACC
          GTCCTGCAGCAACGAAGGCTACCCCAACACAACCCTCATTACCCTGTCCCCCCACAGACC
          GTGCTGCATCAACGAAGTCTACCTCAACACAACCCTCATGACCCAGTCCCCCCACAGACC
          GTTCTGCAGCCACGTAGACTCCCTCACTATAACCCTCATTACCTAGGCCCCCCAAAGACC
          GTCCTGCAGCCACGAAGATTACCTCAGCAAAACCCTCATTACCCTGCCCCCCTACAGACC
          GTACTGCAGCACAGAAGGCTCTCACAACATAAACCACATTACCCTGTTCGCCCACACACC
          ATACTACAGCTACGATGCCTCCCACGGCAAAACCCCCATTATCCTGTCCGCCCCCAGACA
          GTCCTGCAGCTACGCTGGCTCCCTCGACAAAACCCTCATTATCCAGTTCGCCCACAGACA
          GTCCTGCAGCTACGATGGCTCCCTCGACAAAACCCTCATTATCCAGTACGCCCACAGACA
          GTCCTGCAGCTACGATGGCTCCCTCGACAAAATCCTCAGTATCCAGTACGCCCACAGACA
          TTGCTTCAGGTTCTTTGTCTCCCACGCCAGAATCCCCAGTATCCAGTCCGCCCGCAGACA
          GTCCTGCACCTCCGTTGCCTCCCACGGCATGACCCCCAATATCCAGCGCGTCCACAGACT
          GTCCTGCCTCTCCGATGCCTACCGCGACACCATGCACATCACCCAGTCCGCTCAAAGACA
          TTACTCCAGCTACGTTGCCTCCCACGACACTACCCGCAGTAGCCAGTGCGCTCCCAGACG
          GTCCTGCAGCTACGATGCCTGCCCCGACACTACCCACAATAGCCTGTGCGCTCCCAGACC
          GTCATGCAGCTACGATGCCTCCCGCGACACTACCCACAGTAGCGGGTTCGCTCACAGACC
          GTCCAACAGCTACGATTCCTGCCGCGACACCACCCACACTATCCACTACGCTCACACACA

          CGGGACACGTTTTATTCCTCTGAACTTTATCATTATGCTCTCCGTGGTAGGCGTAATCGT
          AGAGATACTCTATATTCGGCAGAAGTGTCACAGGACGCCTTAGGAGGGCGATGCCTACGC
          AGAGAAACCCCCTATTCGACGGACCTATCAGACGAGGCGGTCAGAAGCCGTCGACTGCGC
          AGGGAAAACCTGGACTCGACGGATCTCTCGGACGAAGCGCTGAGCCGCCGTCGTCTGCGG
          AGGGAAACCGCCTATTCAACGGACCTATCTGACGAGGCGCTGAGAAGACGTCGACTGCGG
          AGAGACACTCTATACGCTACCAACTTTTCAGACGAAGCTCTAAGAGGACGGCGGATCCGC
          AGAGACACTCTCTACTCCACGGAACTTTCCCAAGAAGCTCCTAGTGGGTGGCGAATAAGC
          AGCGAAACTATACAGCCAATGGAACCTTCACAAGAATCGCTGAGAGGACGTCGTCTACGC
          CGGGAAACACTACATACGACTGAACTCTCCCAAGAAGGTCTAAGCGATCGGCGAATACGC
          AGGGACACTCTATATTCGACAGACCTTTCACAGGACGGTGTTAGAGGGCGACGAATGCGT
          AGGGAAACGCTGTATTCGACGGAACTTTCACATGACGGTCATAGAGGCCGGCGAATGCGC
          AGGGATCCTCTATACTCGACCGAACTGTCACACGATGCTCTAAGAGGACGGCGAATACAC
          AGGGACACTCTCTATTCGACGAAACTATCACAAGAAACACTGCGCGGCGGTCGCATCCGG
          TGCGAAACTCTATACTCTACTGACCTCTCACAAGATGCTCTAAGTGGCCGACGGATACGC
          AGGGAAACTCTTTACTCGACTGATATTTCACAAGATGCTCTCAGAGGGCGGCGCATCCGC
          CGGGACACTCTATATTCCACGGATCTATCGCACGAGGCCCTGAGAGGGCGTCGCATACGT
          CGAGACGCACTGTATTCGACCGAACTTTCACATGAGGCACTGAGTGGGGGCCGAGTGCGC
          CGCGAAACGCTGGATTCCACTGAACTTTCGCACGATGCACTGAGGGGGTGTCGATTCCGC
          CGGAACACGCTGTATTCCACGGAACTTTCGCAGGCAGCTCTGAGGGGGTGTGGATTACGC
          AGCGACACGCTGTATTCGACGGAACTTTCCCAGGAGGCTCTGAGGGGCTGTGGATTTCGT
          CGGGAAACAGTTTACTTTACCGAACTTTCCCAGGATGCTCTCAGGGGGCGCCGCCTTCGA
          CGGGAGACGCTGTACTCTACCGAACTTTCACATGAGGCCCTGAGGGGTCGCAGATTACGT
          CGGGATACACTATACTCCACGGACATTTCGCATGAGGCGCTCAGGGGGCGTAGATTACGT
          CGGGATACACTATACTCCACGGACATTTCGCATGACGCCCTGAGTGGGCGAAGATTACGT
          GGGGACACACTATACTCCACGGACATTGCAAATGAGGCGCTGAGGGGGCGTCGATTACGT
          AGGCAGACGCTATACTCCACAGAGATGTCGCATGAGGCGCTGAGTGGGCGACGGTTACGC
          CGGGACACACTATACTCCACGGACCTATCGCATGAGGCGCTGAGTAGGCGGCGATTTCGT
          CGGGACACACTATACTCCACGGACCGTTCGAATGAGGCGCTGCGGGGACGTCGATTACGT
          CGGGAGTCTCTATACTCCACGGACCTTTCGCATCATGCGCTTAGGGGGCGGCTATTCAGT
          CGAGACACACTATACCCCTCCGATTTTTCACATGATGCACTGTGGGGGCGGAGATTACGT
          TGTGACACACTGTACTCCACAGAGCTTTCGCATGAGGCACTGAGGGGGCGTCGTTTACGT
          CGAGACACCCTCTACTCCATGGAACTGTCGCATGAGGCTCTGAGTGGGCGTAGATTACGT
          CGGAACACAATATACTCCACGGAACTGTCGCATGAAGCTCTCAGCGGGCGTCGATTCCGA
          CGGAAAACAGTGTACTCCACGGAACTTTCCCAAGAAGCTCTCCGCGCGCGTCGCTTTCGG
          CGCCACACATTCTACTCGACTGAGCTTTCGCATGACGCTGTTAGCGGTCGTCGATTTCGC
          CGCGACACATTATACTCGACGGAACTTTCGCATGAGGCTCTGAGCGGACGTCGATTTCGT
          GGGAAAACTCTATATGCCACGGATCTTTCTCATGAGGCACTCAGTGGTCGTCGCATTCGA
          CGGGATACGCTATATGCCGCGGAACTATCACATGAGCCACCCAGCGGGCGTCGGATGCGT
          CGGGATACGCTATATGCCACGGATCTCTCCCATGACGCTCTCAGTGGGCGTCGGAATCGT
          CGCGATACGCTATATGCCACGGATCTCTCACATGAGGCTCTCAGGGGCCGTCGAAGACGT
          CGCGATACGCTATATGCCACGGACCTCTCACATGAGGCTCTAAGTGGGCGTCGAAGACGT
          CGGGATACACTATATGCCACGGATCTATCACATGAGGCTCTCAGTGGGCGTCGAATTCGT
          CGGGATAGTCTATATGCCACGGAGCTGTCACATGAGGCGTTCAGTAGGCGTCGAATTCGG
          CGGGATACGCTATATCCCACGCATCTCTCAGATGAGGCTCTCAGTGGGCGGGGAATTCGT
          CGAGACGCACTTTACTCCACGGAACTCTCCCATGACGCTCTGAGCGGGCGCGGAATACGT
          CGGCACCCCCTACATTCCCCAGAACACTCACAAGAAGCTCTGAGTGGGCGTAGAATACGT
          CGGCACACCCTACATTCCCCGGAACACTCACAAGAAGCTCTGCGTGGGCGTAGAATACGT
          CGGCACACCCTACATTCCCCGGAACACTCACAAGAAGCTCTGCGTGGGCGTAGTATACGT
          CGGGACATGCTATGTTCTACAGAGCTTTTCCTCGATGCTTTTGGCGGACGTCGTATACAT
          CGGGACACGCTGTATTCCACAGAACTTTCCCATGAAGCCCTCAGTGGCCGACGAATTCGT
          CGGGACACGCTATATTCCTCTGAGCTTTCACATGAGGCTTTCCGTGGACGTCGTAATGGG
          CGAGACACACTTTATTCCTCTGACCCTTCACAGTAAGCTTTGCGTGGCCGTCGCTTTCGG
          CGTGACACACTTTATTCCTCTGAACTTTCACAGTAAGCTCTGCGTGGACGTCGTATTCGG
          CGGGATCCTCTTTACGCCTGTGAAGTGTCACAGTACGCTATCCGCGGACCTCGTATGCGT
          TGTGACACACTTTAGTACTCGGAACTTTATGATTAAGCTCTTCGTCGCCGTCGTATTCGG

          ACGTGAAATAAAAGTGACGTACGCCATCGTCAAGATGTCTACACATCCTGACTACATCAG
          ACTTGGAAGAACAGCGAGATAGGCCAACGAGAAGACGCCGAGAATTCCTGGCCCCATCGG
          GCTAGCAGGGAGAGAGAGATAAGACATGGGGTAGATGCCGAGAACTCCTGCCCTCATCAC
          ACTAGCAGGGATAGGGAGATTGGGCAGGGATTCGACGCGGCGAACTCCTGGCCACACCAG
          ACTAGCAGAGACAGAGAGCTGGGCCATGGAGTCGATGCCGATAATTCCTGCCCACATCAG
          ACTTGCTATCACAACTATAAACGTCACACTGAGGAGGTCGACAACTCCTGTCCGCATCGT
          ACTTTCAAAAACAGTGACATACCTCATCGTGAAGATGCTGACACGTCGTGCCTGCATCGC
          ACTTGTAAGGAAAGGGAAACCAGCCAACGTAGCGATTCGGAAACGCCCTGCCTGCAAGGA
          ACGTGAGATAACAGAGATATAAGACAGCGGGACCTAGCCGACACCTCTTGACTGCACCGC
          TCATGGGATAAGAGAGAAATACGTCAGAGAGATGTTTCCGACACGTCTTGAGTGCATCGT
          ACGCGGGAAAACAGAGACATACGTGAGAGAGAGGTTGCCGAAACGTCCTGACTGCACGGC
          ACATGGGATAAAGGTGAGATACGTGATCGAGAAGTTGCGGAAACACCGTGGCTCCAGCGC
          ACATGTAATAAAAGTGAACTCCGGCATCGCGAAGATGCCGACAGTTCCTGAGTGCAGCGT
          GCGGGAAATAACTGTGAAATGCGGCATAGAGAAGAACCTTACACCACGCGATTACACCGC
          ACAAGCGATAAAAGTGACATACGACATCGTGAAGATGCCTACACATCATGCTTACAGCGC
          ACGTGGCATCAATGTGAAATCCGTCTCCGGGAAGATGTCGAAACCTCCTGACTGCAGCGG
          ACCTGGCATCAGAGGGAAATCCGTAACCGGCATGAAGTCGACACGTGGTGCCTCCAGCGA
          ACTTGGAATCAGAGCGATATACGGTACCGCGATGAGGTTGTCACTACTTGTCTGGATCGT
          GCGTGGAATCAGGGCAAAATGAGTTACCGGGAAGAAGTCGACAGCTCCTGACTGCAACGG
          ACGTGCAATCACGGCGAAATCCGACACCGGGAAGAAGTCGAAAGCTCCTGACTTCAACGA
          ACGTGGAATCATATAGATATCCGGCAACGTGAGGATGTCGAAATCTCAAGTCTTCAGCTA
          ACCTGGAATCAGAGCGAAATCCGTCAACGTGAAGAAGTCGTCACTTCGTGGCTACACCTA
          ACATGGAAAAACAGTGAGATCCGTCACCGTGAGGAGGTGGAAACCTCATGACTACCTCGC
          ACATGTAAACACAGTGAGATCCGTCACCGTCAAGAAGTCGATACCTCATGGCTACAGCGC
          ACGTGGAAACATAGTGAGATCCGCCACCGTGACGAAGTCGACACCTCCTGACTACAACGC
          ACATGGAAACAGAGTGAGATCCGCCATCGTGAAGACGTGGACACCTCATGACTACAACGT
          ACATGGAAACAGAGTGATATCGGTCACCGAGAAGTCGTCGAGACCTCGTGACTACACCGA
          TCATGGAATCAGAGTGACTTACGCCACCGAGAAGTGGTCGAGACCTCCCGACTACATCGA
          AAATGGAACCAGAGCGTTATCCGTCACCGTGAAGACGTCGAAACCTCGTGAATACATCGT
          ACATGCAAACGGAGTGAAATACGGCACCGAGAGGAATTCGACACGTCCTGACTACATCGT
          ACGTGGAAACAAAGGGAACTCCGTCATCGTGAGGAAGTCGACACGTCCTGTCTGCATCGA
          ACGTGGAATCAGCGTGAAATACGACACCGGGAAGACGTCCACACCTCCCGACTACATCGA
          ACTTGGAAACAAAGCGAGATTCGCCATCCGGAACAAGTCGACACCTCCTGTCTACATCGA
          GCTCGGAATCAAAGCGACATTCGTCACCCGGAAGATGTCGATACATACTGCCTACATCGC
          ACGCGGAATCATAGGGAAATGCGCCACGCGGAATACGTTGACACATCCTGGCTACATAGA
          ACGTGGGAGCTCAGTGAGATACGTCATGGGGAAGAGATCGACACTTCCTGACTCCATCGA
          ACATGGAACCAGAGTGAAATACGTCACCTAGAGAAAGCTGATACATCTTGGCTCCACTGG
          ACTTGGAACCAAAGTGATATACGGCACCTAGATGAAGCTGATACCTCTTGATTCCACTGG
          ACATGGAAGCAAAGTGAGATACGTCACCTAGAGGAAGCCGAAACATCTTGATTCCACTGG
          ACGTGGGAACAAAGTGAAATCCGTCACCTAGAAGAAGCCGATACATCTTGATTCCACTGG
          ACGTGGAAACAAAGTGAAGTACGACAACTGGAAGAAGGCGATACATCGTGATTCCACTGG
          ACGTGCAAACAAAGTGATATACGCCGCCTAGAAGGTGCGGATACATCTTGCCTCCACAGT
          ACGTGGAAACAAAGTGAATTACGTCACCTAGACGAACCCGATACATCCTGCCTCCGCTGG
          ACTAGGAATCAAAGCGAAATACGTCACCTAGAAGAAGCCGATACGTCTTGACTCCATTGG
          ACGTGATATTATAGGGAACTTCGTCATCGCGACGAGGTCGACACATCTTGACTGCGTAGG
          ACGTGAAATTGGAGGGATATACGTCATCGCGAAGATGTCGAGACGCCCTGGCTCCGTCGG
          ACGTGACATTGGAGGGAAATACGTCATCGCGAAGAGGTCGAGACGCCCTGGCTTCGTCGG
          ACGTGACATTGGAGGGAAATACGTCATCGAGAAGATGTCGAGACGCCCTGGCTTCGTCGG
          AAATGGAAGAAAAGTGACATGCGTCATCGCGAAGAAGTAGACGCATCGTCTCTGCATCGG
          ACGTGAAACAATAGTGACATACGTCATCGACAAGAGGTCGACACGTCGAGACTACAACGG
          ACATGAAACAAAAGTGACATACGGTATCGTCAAAATGTTGACACATCGTGACTACACCAG
          ACGTGAAATAACAGTTACATACGTCAGCGTCAGGACGTCGACACGTCGCGCCTGCATCAG
          ACGTGAAATAAAAGTGACATCCGTCATCGTCAAGACGTCGACACGTCGTGAGTGCATCAG
          ACGTGCAATAAAAGTGACTTCCGACATCGACAAGATGTAGACACATCCTGACTGCATCAG
          ACGTGAAACAAAAGTGACATTCGTCATGGTCAAGATTTCGACACATCCTGCCTCCGTCAG

          ATTCTCTAATTTCAGCCTGTACGGCAATATTTCTACAGTCTTCGAGATACTGCTCTTCTG
          TTATTCTACTTGCAGGCCGTGCGCCAAGATTTGTACAGCCTTGGCGATACTGCCCTGCTC
          TTTTTGTACTTGCATGATGTACGCTCATTTATTTACAGGCTGGGAGATGCAGCCCTTCTC
          TTTTTAGACTTGGATCAGGTACGATCATATATCTACAGGCTGGGAGATCCCGCTCTCCTC
          TTTTTCTATTTGCATCATGTTCGCTCCTATATGTACAGGCTGGGAGAGCCAACCCTTCTC
          TTCTTCTATTTTCACCCAGTACGTCAAGAGTTGTATAGTCTTGGAGAGACAGCCCTTCTC
          TTCTTCTAATTGCAGCCGGTGCGTCATCACTTGTATAGTCTAGGGGATTCAGCCCTTCTA
          TTCTTCTACTTGCATCCCGTTCGGCCTCATCTATACAGCCTAGGAGAGACTGCCCTACTC
          AGTTTTTCAATTCAGCCAATGCGGCAATACTTCTACAGGCTGCGTGAAACGGCACTTCTC
          CGATTCCCTTTGCAACCCGTCCGGCGCTTATTCTACAGACTGCGTAAGACTGCACTTCTT
          AGTTTTTCATTCCACTCCGTGCGGCAATACTTGTACAGCCTGCGTGACACTGCTCTAATC
          ATTTTCTCATTGCAGCCCGTGCGGCATGACTTGTACATCCTGCGTGAGACTGCTCTTCTC
          ATTTTCTCATTACAGTCAGTGGGGCATTACTTCTCTAGACTCCTAGAGACGGCTCTTCTA
          ATTTTCTCCATACAACCCGTTCGTCAATACTTATATAGTCTGGGGGAAACTGCACTTCTC
          ATATTCCCATTCCAGCCGGTGCGTCACTACTTGTATAGTCTCGCCAATACGGCTCTAATA
          CCTTTATAATTACAGCCCGTACGGCACAACTTGAATAGGTTGGGAGAGACCGCTCTACTC
          ACTTTATAATTGCAGCCTGTACGGCATCACTTAAAAAGACTGGGAGAGACTGCCCTACTC
          ACCTTATAACTCGACCCAGTACGTCATCACTTCAACGGTCTGGGAGAAACTGCGCTCCTC
          GCCTTGTACTTGCAGCGGGTGCGCCACCACTTGAACAGCCTGAGAGATACAGCTGTCCTA
          ACCTTGTAATTCCATCCAGTACGTCACCACTTTAAAAGACTAGGAGAGACTGCGTTCCTC
          ACCTTTTAATTCCAGCCGCTTCGGGATTACCTAAAATGGCTTGGGGATACAGCTCCACTA
          ACCTTATAATTGCAAACGGTTCGTCACTATTTGAAAAGACTGGGAGATACTGCTCTTCTC
          ACCTTATAATTGCAGCTAGTCGGCGACTACTTCAAAAGACTAGGTGAGACATCTCTCCTC
          ACCTTATATTTCCACCCGGTACGTGACTATTTGAAAAGCCTGCGTGATACTGCTCTACTC
          ACGATTTAATTGTATCCCGAACGCGATTACTTGAACAGACTCGGTGAAACAGCTCTCCTC
          ACCTTAAAATTGCAGGCGGTACGGGACTACCTAAAAAGACTGGGTGAGACAGCTCTTCTC
          ACCTTCTACTTACCGCCGGTGCGTGACTACTTAAAAAGACTCGGACAGACGGCTCTCCTA
          ACCTTATAATTGGAGCCGGCTCGTGAGTACTTGAATAGACTCGGAGAGACTGCTCTACTT
          ACCTTGTAACTGGAGCCGGTACGTGATTATTTGAAAAGACTGGGTGAGACTGCTCTTCTT
          ACCTTATACTTGCAGCCGGTACGAGACCATTTGAAAAGACTGGGAGACACAGCACTACTG
          GCCTTGTAATTGCAGCCGGTACGAGATTACTTTAATAGCCTGGGAGATACGACACTTCTA
          TCCTTATATTTGAAGCCGGTCCGGCACTACTTAAAAAGACTGGGTGAGACTTCTCTTCTG
          TCCTTTTACTTGCAACCGGTTCGACACTACGTTAAAAGACTGGGAGAGACTTCTCTTCTC
          TCCTTTGAATTGCATCCCGTACGTCACTACGTTAAGAGCCTGGGAGATACTTCACTTCTC
          TCCATTTAATTGCATCCAGTACGTCACTACGTCAAAAGCCTTGGAGAGACTCCCCTTCTC
          TCATTTTAATTTCAACCTGTTCGTCAGTACGTAAAGAGCCTAGGAGAGACCTCTCTTCTT
          ATTTTTTACTTGCAGCCAGTACGTCACTACTTCGAGAGATTTGGAGAAACTGCTCTGCTA
          ATTTTTTACTTGCAGCCAGTACGCCACTACTTAGAGAGACTTTGCGAAACAGCTCTTATC
          ATATTTTACTTGCAGCCTGTACGTCCCTACTTGGAGAGAGTTGGAGAGACTGCTCTCATT
          TTTTTTTACTTCCAGCCCGTCCGTCAGTACTTAGAGAGACTCGGAGAGACTACACTTCTC
          ATTTCTTATTTGCAACCCGTACGTCACTATTTGGAAAGACTCGGAGAGACTGCTCTACTC
          ATTATTTACTTGCAGCCGGTGCGCCAATACTTGAATAGACTTGGAGAGACTGCTCTTCTA
          ATGTTCTACTTGCAGCCTGTACGTCACTACTTGGAGAGACTTGGGGAGACAGCACTTCTC
          ATATTTTACTTGAAGCCAGTTCGTCATTACTTCGGCAGGCTGGAAGACACGGCACTTCTC
          ATTGTGTAATTTCAACCTGCACGTCAGTACTTTTACACCGTAGGAGAGACTGCTCTACTC
          ATTTTATACTTGCACCCTGCAGGTCAGCACTTATACACTGTTGGTGAGACTGCTCTACTC
          ATTTTATAATTGCACCCTGCAGGTCAGCACTTATATACTGTTGGTGAAACTGCTCTACTC
          ATTTTATAATTGCACCCTGCAGGTCAGCACTTATATACTGTTGGTGAAACTGCTCTACTC
          TTATCATATTTACAACCCGTCCGTTCGTATTTGTACTGTCTTGGCAATACTGCGCTCCTG
          ATTTTATAATTTCAGCCCGTACGGCAATACTTTTATAGTCTTGGAGAAACTGCTCTCCTG
          ATATTCTAATTTCAGCCCGTACCGCATTATGTCTACAGTCTTGGAGACACTCCACTCCTA
          ATTATGTATTTTAAGCCCGTCCGTCAATATTGCTATAGTCTAGGAGACGCTCCTATTCTC
          ATTATAAATTTTCACCCCGTACGACATTATTGCTATAGTCTAGGAGACGCTCCTCTTCTG
          ATCATCTATTCTCAGCCCGTGCAACAATATTTCTATAGTCTAGGGGAACCTCCTCTTCTG
          ATTCTCTAATTTCAGCGCGTACATCTATACTTGTACAGTCTCGGTGACACTCCTCTTCTT

          ACTTGGGGCCAGTTTTGAATGCAAGGCACTGAAAACATTGCTGTAGTTCCAAACATTTGC
          ACTTGGGGGAATTGTTGAATCCAAGGCACAGACAAAATCACAGTTATGCCTAATATATGT
          ACCTGTCGGCACTGTAGTATGCATGGTACTGAGCATACCACCGTTGTCCCAAAGGTGTGT
          ACCTGTCGGCCCAGTTGTATCCATGGTACTGATAATACAACCGTTGTGCCTAAGATTTGG
          TCATGTCGGCACTGTGGTATACAAGGTACTGAGAAGAGCACCGTTGTTCCAAAGATTTGG
          ACCTGCGTACACTGTTGGATGCAATGGACGGAGAAACTAACGGTAGTACGTAACATACGT
          ACGTGTGGGCAGTGTTGAATGCATGGCACAGCACAAATAACCGTAGTACCTAACATCTGG
          ACGTGCGGGCACCGGTGTCTCCATGGCACTGACAGTATAACGATGGTACCGGATCTTCGT
          ACTTGCAGCTGGTGTTGAATATACGGGCCTGATAGGATTACTGTGGTGTCGAAGATGTGT
          GCATGCGGCCAGTGGTGAATCAAGGGCACGGATCGTATTTCCGTTCTATCCAACATATTT
          ACTTGCGGTCCGTCATGAAGAAATGGCCCGGAGCAAATTGCGGTTGTATCAAAAATATGT
          CCCTGCGGCCAGTGGTGTATTCAGGGACCTGACAAGATTGCGGTTGTATCGAAAATATGT
          ACCTGTGGGCACTGCTGAATCCATGGACCCGATAACATGACCGTGGTTTCAAAGATTTGT
          ACCAGCGGCCAGGGTTGAATACATGGGCCGGAAAATATTACTGTTCTGTCAAAGATCTAT
          ACTTGCGGCCAGTGTTTGATCCAGGGCCCCGATAAAATTACCGTTCTATCAAAGATAAAG
          CCATGCGGACAGTGTAGAATCCCGAGCACAGAACAAATTACGGTCGTCCCAAACATTTGT
          CCTTGCGGCCAATGGTGGTTGCACTGCACCGAGCATTTTACGGTCGTCCCAGACATGAGT
          CCCTGCGCCCAGTGTTGTCTTCAATGCACCGAGCATTTCACTGTCGGACCAGACATCTTT
          CCTTGCGGCGAGTGTTGCATGCACTGGACCAAACACTTGACCGTGGACCCTGATATGTGT
          CCTTGTGGACACTGTTGGATGCAAGGCACCAAACACTTTACGGTCGTGCCAGATATCTGT
          CCCTGCGGTCAGGGGTTGATTCAAGGCATCGATAACATACCGGTCTTTCCAAACATTTGG
          CCTTGGGGCCAGGGCTGGATGCATTCCACTGAACAAATCACGGTCTTCCCAGACATGTGT
          CCTTGCAGCCAGAGTCGGATGCAATGCACTGAACATATTACGGTCGTCCCAGATTTTTGT
          CCCTGCGGCCAGTGTCGGATGCAATGCACTGAACAGATCACAGACGTTCCAGACTTTTGT
          CCTTGCGGCCATTTTGGGATTCACTGCACAGAACATATTACAGACGTGCCAGACTTTTGT
          CCTTGGGGCCAGTGTCGGGTACAATGCACGGAACATATAACGGACGTCCCAGACTTTTGT
          CCAAGCGGCCAGTGTTGGCTGCAATGCAGGGAACAGATGACAGTCGTCCCAGACTTTTGT
          CCATGCGGCCAGTGTTGTGTGCAATGCACGGAACATATAACTGTCGTCCCGAACTTTTGT
          CCTTGCGGCTATGGTAGGGTTCAATGCACGGAACAAATTTCTGTGGTTCCAGACCTTTGG
          CCTTGGGGTCAGTGTTGTATGCAATGTAGTGAACAGATAACGGTCGTCCCCGAGGTATGC
          CCTTGCGGCCACGGTTGGATGCATTGCACTGAACAGATTACGGTCGTCCCGGACGTGTGT
          CCTGGCGGTCAGTGCTGGTTGCAACGGACGGAACATATTACGGTTGTACCTGACTTTTGG
          CCTAGCAGCCAGTGTTGGATGCACTGCACTGAGCACATTACCGTCGTCCCAGATTTATGT
          CCTCGGTGCGAGTGTTGGATGCAATGGACTGAGCATCTTACGGTCGTCCCCGATTTTTGT
          CCGAGCGGACAGTGGTGGATGCAATGGACTCAACAAATTACGGTTGTTCCAGACTTTTGC
          CCTAGCGGCCACTGGTGTATTCAGTGGACTGAACACATTACGGTTGCCGCAGATTTTTGT
          CCTTGCCGCCAGTGTTGCATTCACCGCTCAGAAAACATAACCCTGGTTCCAGACATTTGT
          CCTTGGCGCCAATGTTGCATACAACGGACAAAGTACATTACGGTGTCTCCTGACATTTGT
          CCTTGGCGCCAGTGTTGCATCCAACGCACAGATAACATTACGGTGGCGCCAGACATTTGT
          CCTTGGCGGCAGCGTTGCATCCAACGCACAGATAATATTACGGTGGCTCAAGACGTTTGT
          CCATGGCGGCACTGTTGCATCCAGCGCACAGAAAATATAACGGTGGCTCAAGAGATGTGT
          CCCTGGCGTCCGTGTTGTATCCACCGCCCAGCAAACATATCGGTGCGACCAGATATTTGT
          CCCTGCCGTCAGTGTTGCATACAACGACCTGAAAAGATGACGGTGGCTCCAGACAATTGC
          ACTTGTCGTCACTGTTGCATCCATCGCACAAAAAACATGACTGTTTTTCCAGAAATTTGT
          ACTTGCGGCGACTGTTGACTACAATGCACAGACAACATCACCGTGGCTCCGGACATTTGT
          ACGTGGGGGCAGTGTTGAATCTACTGTACAGAACACCTTACGCTTGTTCCTGACATTCGA
          ACGTGGGGGCAGTGTTGAATCTACTGTACAGAAAACCTTACGCTTGTTCCTGACATTCGA
          ACGTGGGGGGAGTGCTGAATCTACTGTACGGAAAACCTTACGCTTGTTCCTGACATTCGA
          ACCTGGGGCCAGTGCTGAATGGATGGTACTGACAACATTTCAGTGGTTCCCAATACCGGT
          ACTTCTGGCCACTGTTGAATACAGTGTACCGATAACATAACAGTTGTTCCAACAATCTGC
          ACTTGGGGCCAGTGGTGCATTCAGGGCACTGAGAATATTACTGTAGTTCCCAACATTCGG
          ACCTGGGGTCAGTGTCGAATGCGGGGCACTGAAGACATTACTGTGGTTCCAAACATTTGC
          ACAGGGGGGCAGTGTTGAATGCGGGGCACTATAGACATTACGGTTGTTCCAAACATTTGT
          ACATGGGGGCAGTGCTGAATGCAGGGCACTGAAAACATTACGGTTGTCCCAAAGATTGGT
          ACTTGGGGCCAGTTTTGAATGCACGGCACTGAACACATTACTTTAGTTCCAAACATTTGC

          CACGGAAGTTCGGACACTC
          CAGGGAAGAGCGGACGCCC
          CAGGGGAAATCGCACACTC
          CAGGGAAGGTCGCACACGG
          GAGGGAAGATCGCACAAGC
          CACGGTAGTTATGAGACGC
          CAGGGAAGCTCGGACACGC
          CAAGGTAGCTCAAATACCC
          CACGGCAGTTCCGAGGCAT
          CAAGGAAGTTCGGAGACGT
          CATCGAAGCTCGGAGAATT
          GAGGGGACGACTGAGACGC
          CAGGGAAGGTCGGATACGC
          CAGGGCAGGTCAAATACCC
          CAGCGTAGGTCTGAGACAC
          GACGGAAAGTCAGATACCA
          GACGGAAGCTCGGAGTCTT
          GAGGGGAGCGCGGACACCA
          GACGGGTGGTCGGAGACAA
          GACGGAAGGTCAGAGACAA
          GACGGCCGTTCAGACCCAA
          GACGGAAGTTCAGACCCCA
          GAGGGAAGTTCTGAGACAA
          GAGGGAAGTTCTGAGACAA
          GAAGGAAGTTCAGAGACAA
          GCGGGAAGGTCCGAGACAA
          GAGGGCAGTTCAGAGACAA
          GAGGGAAGTTCCGAAACAA
          GACGGAAGGTCAGAGACAA
          GATGGAAGATCGGACACAA
          GATGGAAGTTCAGACACAT
          GAGGGAAGTTCAGAGACAA
          GAGGGAAGCTCAGAGACCA
          GATGGAAGTTCAGCGACGG
          GAGGGTAGTTCAGAGACCA
          GAGGGTAGTTCAGAAACCA
          CAGGAATGGTCAGACACGA
          CACGAGTGGTCAGAAACAA
          CAGGAGTGTTCGGAAACGA
          CAGAAGTGGTCAGAAACGA
          CAGGAGTGGTCAGAAACTT
          CAGGAGTGGTCAGACACGA
          CAGGAGTGGTCAGAGACGA
          CAGGATTGTTCAGAGACGA
          CAGGGAGGGGCGGAAACAC
          CAGAGAAGGTCGGACACGC
          CAGAGTAGGTCGGACACGC
          CAGAGTAGGTCGGACACGC
          CAATGTCGGGCGTATACAC
          CAAGGAAGGTCGGAGCCTC
          CAGGGAAGTACTGACTCTC
          CAGGGCAGGTCGGACACTC
          CAGGGCAGGTCGGACACTT
          CAGGGCAGGTCGGACACTG
          CAGGGCAGGTCAGACACAC

