 55 675
Haliotis_ TTACGCCGGGTTCCAATCAGCATGTTCTGCGTTACGCCTACGAATCAAACACATTGCACT
Chiton_ol CTTCGTCGGCTTTCCATCAGAATAGTGCGTTTTACCCCTGCGTGTCAATACTAGAATCCG
Chaetoder GTTCGTCGGGTTTCTATTAGCATAGTCTGGGTAACGCCGACAATCCAATCGTATTACCCG
Greenland GTGCGTCGAGTTTCTATGAGCATAGTCTGTGTAACGCCAACTGTGCATTCGTACAACCCT
Neomenia_ GTGCGTCGGTTTTCTATGCGCATAGTCTGTGTGACTCCAACAATGCAATCGAATAACCCT
Gadila_to CTCGTGCGCGTTTCGGTGAGTATAGTTTGCGTTACTACTACGAGACAGTCCAAAAACCCG
Laevipili CTCCGACGAATCTCATTAAGTATAGTCTGGGTGACCCCAACTAGACATTCAGAGTACCCG
Octopus_v GTACGACGAGTTTCTCTCATAATCATTTGTGTAACGCCTACCTGGCAATCGTATAATCCT
Mercenari TTTCGAGGGGTCTCTGTCAGCATGGTGTGCGTCACGCCTACGAGGCACCCGTAGAAGCCC
Myochama_ CTGCGATGGGTTTCAGTCAGCATGGTTTGGGTGACGCCGACGAGGAAGCCGTAGAAGCCG
Astarte_s CTGCGAGGTGTATCAGTCAGGGTAGTTTGCGTGACGCCCACGAGGCACCCTGAGAAGCCC
Neotrigon CCACGAGGGGTTTCGGTAAGGATGGTGTGCGTCACTCCAACGAGTCAACCATACAAGCCG
Pinctada_ TTACGAGGAGTACCCATCAGCATGATGTGTGTGACGCCGACAAGGCAATCCAAAAAACCC
Solemya_v CTACGTGGAGTATCAATTAGTATGGTGGGCGTACCGTCTTCGAGGAAGTCATTGAAGCCC
Ennucula_ CTTCGTGGGGTATCAATAAGGATGCTGTGCGTCACAACTACGAGGCATCCGTATAAGCCC
Doris_ker TTACGGCGGGTTACATTTAGCATTATCTGCGTCACCCCAACGAGGCACTCGTACAGCCCT
Pleurobra TTTCGTCGAGTTCTTATCAGCATTATGTGCGTGTCCCCAACGAGACAATCCTAGAGTCCT
Fiona_pin TTACGGCGTGTAACCATCAGCATAATGTGGGTCACCCCTTATAGTAACTCGTATCGCCCG
Bathydori CTGCGCCGAGTGACCATCAGCATAATGTGTGTGACCCCTACGAGACAGTCTTAGTGTCCT
Architect CTGCGGCGAGTCACCATCAGCATAATGGGTGAGACCCCCACGAGCCAATCGAAGAGTCCA
Rissoella TTACGACGAGTCGCCATCAGGATGATGAGTGTACCCCCGACCTGGCAGGCTTAGAGTCCT
Hydatina_ TTCCGTCGAGTTACTATCAGGATTATGAGTGTACCTCCAACCAGACAGTCCTAGAGCCCT
Ophicarde TTACGGCGAGTTACCATCATCATAATGTGTGTGCTTCCAACCAGTCAGTCGTAGAGGCCC
Onchidell TTAAGTCGCGTTAGTATCAGCATAATGTGTGTGCTCCCAACCAGACATTCGTATCGCCCC
Microhedy TTACGCCGTGTTGCCATTAGCATCCGGTGTGTGCTCCCAACGAGACAATCGTAGAGACCC
Strubelli TTCCGGCGAGTTACCATCAGAATAAGGTGTGTGCTCCCAACGAGACAATCGTAGAGCCCG
Phallomed TTACGGCGAGTTTCGATCAGCATAATGTGTGTGCTTCCAACCAGACAAGCTCAGAGTCCC
Turbonill TTACGGCGTGTAACAATAAGCATAATGTGTGTTCTCCCTCCAAGACAATCTTAGAGTCCC
Siphonari TTTTGGCGTGTTACCATCAGCATAATATGTGTGCTCCCCACTAGACAATCGTACAGGCCG
Biomphala TTGCGCGGAGTCACAATCAGAATAATATGTGTGCCACCATCCCCCCAATCGTATAGGCCT
Oxynoe_vi TTACGTCGTGTGACCATCAGGATAATATGTGTTCCCACAACCAGATACTCGTAGAGGCCG
Tylodina_ TTACGACGGGTTACGATAAGCATGATGTGTGTCACCCCAACCCGACACTCGGATAGTCCT
Aplysia_c TTACGGCGAGTAACAATAAGAATTATGAGTGTTCCAACAACTAGACTATCGTAGAGTCCG
Clione_an TTTAGTCGAGTTACCATAAGTATAATCTGTGTGCCCCCAACAAGGATATCCTAGAGTCCT
Haminoea_ TTTCGGCGAGTTACCATTAGCATTATGGGTGTCCCCCCGATGAGACAATCGTAGAGACCT
Philine_a TTACAGCGAGTTAACATAAGCATAATGGGTGTCGCCCCGATGAGACAATCGGAGAGTTCG
Hinea_bra TTAAGTCGAGTCTCAATCAGTATAGTCTGCATTACGCCTACCAGTCAATCGGAGGGCCCT
Janthina_ TTACGTCGTGTCTCTATAAGTATAGTCTGCATTACGTCTACCAGACAATCGTACAGGCCT
Rubyspira TTTCGTCGAGTCTACATCAGCTTAGTGTGCGTTACCCCTACCAGTCAAGCGTAGAGCCCT
Littorina TTTCGTCGGGTCTCTATCAGCATAGTGTGCATTACCCCCACCAGTCAATCGTAGAGACCT
Polinices TTTCGCCGAGTCTCCATCAGTATTGTGTGCATTACCCCTACCAGTCAATGGTAGAGCCCT
Urosalpin TTACGACGAGTTTCTATTAGTATAGTGTGCATTACCCCCACAAGTCAATCGTACAGCGCT
Ilyanassa TTACGAAGAGTCTCCCTTAGCGTAGTTTGTATTACCCCTACCAGTCAATCGTATAGTCCC
Pomacea_d TTTCGTCGAGTATCAATCAGCATTGTCTGGATGACCCCTACCAGTCAATCGAATAGTCCA
Nerita_pe TTCCGACGTATGTCTATCAGAATTGTTTGTTTTTCGCCTACTAGGAAATCGTATTGTCCT
Pyropelta TTTCGACTAGTCTCTATCAGAATAGTGTGTTTGTCGCCTACCAGGCAATCGTATAGCCCT
Titiscani TTTCGACGAGTCTCTATCAGAATAGTGTGTTTGTCGCCTACCAGGCAATCGTATAGCCCT
Paralepet TTTCGTCGAGTCTTTATCAGAATAGTGTGTTTGTCGCCTACCAGGCAATCGTATAGCCCT
Lottia_gi TTACGGCGCGTCTCAATCAGCATATTTTGCGTGACGCCTACCAAGCAATCATAGAGCCCA
Perotroch TTGCGACGGGTTTCAATCAGCATACTCGGCGTGACGCCTACAAAGCAATCGTAGAGCCCT
Granata_i TTCCTCCGTGTTCCCATCAGCATGTTCTGCGTAACCCCTACGAAGCAATCCTAGTGCGCT
Prothalot CTACGCCGTGTCTCAATTAGCATTGTGTGCGTTACGCCCACCAAGCAAACATATTGGCCC
Monodonta TTACGCAGCGTTTCAATCAGCATTTTCTGCGTTACGCCCACCAAGCAAACGTAGTGGCCT
Phasianel ATACGGCGCGTTTCTATCAGCATGTTCTGTGTTACGCCTACCAAGCACACATAGAGCCCC
Lepetodri TTGCGCCGGGTTTCGATCGGCATGTTCTGCATTACATCTACTAATCAGCCATAGTGCTCT

          GGTGTACCTGGATCTTGCCCTGGACCTAATTTCCAAGGAAAGTGGAGGCACACTCACCGT
          CGGGTATCGGGATCTTGGCCAAGGACAGACATCCAGGGACATTGTCGCCAGAGTGAACGT
          CGTGTGTCCAGATTCGGACCGAGATCCAAGATCCAAGGACATTGTCGACAGACGCAACGT
          CGTCTGTCCAGATCGTGTGCTGGTTCGGACATCAATGGACACCGCCGTCAGACACAACGA
          CGTGTGTCCAGATCGTGTCCCGGTTCGGACATCCATGGCCATTGTGCTCAGACTCAACGA
          CGCGTATCGGGATCGTGGTCAGATCCGCACATTCAAGGTCACTGGTGCCACACACATGGA
          CGAGTGTCGAGATCCCGTCCAGGTCCTTATTATAAGGGAAAATGTTGTAATACCCAGCGC
          CGAGTATCGAGCTCCTGCCCACGACCGGATTATCACCGGAATTGCTGTCATACTCACCGG
          GGGGTGTCCAGTTCAGGTGCGGGTCGTGACTTTAAGGGAAACGGGCGACAAACTCAGCGT
          GGAGTGTCGAGTTCCAGTCCGGGGCCTGACTTTCATGGAAATGGACGCCAAACTCAAAGT
          GGGGTGTGGAGATCAGGTCCGCGTCGGGACTTTGAGGGAAATGGCTGCCAGACTCAGCGG
          GGGGTGTCGAGTGCCGGTCCGGGACGTGACTTTCAGGGAAAGTGCTGCCAAACCCAGCGT
          AGAGTGTCGAGTACGAGCCCGGGCCCCTATTTTCAAGGGAAAGGTTGCCATACTCAGCGC
          GGGTTGTCTGGATCATGGCGAGGCCCCTACTTCGAAGGGAACAGACCCCAAACCCACCGT
          GGGCTGTCGAGATCCTGGGCAGGTCCTTACTTTCAAGGTAATTGTTACCATACTAAGCGT
          GGCGTCCCGACAACGTGGCCAGGTTCTGAAGTTCAAGGAAAGTGCGGCCACACTCAGCGT
          GGTGTGCCGTCGACGTGGCCAGGACCAGATGTGCATGGAGAAAGTGGCCACACACATCGT
          AGATCGCCAACGTCGGGGCCAGCACCGGAAGCACAAGGCAAAAGAGGGCACACTCATCGT
          GGTGTGCCGACATCATGGGCCGGACCGGAAGTTCAAGGAAACAGCGGTCACACTCAGCGT
          GGTGTGCCGACATCCTGGGCAGGACCGGAAGTTCAAGGGAAAAGTGTTCAAACTCAGCGC
          GGTGTGACCACATCATGGCCGTGTCCAGAAGTGCGGGGGAGGTGCGGACATGCTCAGCGG
          GGTGTTTCCACATCGTGGCCAGGACCAGAACTTCGAGGAAAATGTGGACACACGCAACGG
          GGAGTACCGACATCGTGGCCAGGGGCAGAAGTACAAGGAAAATGTGGCCATACTCATCGG
          GGAGTGGCGACATCATGTGCAGGAGCAGATGTCCAAGGCAAATGTGGCCACACCCAGCGG
          GGTGTGTCAACGTCGTGGGCCGTAGCAGAGGTTCAGGGGAAATGTGACCACACGCAGCGG
          GGAGTGCCGACGTCGTGTCCAGGAGCGGAAGTTCAAGGAAAAGGTGGCCACACACAGCGG
          GGAGTACCGACCCCGTGTCCCGGAGCAGAAGTTCAAGGGAACTGTGGACAGACTCATCCG
          GGGGTGCCGACATTGTGGCCAGGCGCAGACGTCCACGGAAAATGTGGCCACACGCATCGG
          GGAGTGCTGACATCTTGCCCAGGAGCAGACGTTCAAGGAAAGTGTGGCCACACTCATTGC
          TGTGTCCCGACGACGTGTCCAGGATCAGACGTTCAAGGCAAGTGGGGACAAACACAGCGG
          GGTGTTCCGACAACTAGGCCAGGTGCAGAAGTTCAAGGGATGTGGGGCCACACTAAGCGG
          TGTGTGCCGACATTGTGTCCAGGACCAGAAGTTCAAGGAAAATGGGTACATACTCATCGA
          GGTATGCCGACTTCATGCCCTGGAACAGAAGTTCATGGAAAATGCGGCCACACTCATCGG
          GGTTTCCCGACCTCATGCCCAGGGCCCGAAGTTCATGGAAATTGCGGACACACTCATCGG
          GGTGTACCAACTTCGTGGCCAGGGCCAGAAGTTCATGGAAAACGTGGCCATACTCATTGG
          GGTGTGCCGACTTCGAGGCCAGGACCAGATGTTCAGGGAAAGTATGGCCACACTTATTGG
          GGAGTTCCTAGATCAAGTCCGGGTCCTGAGCTTCAAGGTAAAAGTTGTAAACCGCAGCGT
          AGGGTGTCAAGTTCACGACCAGGTCCCGAATTGCAAGGTAACAGTTGGAAACCTCAGCGT
          GGCGTGCCCAGGTCAAGACCAGGTCCTGATTTTCAAGGTAACAGCTGGAATACTCAACGT
          GGGGTTCCAAGATCAGGACCAGGTCCTGATTTCCAAGGTAACAGTTGGAAAACTAAGCGT
          GGGGTGCCTAGATCAAGACCGGGGCCTGAGTTTCAAGGTAACAGGTGCAAGACTCAGCGT
          GGGGTGACTAGGTCAAGACCATTTCCCGAATTTCACGGTAATAGCTGGAAAACTCATCGT
          GGGGTGACAAAGTCAAGACCAGGTCCTGAATTTCACGGGAATAGGTGGAAAACTAAACGT
          GGAATGCCTAGCTCCAGTCCGGGACCGGAATTTCAATGTAAAAGCTGGAAAACTCAACGG
          GGAGTGCCTAGATCCTGTCCCGGGGCGGAGTTATATGGGGAATGTTGCCCAACGCAGCTT
          GGAGTTCCGAGATCTTGTCCTGGTCCGGAATTTCATGGAACATGGTGCCCGACTCATCTC
          GGAGTGCCGAGATCTTGTCCTGGTCCAGAATTTCAGGGAAAATGTTGTCCGACGCATCTC
          GGAGTGCCGAGATCTTGTCCTGGTCCGGAATTTCAGGGAAAATGTTGTCCAACGCATGTC
          GGGGTACCGAGATCTGGTGCTGGACCGGAATTAAAATGGGATTGGTGCCAAACTCAGCGG
          TGGGTTCCGAGATCTTGTACAGGACCGGAAGTACAAGGAAAATGGTGGCAAACTCATTAT
          GGGGTGACTGGATCTTGTCCAAGCCCGAAATTCCAGCGGAAAGGCTGGCAAACTCAGCGT
          GGGGTGCCTGGCGCTAGCCCAGGTCCGAACTTGCAAGGAATGTGGTGCCAAACTCCACGT
          GGGGTGCCTGGAGCTCGACCTGGGCCGAACTTTCAAGGAAAGTGGTGGCAAACTCCGCGT
          GGGGTGCCTCGAACATGCCCAGGACCGAAATACCATGGAAAGTGGTGGCAAACCCCGCGT
          GGGGTACCTGGATCTAGCCCTGGGCCAAATTTCCAAGGAAAAAGGGGGCAAACTCCCCGT

          ATACGATGCACACCTAAACTCAATGCGGCCCGAGGCGGATAGGATGCTAAGTAAGATATA
          ATCCGTTGGACCCCAAAACTAGATGCTGCACGGGGCAGATATTATGCTGCCTAACAATTA
          ATCCGGTGGACACCGAAACCGGACGCCGCACGAGGCGGGTATGATGCAAATTATCTGATC
          ATTAGATGGACACCGAAACTCGATACGGCACGTGGCGGGTATGATGCCAATTATCTATTA
          ATACGATGGACACCGCAACTGGAAACGGCACGGGGCGGTTATGATGCCATGTATCTTTTA
          ATTCGTTGCGCGCCAAAATTATATGCCGCGCGTGGGGGCTAGGATGCTAAGTATCAATCT
          GTCCGCTGGCCGCCTAATATGTACGCGGTACGCGGCGGTCACGACGCCAAACAAAACCTA
          ATCGGTTGGCCGACGAAACTATATGCATCTCGGCGTGGGCAAGAACCGAATTAACAATTC
          CTACGTTGTTCGCATAAACTATACGCTGCCCGTGGGGGAGAGCAGGCGCAATATAAATTG
          ATTCGTTGTTCTCCTAAACTATACGCTGCCCGGGGGGGCTACCAAACCAAATATAAGTTA
          CTTGGTTGGTCACCTAATCTATATGCGGCTCGCGGGGGAAATCATGCCAAATACAAACTC
          CTTCGTTGTTCACCTAAACTATATGCGGCGCGGGGCGGATAGGATGCTAAGTATAAATTG
          ATTCGTTGTTCTCCTGACCTCCATGCGGCTCGGGGGAGGTACGATGCTAAGTATAAATTG
          ATCCGTTGTATTCCAAAACTTTATGCGGCCCGGGGCGGAAAGCATGCTAAGTAAAACTTA
          ACCCGTTGTATGCCTAAACTTTATGCGGCACGGGGCGGACCGGATGCTAAGTACAAATTA
          TTGCGGTGGACGCCAAAGATTTGTGCAGCAAGGCGAGGATACGAAGCTAAATAACAATTA
          ATACGCTGCACGCCTAATATGCGCGCACCACAACGCGGGTACGATGCTGACTAACAGTTC
          ATACGTTGTACAACTAACATATGCGCCTCACAGCGCGGGTACGAAGCGAACGAACAATTA
          ATACGATGCACTCCTAACATATGGGCGTCACATCGCGGATACGATGCAGATTACCAATTA
          CTACGTTGCACTCCTAATATATGGGCGGCCCATCGCGGATACGATGCCGACTACCAATTT
          GTACGCTGCACTCCTAACATATGTGCCGCCCCACTCGGGTACGAAACTGAGTATCACTTA
          ATCCGCTGTACTGCTAACATTTGTGCAGCACAGCGCGGATACGAGACGGACTACCAGTTA
          ATGAGCTGCTCTCCTAAATTAGGGGCGGCCCATCGCGGCTACGATGCTGATTCTCAATTA
          ATAAGCTGCACCCCCAATATATGTGCGGCACATCGCGGCTACGATGCCGATTCACAATTA
          ATAACGTGCACTCCTAAACTATGTGCGGCATACAGCGGTTTCGATGCTGAGTCCCACTTA
          ATAGGCTGCACTCCTAAAATATGTGCGTCATATAGCGGCTACGAGGCTGAGTCTCAATTA
          ATAGGCCGAACTTCCCCAATATGCGCGGCACATCGCGGCTCCGATGCTGATTCTCAATTA
          ATAGTCTGCACTCCTAAAATCTGTGCGGCCCAGCGCGGCGATGATGCCGACTCTCATTTA
          ATAGGCGGCACCCCTAAAATATGTGCCGCACATCGCGGATACGATGCAGAGTCGCAATTA
          ATCGGTTCCACTCCTAAAATGTGTGCAGACCACAGCGGATACGATGCAGATTCCCAGTTA
          ATAGGTTGCGCTCCTAAAATCTGGGCAAAACAACGCGGATACAAAACGGATTCACAATTA
          ATACGATGTCCTCCTAAAATCTGTTCAGCACAACGCGGGTACGATGCAGAGTCACAATTA
          ATACGATGCACTCCTAACATATGTGCGGCTCATCGAGGATACGAAGCAGAGTCACAGTTC
          ATACGGTGCACTCCGAAGGTATGTGCGGAACACCGCGGATACGATGCAGATGCGCAATTG
          ATACGGTGCACTCCAAAAATTCGGGCAGCAGATCGCGGATACGACGCAGACTCAGGATTA
          ATACGGTGCACTCCAAAAATATGGGCGGCGGATCGCGGATACGACGCTGAGTCACGATTA
          ATCCGACGCACCCCTAAACTATGTGCGGCCCGGAGCGGGTACGATGCTAAATATCAGCTC
          ATACGTTGCACGCCTCAATTTTGTGCGGCCCGCGGCGGCTACGATGCCAAGTATCAACTC
          ATACGATTCACCCCTAAACTATGCGCGGCCCGGGGCGGCTACGATGCCAAGTATCAACTC
          ATACGATGCACCCCTAAACTATGTGCGGCCCGGGGCGGCTACGATGCTAAGTATCATCTC
          ATACGCTGCACCCCGAAACTATGTGCGGCCCGGGGCGGCTACGATGCTAACTATCAACTC
          GTTCGATGTACGCCTAAACTGTGTTCGGCCCGGAGCGGCAACGATGCCAACTATCAGTTC
          ATTAGATGCACACCTAAACTGTGTGCGGCCCGGAGCGGCAACGATGCGAAGTATCAGCTC
          CTCCGCTGTACACCTAATCTTTGTGCGGATCGTGGCGGATACGATGCAAAGTAACAGCTC
          ATGCGTTGTACCCCTAAACTATATGTGGCACGGGGTGGCTAGGAGGCCGAGTAACACTTC
          ATTCGTTGTACGCCTAACCTATATGCGGCAAGGAGCGGATAGGACGCTGAGTAACAACCC
          ATTCGTTGTACGCCTAACCTATATGCGGCACGGAGCGGATAGGACGCTGAGTAACAACCC
          ATTCGTTGTACGCCTAACCTATATGCGGCACGGAGCGGATAGGACGCTGAGTAACAACCC
          ATTCGTTGCACGCCCAAACTCAACGCTGCGGGGGGAGGGTAGGAGGCACATTAAAAATTC
          ATTCGTTGTACGCCTAATCTATATGCGGCACGTGGTGGAGAGGAAGCCAAATAACAATTT
          ATACGCTGCACGCCGAACCTCTATGCTGCCCGAGGGGGACAGGACGCAAATTAAGAATTA
          ATACGATGCACACCTAAACTCTATGCGACCCGAGGAGGGTAGGAGGCTAAGTACGACATA
          ATACGATGCACACCTAAGCTCTATGCGGCACGAGGCGGATAGGAGGCTAAGTACGAAATA
          ATCCGATGCACACCTAAACTCTATGCGGCTCGAGGCGGACAGGATGCTAAGTAAGAACTT
          ATCCGCTGCACACCGAAACTCTACGCGCCCCGCGGCGGAAAGGATGCTAAGTAAGATATT

          CAGATGACTCAGCATTGATACAAGCGTCTTCTTTGGTTCTCAACCCCCTCGAGCTTCCAC
          CAGTATTCTCTGACTTGTTATGAACGGCTCCTTAGTTTCATATCGCCGTCCAGATCGGAA
          CCAAACACCCACACATGCGATGAGCGTCTTCTAAGTTTCTTAACCCCGTCCAGCTCCGAA
          ACGAAGACCAAGACATGCTATAAGCGTCTCATAAGGTTATTAACGCCGTCCAGCTCTGGA
          CCGAATACACAACCATGCTATCAACGTCTCCTAAGAGTCTTTACGTCGTCCAGGTCCCAC
          GACCACACTAAGACATGCAATGACCGCCTGCTTAGTTTCATATCGCCCCCGAGCTCGGAT
          CAGAAATCTCGGCCGTGTTCTCAACGGCTACTTATATTCTTCTCCTCGTCGAGTTCTCAT
          CAGAAGACTCAGACGTGCTACGATGGGCTCCTTATATTTTTCTCCCCGTCGAGCTCCCAT
          CAGAAAACTCAGACATGGCAGGATCGTCTACTCAGCTTCTTTTCTTCATCAAGTTCCCAA
          CAGAACACTCAGACATGCCACGAGCGTCTACTCAGGTTTTTATCTCCCTCGAGTTCCCAT
          CAAAAGACTCACACCAGATACGACCGTCTCCTGTGGCTCTTTTCTCTGTCGAGTTCCCAG
          CATAACACTCAGACATGATACTATCGTCTTCTCAGGTTGTTATCCCCTTCGAGTTCCCAG
          CAGAAAACCCACACATGGTACGACCGCGTACTAAGGTTATTGTCGCCTACGAGTTCTCAC
          CAGAAAACTCAGACATGATACGACCGACTGATTAGAATGTTATCGCCGTCGAGTTCCAAC
          CAGACAACGCTGACCTGAAACGAGCGTCTACTTAGATTCTTATCGTCGTCGAGATGTCAC
          CACAAAACCCAGACCCGCTATGACCGTCTCCTATGGTTTGTAATGCCATCCAGTTCGCAA
          CATCGGACGCATGCCTGATATGATCGACTTCTATGGGCGGTCTTGCCATCGAGTTCCCAG
          CAGAACACACAGCCGTGATATGATCGGCTACTATGGGTCGTAAACCCGTCTCGGTCTCAG
          CATAATATCCAAACATGTTATGATTGTCTACTGTGTATCGTCATACCGTCCAGCTCTCAG
          CAAAAAACCCAGACCTGATATCATCGTCTGCTATGTATCGTGCGCCCGTCGAGTTCGCAG
          AATAAAACCCACACCTGAGATTACCGTCTCCTCTGCTTAATAATCCCACCGAGTCCGCAT
          CACAAAACCCAGACCTGCTATTACCGTCTTCTGTGGGTAATCATCCCTTCGAGAGCTCAC
          CAGAAAACCCAACCTTGATATGACCGGCTTCTACGGGTCGTCATCCCGTCTAGTTCCGAG
          CAGAACACCCAGCGCTGTTATGACCGCCTTCTACGGGTCGTTATGCCGTGCAGTTCTCAG
          CAGAAAACCCAGCCCTGATATGATCGACTGCTGCGGGTTGTCATTCCGTCTAGTTCCCAG
          CACAAAACCCAGCCCTGGTATGATCGACTTCTACGGGTCGTCATCCCGTCCAGTTCTCAA
          CAGAAGACTCAACTGTGTTATGACCGACTTCTTTGGGTTGTTATGCCGTCCAGTTCTCAT
          CAGAACACTCAACCTTGATATGACCGACTTCTCTGGGTCGTCTTCCCGTCTAGATCTCAT
          AACAATACCAATCCCTGATATGCCCGACTTCTACGGGTAGTCACACCATCCAGTTCCCAG
          CAGAATACTCAGACATGATATGACCGACTTGTTTGGGTTGTCATCCCGTCCAGTTCTCAT
          CAGGAAACGCAGCCCTGTTATGACCGACTTCTCTGGGTGGTCACTGCGTCCAGTTCTCAG
          CAGAACACACACGCCTTATATGACGGACAACTCTGGGTTGTCATCCCTTCTAGCTCCCAG
          AAAAACACACAGCCATGATATGACCGTCTTCTGTGGGTAGTCATCCCTACCAGCTCTCAC
          CAAGACACACAGCCCTGTTATGACCGACTAATCTGGGTTTTCCTTCCTACCGGCTCTCAG
          CAAAAGACCGAGCCCTGCTACGACCGGTTTATTGGGGTTGTCATGCCTTCTAGGTCACAG
          CAAAACACCGAGCCCTGATACGAGCGTCTTCTTTGTGTCGTCATCCCGTCTAGGTCACAG
          CATAATACGCATGCCTGATATGAACGACTACTTGGCTTCGTCACCGCGTCGAGGTCTCAC
          CACACGACGCATACCTGATATGAACGCCTATCTGGCTTAGTTACTCCGTCCAGGTCTCAC
          CACAAGACGCATACATGATATGAACGACTTTCCGGCTTAGTTACTCCGTCGAGGTCTCAC
          CACAAAACGCATACATGATATGAACGACTATCTGGCTTAGTTACTCCATCGAGATCACAC
          CACAAAACGCATACTTGATATGACCGTCTGTCGGGGTTAGTTACTCCGTCGAGATCTCAC
          CACAAGACGCATTCGTGATATGAACGACTATTTGGCATAGTAACTCCGTCAAGCTCTCAC
          CACAAGACCCATGCGTGATATGAACGACTCTTTGGCTTAGTTGCTCCGTCAAGGTCTCAC
          CATAACGCTCAAATCTGGTATGAACGACTACTTGCCTTACTAACCCCGTCAAGGTCACAG
          CAAAACACCAATACTTGTTATGACCGTCTACTTAGTTTTTTAACGCCTTCCAGTCCGCAA
          CAAAAGTCTCAAACCTGATATGACCGTCTACTTAGTTTCTTGACCCCGTCCAGTTCTCAG
          CAAAAGTCTCAAACCTGATATGACCGTCTACGTAGTTTCTTGACCCCCTCCAGTTCTCAG
          CAAAAGTCTCAAACCTGATATGACCGTCTACGAAGCTTCTTGACCCCCTCCAGTTCTCAG
          CAGAAGACCGAGACGTGTTATTACCGACTCCTTTGGTTCTTAACCCCATCACGTTTCCAA
          CAGCAAACGCATACGCGAAAATAACGCCTACTTGGGTTCTCAACGCCGTCGAGTTTGCAG
          CAAATCACTCAGACTTGATACTAACGACTTCTTTGCTTCTCAACCCCGTCAAGCTTTCAA
          CAGATGACTCAAACTTGGTATTAACGTCTTCTGTGCGTCTCTACCCCGTCGAGTTTCCAG
          CAAATGACTCAAACTTGATATTAACGTCTTCTGTGCGACTCAACCCCGTCGAGCTTGCTG
          CAGATCACTCAAGCTTGATATTATCGTCTTCTTTGGGTCTCGACGCCTTCGAGCTTCCAG
          CACCTGACTCATACTTGATATTAACGCCGCTTTTGCTTCTCGACCCCGTCGCGCTTCCAG

          GACCTTATGCCAGGCCTGCAAGTTATGATTGGGTTGCTCCATTGTCCACGCCTGCTTCTG
          GAACTTATTTCCGGCCTCCAAGTATTGATAAGGATTCTGCATTGGCCACGTATCCGCCTC
          GAAATAATACCTTGCTTGCAAGTAATGATAAGCATACGGGAATGTCCCAGGATTCGTCCC
          GATATTATACCATGCCTTCAGGTAATGATAAGCAATCGGGAATGCTCCAGAATGCGTCTG
          GATATCATACCATGCCTGCAAATTATAATGAGCATACGGGAATGTCCCAGAATGCGTCTC
          GAGATAATCTCAGGCCTCCACGTGGTCATAGGTATCCTATACTGTCGGCGAATGCGACTG
          GATCTGATCGCCGGCCTCAACGTATTATTAGGTATATTACATTGGCCCCGTATACGTCCC
          GATCTGCTTCCTCGTCTTCATGTTATCCTAGGAATTTTACATTGGACGCGCACACGGCTG
          TATCTCATCCCAAGCCTCCAAGTAATAATACAGTTTCTGCAGTGTCCTCGTATCCGTCTA
          TATCTGATACTAGGGTTCCAAGTAATCATGGGGATTCTGTATCGTCCAACTATTCGTCTA
          TATCTTATGCCCGGGCTGCAGGTTGTCATGGGCATCCTGAATTGGCCCCGGATACGTCTC
          GATCTTATCCCAGGCCTCCACGTAATCATAGGGATTCTGCATTGTCCTCATATACGTTTC
          GTTCTGATGCCAGGCCTCCAAGTTGTAATTGGTAGTCTGGATTGGCCCCGGATTCGTTTG
          GAAGATATGCCAGGCCGTCAAGTTCTGATGGGAATACTTCAGTGTCCTCGGATACGTCTC
          GACCTTATGCCAGGGCTCCTTGTAATGGTCGGAATTCTGCATTGTACGCGAATGCGTCTA
          GAGCTTCTTCCCGGCCTTCATGTAATTATATGTATTCTACATTGCCCACGTATCCGACTT
          GACCTTATCTCGCGCCTGCAGGAAATGATAGTCATTCTGAATTGCCCACGTTTGCGACTG
          GATCTCATGTCTGGGCTACATATGATGATTGTCATTTTCCAGTGTCCACGTTTCCGTCTC
          GAGCTCATTTCAGGCCTCCATATCATGATTGTCATTCTGCATTGTGCACGTTTACGTCTC
          GAGCTAATTTCTGGCCTGCATATCATGATAGTCGTTCTTAATTGTACACGTCTACGTCTG
          GATCTCATATCCGGCCTTCATGTAATAATATTCGTTCTGCGATGTTCCCGGGTACGTCTC
          CAGCTGATTTCAGGCCTGCAGGTAATGAAATTCATTCTGCGTTGGCCACGTTTACGACTG
          GAGCTGATTGCAGTCCTGCAGGTGATGATAGTCATTCTCCAGTGTCCGCGCTTCCGTCTG
          GAGCTGATTGCAGGCCTGCAGGTCATTATAGTCATTCTGCAGTGTCCGCGGTTCCGTCTT
          GAGCTAATTGCAGGCCTTCATGTGATCATGGTATTTATGCATTGTACGCGCTTACGTCGC
          GAGCTAATTCCTGGCTTGCAGGTGTTGTTGGTCATTCCGCAGTGTCCGCGCTTGCGTCCC
          GAGCTGATTGCTGGCCTCCAGGTAATAATAGTGATACTGCAGAGTCCGTGCATGCGTCTT
          GAGCTCAATGATGGCCTCCACCTGATAATGGTAATGCTGCACGGGCCTCTCTTTCGTCTG
          GAGATGATTGCAGGGCTGCAGGTCCTGATAGTAATTCTGCAGTGCCCTCGCGTGCGCCTC
          GAGCTATTGGCAGGCCTAGAGGTGATGATTGTGATTCTTCAGTGTCCGCGGTTACGTCTA
          GAGCTCATAGCAGGCCTGCAGGTCATCATAGTCTTACTGGAGTGTCCGGGGTTGAGTCTT
          GAGCTAATGGCAGGCCTGCAGCTAATGATAGTCATTCTGCAGTGTCCGCGTTTGCGTCTC
          GAGCTAATAGCAGGCCTGCAGGTAATGATAGTCATTCTGCAGTGTCCACGGTTTGGTCTA
          CAGCTAATAGCAGGCCTGCATGTAATTATAGTCATTCTGCAGTGTTCGCGATTGCGTCTA
          GAGCTAAGGGCGGGCCTGCAGGTGGTGATGGTCTTGCTCCACTGTCCGCGTTTGCGTTTG
          GAGCTAATAGTAGGCCTTCAGGTAGTTTTGGTCTTCCTACATTGTTCGCGATTGCGCCTA
          GACCTGATACCAGGCCTACAAGTGATGGTAGGTATGCTGCATTGTCCGCGTATCCGTCTC
          TACTTCATGCCCGGTCTACAGGTCATAATAGGCATGCTGCATTGCCCTCGGATCCGGCTC
          TACTTTATGCCCGGCCTACAAGTCATGATAGGCATGCTGCATTGTCCTCGGATCCGTCTG
          TACTTTATGCCCCGCCTAGAAGTTATGATAGGCATGGTTCATTGTCCTAGAATCCGTCTG
          TACTTCATGCCCGGCCTAGAAGTCATGGTTGGCATACTTCATTGCCCTCGGATCCGTCTC
          TACTTGATGCCAGGTCTCCAAATCATAATGGGCATTCTCCATGGTCCTCGGTTCCGTCTC
          TACTTGATGCCAGGCGTACAAGTCATCATAGACATACTCAATTGTCCGCGGATCCGGCTC
          GACCTGATGCCTGGACTGCAAGTCATCGTAGGGATACTACATTGTCCACGCATCCGTCTT
          GATCTTATGCCTTGCCTTCAGATAGTGCTAGGTATGCTCCATTGGCCTCGTATACGTCTA
          GATCTTATGGCCGGCCTGCAGGTAGTGATAGGAATCCTCCATTGCCCTCGAATGCGTCTC
          GATCTCATCCCTGGCCTGCAGGTAGTCATAGGAATCCTCCATTGCCCTCGAATACGTCTC
          GATCTCATCCCTGGCCTGCACGTAGTCATAGGAATCCTCCATTGCCCTCGAATACGTCTC
          GACCTTATCTCAGGAATCCAATTAGTAATAGGAATGTTTAATTGTCCTAGTATGCGTCTC
          GACCTAATGCGAGGCCTACAAGTAATCATAGGAATTCTCCCGTTACCTCTTATGCGTCTA
          GACCTAATGCCAGGACTCCAAGTAATAATGGGGATTCTTCAGTGTCCTCGACTGCTTCTC
          GACCTTATGACAGGCCTCCACGTAATGATTGGTATACTCCCATGCCCTCGCCTGCTTCTT
          GACCTTATGTCAGGCCTCCACGTAATAATTGGGATCCTCACATGTCCTCGCCTGCTTCTA
          GAGCTTATACCAGGGCTCCAAGTTATGATTGGGATGCTCCATCGGCCGCGTCTGCTTCTC
          GATCTAATGCCAGGCCTCGAAGTTCCGATTGGAATGCTCCAATGGTCGCGCCTACTTCTA

          GTTTTTCCCAATTCATGCCGCCCCTCACGACTCTCCATAGAGCCACAGCCCTGCGCTTTG
          GTTATGCCAAAGTCGCGTCGTCCCTCGCGTCTCGCACGCGCGCACCAGCCATGGGTATTG
          GTTATAACCCAATCGTGTCGTCCCCCCCGTCACGCGCGAGCTCATCAGCCACGGGTTTTT
          GTTATGGCCCAGTCACGCCGTCCACCCCGGCTAGCACGTGCGCAGCACCCCTGTGTTTTT
          GTTATGACCCACGCCCGTCGGCCTTCCCGTCTAGCACGAGCGCATCAACCATGTGTTTTT
          TTGATGCCGAAGACGCGTCGGGCCTCGAGTCTGTCGCGAGCACCCCAGCCATGTCCAGTT
          GTGATGCCTAATTCGCGACGGCCTTCTCGATTTTCACGGGAACCCCAGCCTCGCGCTTTG
          GTGATGTCTAATGTGCGCCGGCCATCCGGGCTCTCGCGGGCGACCCAGCCCTGCTCATTA
          GTTTTGGCAAAGTCTCGACGGCGATGGCGACTGTCGCGAGCCCTTCTGCCACGACCATTT
          GTTTCGCCTAAGTCGCGACGGCCATCGCGCCGGTCGCGTGATCTTCAGCCACGACCGTTC
          CTTTTCCCGGACTCTCGACGTCCTTCGCGTGTTTCTCGAGCACTCCCCCCACGATCCTTC
          GTATTCCCAAAGTCTCGACGGGGATCGCGACTCTCTCGAACACTTCAGCCGTGGGCCTTT
          GTTTTGCCAGAGTTGCGCAGGCCGTCGCGAGTCTCGGGGGCACTAAAGCCTCGTGCATTC
          CTTTTTCCTGAGTCTCGACGGCCATCGCGACTATCCCGAGCCCCTCAGCCATGTGCTTCT
          GTTTTGCCAGATGCTCGGCGACCGTCACGACTCTCGGCGGCGCCTCAGACATGTCCTTTT
          GTATTTCCTAAGTATCGTCATCAATCACGACTATCCCGCGCCCCTCAGCCTCGCGCTGTG
          CTTTCACCTAACGCCTACCGGCAATCACGATTGTCTCGGGCCCCGCAATCGTGCGCTGTC
          GTGTCACCTAAGTCCTACCGTCATTCACGACTTTCCCGCGCTCCTCAGCCATGGCCCGTC
          GTTTCACCTCAGTCCTACCGTCATTCTCGTCTCTCTCGGGCCTCTCAGCCGTGCGCCGTT
          GTTTCACCTAATTCATACCGTCATTCACGTCTATCCCGGGCACCTCAGCCGTGCGCTGTC
          GTAATGCCAAATTCCTACCGACAATCCCGTCTGTCCCGCGCGCCTCAGCCGTGCTCCGAC
          GTTTTGCCTAAATCCTACCGTCAATCTAGACTGTCCCGGGCCACTCACCCGTGCGCTGTC
          GTCATGCCGAACTCGTACCGACAATCACGTGCGTCCCGGGTCCCGCAGCCGTGCGCTCTT
          GTGATTCCTAAGTCGTACCGTCAATCACGTCTGTCACGGGCACCTCAGCCCTGGGCTATT
          GTGTTGCCGAAGTCCTACAGTCATTCACGTCTGTCACGAGCCCCTCATCCGCGCGCTGTT
          GTGTTGTCCAAGTCATACCGTGAATCGCGTCTTTCGAGGGCCCCACAGCCGTGCGCAGTT
          ATGTTGCCTAAGTCCTACCGCCAATCCCTTTTGTCCCGGGCACCTCATCCATGCCCTGTC
          GTGTTTCCGAAGTCCTACCGTCAATCGCGATTGCGCCGGGCCCCTCAGCGGTGCGCTGTA
          GTTTTGCCTAAGTCCGAGCGTCACTCACGACTGTCACGGGCCCCACACACATGGTCTGTC
          GTGTTGCCGAAGTCCTTCAGTCAAACACGTCTGTCTCGTGCCCCTGAGCCGTGGGCGGGT
          GTTTTGCCTAATTCTTATCGTCAAACAGGTCTCTCACGGGCCTCTGAGCCGTCCGCGGTC
          GTGTTGCCTAAGTTCTACCGTCACTCGCGACTGTCGCGGGCCGCACATCCGTGCGCTGTC
          GTGTTCCCTAATTCCTACCGTCAGACACGTCTGACCCGTGCCGCTAAACCGTGCGCTATA
          GTGTTCCCTAAATCCTACCGTCAGACGCGTCTCACCCGAGCCGCTAATCCATGCGCTCTG
          GTGATGCCTAACTCGGACCGCCACACATGTTTGACCGGGGCAGCGCAACCGCGCGCTGTC
          GTGATGCCCAAGTCTGACCGCCACGCACGTCTGACCTGGGCCGCTCATCCAGGCGATGTC
          GTTTTGTCAAAGGCTCGGCATAAATCACGACTGTCACGGGCGGCTCATCCCTGTGCTTTG
          GTTTTTCCAAAGTCTCGTCGTCAGTCACGACTTACACGCGCCCCTCAGCCATGTGCTTTG
          CTATTTCCAAAGTCACGCCGTCAATCACGACTAACTCGCGCGCCTCATCCTTGTGCATTG
          GTTATTCCAAAGTCTCGACGTGACTCTCGACTCACACGGGCGCCTCATCCATGTGCAATC
          GTGATTCCAAACTCTAGTCGTCCATCACGACTGACGCGCGCGCCTCATCCATGTACTTTG
          GTTTTTCCAAAGTCCCGCCGGCATTCACGGCTAACACGGGCGCCACAGTCATGTGCTTTT
          GTGTTTCTCAAGTCTCGCCGTCAATCACGCCTCACACGGGCGCCTCAGCCATGTGCTTTT
          GTTTTGCCGAAGTCCGGCCGTCACTCCCGACTATCACGAGCGCCTCACCCATGGGCTTTG
          GTTTTGCCTAAGTCCCGCCGATCTTCACGACTGCCCCGGGCCCCTCAGCCATGTGCGTTA
          GTCTTGCCTAAGTCTCGCCGGCCTTCACGACTTTCCCGGGCCCCCCAGCCAAGGGCTTTG
          GTTTTGCCTAAGTCTCGCCGGCCTTCTCGACTTTCCCGGGCCCCCCAGCCAAGGGCTTTG
          GTCTTGCCTAAGTCTCGCCGGCCTTCTCGACTTTCCCGGGCCCCCCAGCCAAGGGCGTTG
          GTTTTACCTGATTCACGGAGTTCGTCAAGACTCTCCCTGGTGCCTCAGCCTTGTGAAATT
          GTTTTCCCTAAGTCTCGGCGTCCGGCACGACTGTCCTTAGCCCCTCATCCTTACGCTTTG
          GTTTTGTCTAAATCTCGCCGCCCATCACGACTCTCACTAGCGGCTCACCCTGGCGCCTTT
          GTGTTGCCAAAAACTCGACGCCCATCGCGCCTATCCCAAGCGCCCCAGCCATGCGCTTTG
          GTTTTTCCTGAATCTCGACGGCCCTCGCGCATATCCCTAGCCCCCCAGCCTTGCGCATTC
          CTATTTCCTAAATCTGGCCGCCCATCGCGACTCAGCCTGGCCCCCCAACCTTGTGCTCTG
          GTTTTGCCTCATTCGCGCCGCCCATCACGACTCTCCCTAGCTCCCCACCCTTGCGCGTTG

          TTGGCCGCGTGCCGTAAACTTTCGTCGAGGCTTGACAGACGTGCCCGGTTCGGAGCCCAT
          TTGTCTGCTAGCCGGAATCCCTCGTTGAGGCTGGACGGACGAGCACACTTCAGTACACAT
          TTATCCGCTGGTCGTTATGTATCAGTGAGGCTAGATAGACGAGCCCGGTTAGCAACACAT
          CTCTCCGCTGGTCGCTATGTATCTTTCAGGCTAGATAGACGGGCACGCTTAGCGACACAT
          TTCTCAGCTGGTCGTTATGTTTCATTAAGGCTTGACAGACGTGCACGGTTGGCAACCCAT
          TTCGCAGCTTGTCGCAACCTATGGTTAATCCTAGACGGACGAGCACGGTTCGGTACTCAC
          TTTTCAGCCCGCCGGAATCTATCAGTCCGTATTGACGGGCGAGCCTGTTGCAGGACACAC
          TTTTCTGCCTGTCGGGAAATACCTCTACGCATAGACGGACGAACCCGCTTCGGTACATAT
          TGGTCGGCGTGCCGGATGCTTTCGTTGAGTCTGGAGGGTCTTGCAAGCTTCGGAACCCTT
          TGGGCCGCATGTAGGATTCTCTCGTTGTGTTTGGAAGGTCGTACCAGCTTTTGTACCCTA
          TTGGCTGCCTGCCGGAATCTATCGTTCAGGCTCGACGGTGGAGAAAGTTTCTGTACCCAA
          GTATCCGCATGCCGAAATCTATCGTTGAGACTTGACGGTCGTGCTAGACACGGTACCCAA
          TTGTCCGCATGCCGCAAAATTCTGTTCAGGCTTGACGGTCGCGCTCGTTTAGGGACACAG
          TTGTGCGCTTGGCGGAAACTGTCGTTCAGGCTGGACGAACGGGCCTGGTTGCGAACACAT
          TTCTCGGCATGCCGGAATCTATCATTCAGGCTAGACGGACGCGCCGGTTTGGGGACCCAT
          TTCTCCGCATGGCGGTCTCTATCCTTGAGGGCAGACAGACGCGCCGGGTTAGGAACGCAG
          TTCTCAGCGTGGCGAAATCTCTCCTTAAGCCCCGAAAGCCGTGCTGGATTGGGAACGCAG
          TTATCCGCGTGGCGGAACCTATCATTGAGGCATTACAGACGAGCTCGGTTGGGGACTCAT
          TTTTCTGCGTGGCGTAAAATGTCATTGAGACCTGAAAGACGTGCGGGGTTGGGTACGCAT
          TTTTCTGCGGGGCGTAACCTATCATTTAGGTCTGAGCGGCGTGCCGGGTTTGGAACTCCC
          TTATCCGCGTGTCGGGATCTATCAGTCAGACCTGATAGACGTTCCTGGTTGGGTACACAT
          TTCTCTGCGTGCCGTAATCTATCTTTTAGACCTCACAGTCGTGCCTGGTTGGGCATTCAT
          TACTCCGCATGTCGGAATCTTTCATTAAGACCTGACAGCCGTGCCGGATTGGGCACGCAG
          TACTCAGCATGGCGGAATATTTCTTTAAGCCCTGACAGCCGTGCCGGGTTAGGCACGCAT
          TACTCCGCGTGGCGGAATATTTCGTTGAGACCTGACAGCCGTGCAGGGTTAGGAACGCAG
          TACTCCGCGAGGCGTAAAATTTCATTTAGGCCTGACAGCCGAGCAGGGTTGCGCACGCAG
          TTCTCCGCGTTGCGTAATATTTCATTGAGGCCTGACAGCCGTGCAGGGTTGGGAACGCAG
          TTTTCCGCTTGTCGTAATATTTCATTGAGGCCTGTCAGGCGTTCAGGTTTAGGAACACAG
          TTCTCCGCGTGGCGGAATATTTCATTGAGGCCTGACAGCCGTGCCGGGTTTGGAACGCTT
          TTCTCCTCGTGGCGGAATACTTCATTGAGGCCTGACAGTCGTTCCCGATTGGGAACGGAA
          TTCTGCGCGTGGCGCAACATATCATTGAGGCCGGATATACGAGCCGGGTTGGGAACACAG
          TTATCAGCATGTCTGAATCTATCATTGAGGCCGGAGAGCCGTGCCGGCTTAGGAACGCAG
          TTCTCCGCTTGGCGGAATCTATCATTGAGGCCCGATAGCCGTGCCGGCTTGGGTACGCAG
          TTATCCGCGTGTGGGAATCTATCGTTGAGGCCGGATAGCCGTGCCGGCTTGGGAACGCAG
          GTCTCCGTTTGCCGGCATCTCTCATTGAGGCCCGATTGGCGTGCCGGCTTAGGAACGCAA
          TTCTCCGCTTGGCGCCAGCTCTCTTTAAGGGCTGATCGACGAGCCGGCTTAGGAACTCAC
          CTCTCTTGCTCTCGCAATCTGACGTTGAGTCTTGACAGAAGTGCCGGGTTAGGTACACAT
          TTCTCCGGTTGTCGCAATCTAACGTTGAGTCTCAACAGAAGTACGGGGTTAGGAGCCCAT
          TTGTCCGGTTGCCGCAACCTAACGTTAAGGCTTGACAGAAGTGCCGGGTTAGGTACGCAT
          TTCTCCGGTTGCCGAAACCTAACGTTGAGGCTTGACAGAAGTGCCGGGTTAGGAACGCAT
          AAGTCCGGTTGCCGCAACCTAACGTTAAGTCTTGACAGAAGTGCTGGGTTAGGAACGCAT
          TTCTCTGGTTGCAGCAATCTAACGTTAAGCCTTGATAGAAGCAAGGGCTTCGGTAGACAT
          TTCTCAGGTTGCCGCAATCTAACGTTAAGGCTGGACAGTTGTGACCGTTTCGGAACACAT
          TTCTCGGGTTGCCGCAATCTTACTTTGAGGCTTGACAGCGGCGCAGGCTTAGGAACGCAG
          TTTTCCGCGTGCCGGAAACTATCTTTGAGGCTGGACAGTCGTACGCGGTTCAGAACGCAT
          TTTTCAGGGTGCCGCACACTATCTTTGAGCCTGGAAAGACGCGCCCGGTTAGGTACTCAT
          TTATCAGGGTGCCGCCCACTATCTTTGAGGCTGGAAAGTCGCGCCCGGTTAGGTACTCAT
          TTATCAGGGTGCCGCCCACTATCTTTGAGGCTGGAAAGTCGCGCCCGGTTAGGTACTCAT
          TTCTCAGCGTGCAGCAATCTCACCTTTAGGGCTGACAGCCGTGCTCGGTTTCGTACCGAG
          TTCTCCGCATGCCGGAGTCTATCAGTGAGACTAGAAAGGCGTGCCCGATTCGGTACGCAT
          TTATCGGCTTGTCGGAAACCATCGTTGAGGCTGGAGAGTCGTGCACGGTTCGGTGCCCAT
          TTCTCCGCTTGCCGAAAGCTTTCGTCTCGCGTAGAAAGCCGTGCCCGGTTCGGGGCCCAT
          TTCTCTGCTTGCCGTAAGCTTTCGTCTCGCGTAGAGAGGCGTGCCCGGTTCGGAGCCCAT
          TTCTCCGCTTGCCGTAAACTCTCTTCTCGCCTAGACAGACGTGCGCGGTTGGGTGCCCAA
          TTCTCAGCTTGCTGTAAACTCTCATCGAGGCTCGATAGCCGTGCTCGGGTCGGTGTCCAT

          GTACCGTAGGCCCGGGCATTCGGGAGATTATGACCGGTCCGACGAAAGCTTACTCCTCCC
          GCACCATAGCGGAGGGCATTAGGCAGAATCTGACCTGTTCGCCGGACTGTTACTCCCCCA
          CCTCCGTTGGGGAGAGCTTTAGGCAGTTTTTGCCCGTTTCGTCGGACGCGAATTGCCCCT
          CCTCCATTAGGTCGCGCGTTACGTAGTTTCTGTCCGTTTCGGGGGACTCGCACATCCCCA
          CCTCCATTAGGTAGCGCTTTAGGCAGGTTCTGTCCGTTTCGCGGGACTCGTATTGCCCCT
          TCACCGTACGCAAGGGCCTTGCGGAGTTTATTGCCGGTTCGAAGGACAAAAGCACCCACC
          GCATCCTATGCCAGCGCCTTGGGAAGATTCTGACCTGTCCGCCGTACTTTGACTCCTCCA
          CCGCCGTACGCGAGAACCTTGGGAAGATTTTGTCCAGTTTGCCGGACATTTACTCCTCCG
          GCTCCCTATGCGAGGGCGTTCGGCAGAATATGGCCTGTCCGCAGCACACTGACACCTCCG
          GCATCTTATGCGAGGGCGTTAGGCAGAATATGTCCCTTTCTGCGAACACTAACACCGCCC
          TCTCCTTACGCGAGGGCATTACGCAGAATGTGGCCTGTTCGTCGAACCCTTCCGCCTCCG
          GCCCCGTAGGCCAGAGCGGTGCGAAGCATCTGGCCTGTTCGGGGTACTCTCACACCTCCC
          GCAACTTACTCGGGCGCTCTGGGCAGGATATGCCCTGTGTGGAATACCTTAACCCCTCCC
          GCGCCAAAGCCGAGGCCATTGGGTAGAATCTGTCCTGTTCGTCGAACACTCACCCCTCCA
          GCTCCCTACGCGATGCCCTTGAGCAGAATCTGGCCGATTCGACGGACACTGACTCCTCCA
          GTACCATAGGCTCGTGCATTTGGCAGGATCTGGCCTGAACGACGGACGCTCACTCCTCCC
          GTCCCCAAAGCTCGAGCATTCGGCGGTCTCTGACCGGTCAGACGGTCGCATACTCCCCCA
          GTAGCGAAGGCACGATCGTTGGGTGGGATGAGTCCCGTCAGACGGACCCTTACACCCCCA
          GTGCCAAATGCTCGTGCGTTGGGCGACATCTGCCCGGTCCGGCGGACTCTTACTCCACCT
          GTGCCGAAGGCTCGTGTGTTGGGCGGCATGTGCCCCGTCCGACGCACGCTTACTCCTCCG
          GTGCCGAAGACTCGCGCATTAGGGGGGATCTGTCCGGTCCGCTGTACGCTTACTCCTCCG
          GCGCCAAAGGCTCGAGCATTGGGCGGAATCTGACCGGTCCGACGGACGATTACTCCTACA
          GTTCCGCAGTCACGTGCATTGGGAGGTATCTGCCCTGTACGCCGGACGCTGCCTCCGCCA
          GTTCCGAAGGCTCGCGCGTTTGGCGGTATCTGCCCCGTGCGGCGGACGCTTACTCCCCCA
          GTGCCTAACGCTCGCGCCTTGGGCGGTATATGGCCTGTACGCCGCACGCTTACGCCTACA
          GTGCCAAACGCTCGCGCTTTGGGCGGTATTTGCCCCGTCCGGCGCACGCTTACACCTCCT
          GTGCCGGAGGCCCGTGTGTTGGGCGGTATCTGCCCTGTCCGCCGTACGCTTACTCCTCCA
          GTGCCTAATGCTCGTGCATTGGGCGGTATCTGGCCTGTCCGCTGTACGCTTACTCCACCC
          GTGCCGAAGGCTCGTGCTTTGGGCGGTATTTGGCCTGTACGCCGGACGCTTACTCCTCCC
          GTCCCGAAGGCTCGGGACTTAGGCGGTATCTGGACTATTCGCCGGTCGCTTACTCCGTCA
          GCGCCGAATGCTCGGGCATTGGGCGGGATCTGTCCTATCCGCCGAACGCTGACACCTGCA
          GTGCCGAAGGCTCGTGCGTTGGGTAGTATCTGCCCTGTCCGCCGGACGTTCTCTCCACCA
          GTTCCGAAGGATCGCGCATTGGGCGGGATCTGTCCTGTCCGCCGGACTCTTTCCCCTACT
          GTCCCAAAGGCTCGGGCATTGGGCGGAATCTGGCCTGTCATCCGGACTCTAACTTCTTCA
          GTGCCGAAGGCTCGTGCTTTCGGCGGGGTCTGGCCTGTCGGCTGGACTCTTACTCCTCCA
          GTGCCGAAGGCTCGTGCATTCGGCGGGATCTGGCCCGCCCGTTGTACTGTAACCCCCCCA
          GTCCCGTAGGCACGGGCCTTGGGCAGTTTTTGTCCCGTTCGTGGGTCTCTTACTCCGCCG
          GTACCATATGCTCAGGCCTTGGGCAGTTTCTGGCCTGTACGACGGACACTTACCGCGCCC
          GTACCTTAGGCACGGGCGTTGGGAAGCTTTTGTCCGGTTCGGCGGACTCTTACTCCGCCA
          GTGCCGTAGGCTCGGGCCTTGGGCAGTTTTTGTCCTGTTCGGCGGACACTTACTCCGCCA
          GTACCGTAGGCTCGGGCCTTGCGCAGCTTTTGTCCAGTTCGGCGGACACTTACTCCGCCA
          GTACCCTAGGCTCGGGCCTTGGGAAGTTTTGGTCCTGTTCGTCGTACGCTTACTCCGCCA
          GTACCCTAGGCTCGGGCCTTTGGCAGTTTCTGTCCTGTTCGACGGACTCTCACTCCGCCG
          GTTCCCTACGCTCGGGCAATAGGTAGCTTTTGTCCCGTTCGACGGACTCTTACACCTCCG
          GTACCATATGCCCGGGCAGTTGGCAGTTTATGGCCTGTTCGGCGGACGCTAACTCCGCCC
          GTACCGTGCGCTCGGGCATTGTGTAGGTTATGACCAGTTCGGGGGACGCTGCCCCCCCCC
          TTACCGTGCGCTCGGGCATTGTGTAGGTTATGACCAGTTCGGGGGACGCTGCCCCCCCCC
          TTACCGTGCGCTCGGGCATTGTGTAGGTTATGACCTGTTCGGGGGACGCTGCCCCCCCCC
          GTACCTTAGGCACGGGCCTTAGGTAGATCCTGTCCCGTTCGTCGTACGCTCAGCCCTCCA
          GTCCCGTAGGCTCGGGCCTTGGGGGGATTCTGCCCCGTTCGACGGACACTAACTCCTCCC
          GTAGAGTAGGCTCGGGCCGTCGGCAGATTCTGACCCGTTCGACGCACACTTACTCCTCCC
          GTACCGGAGGCTCGGGCTTTTGGGAGATTCTGACCCGTGCGACGAGCCCTGACTTGGCCC
          GTACCGTAGGCCCGGGCCTTTGGGAGATTGTGTCCCGTTCGACGAACCCTTACTTCTCCC
          GTTCCGTATGCTCGGGCCTTCGGGAGCTTCTGACCAGTGCGACGAACCCTTACTCCTCCA
          GTACCGTAGGCACGTGCCTTAGGCAGATTCTGCCCCGTCCGACGGACCCTGACTCCTCCC

          ATTCTGTCCCCCCAGCAACTGTTCGGTAAGTCCAGGTTCGGAATATTAGTCACGTATCCT
          TTACTTTCTCCCGATAAGTTCTTCGGACAATCGAGGTTCGGAATACGCGTCACTTTTCCC
          TTCCTATCCCCTCACCAAATAGTTTGGAAATCGAGCTTCGGGGTACGAGTGACTTCTCCT
          TTGCTACCTCTACATCATATGGTCCGGAAATCCAGATTCAGCGTCCGAGTGACATCCCCC
          TTGCTCCCTCCTCATCAATTAGTCGGGAAGTCCAGTTTCGGGCTCCGAGTGACTTCTCGT
          TTACAATCCCCCCACCACTTATTTCGAAACTCGAGGTTAGGAATTCGGGGCACGTCACCT
          TTTCTTTCCCCGCAACACTTGCTCGGGAATTCGAGAATCGGGATCCGGGTTACATCTCCT
          TTTCCAGCGCCTCACCAGTTGCTCGGCAATCCAGGATTAATGATAGGCCTCACCGCGCCG
          TTACTTTCGCCTCACCAATTGTTCGGAAATTCAAGATTCGGAATGCGTGTCCCACCTCCT
          TTTCTATCACCTCATCCCTTGGTACGAAATTCCAGGTTCGGCATGCGTATGTCTCCTCCT
          TTCCTATCTCCTAAACACTTGTTGGGAAAATCGAGGTTCGGCATTCGTGTCACCTCTCCT
          TTTCTCTCTCCCCACCGCTTGTTGGGTAATTCTAGGTTAGGCTTGCGTTTCACCTCTCCT
          TTCCGGTCATCCAAACACTTGTTCGGAAATTCGAGGTTCGGCATGGGCATGCCCTCACCC
          TTCCTTTCGCCTCACCAATTCCGGGGAAACTCCAGGTTGGGGATACGTGTCCCATCCCCG
          TTTCTGTCTCCTGACAGTTTGCTTGGAAAGTCCAGATTTGGCAGACGAGTGCCTTCTCCG
          ATGCTGTCCCCAAACAACTTGTTCGGTAATCCCAGGTTTAGGCATCGAGTTACCTCTCCT
          ATACTTTCGCCTTACCACTTGCTCGGCAAGTCTAGGTTCGGGCAACCCGTAACCTCTGCT
          ATACTCTCGCCCGACCAGTTCTTGGGAAAGACCAGATTGGGACAACCATTCACGGCTGCC
          ATACTTCCTCCTCACCAGCTGTTCGGCAATTCTAGGTTCGGGCAACCTGTTACATCCGCC
          ATACTTTCGCCTCACCAGTTGCTCGGCAATTCTAGGTTTGGACAACCTGTTACCTCTGCC
          GTACTGTCGTCGCACCATTTGCTCCGCAATTCCAGATTCGGACAACGGGTCAATGCTCCC
          ATACTGTCACCCCACCAGTTGTTCAGTCACTCCAGTTTCGGTCAACGAGTCACATCTCCG
          ATACTTTATCCACATCAGTTGGTAGGAGATTCCAGTTTCGGTCAACGAGTAACCTCGCGT
          TTGCTGTCTACCCAACACTTCGTCCGAAATTCCAGTTTCGGGCAACGGGTAACTTCCCGT
          ATTCTGTCTCGACATGATTTGGTCGGAAATTCCAGTTTCGGGCAACGAGTAACATCGCCA
          ATACTGTCTCCACATCAGTTCGTTGGAAATTCTAGTTTCGGGCAACGAGTCACCTCGCCT
          ATGCTATCTCCAAATCAGTTGTTTGGGAAATCCAGGTTCGGACATCGATTATCGTCTGCT
          ATGTTGTCTCCACATCACATCTTAGGTAACTCCAGCTTAGGTCAACGTGTTACCTCGCCC
          ATGCTGTCTCCACATCAGTTGTTCGGAAATTCCAGGTTCGGCCAACGACTCACATCGCCC
          GTACTTTCTCGACATCAGGTGATCGGAAATTCCAGGTTGGGCCAACGAGTCCCTTCCCCT
          ATACTATCCCCACATCATTTGATCGGAGATTCCAGGTTCAGCCAACGAGTTACCTCCCCT
          ACACTGTCTCCGCACCAGTTATTTGGCAAATCGAGGTTCGGGCAACGAGTGACGTCCCCT
          ATACTTACTCCACCTCAGTTATTGGGTAATTCGAGGTTCGGTCAAGGAGTAACCTCCCCT
          ATGATGTCTACTCCAGAGTTGTTGGGTTATTCCAGGTTCGGTCAACGAGTAACCTCCCCC
          ATACTGTCCCCACATCACTTGTTTGGAAACTCCAGGTTATGTCATCGTGTGACCACCCCT
          ATACTGTCTCCACATCACTTGTTAGGAAATTCCAGGTTCTGTCAGCGCGTAACGTCACCT
          ATACTATCGCCACAACACCTCTTATGCAATTCCAGGTTCGGGATCCGGGTCACCTCTCCT
          ATACTGTCGCCGGAACAGCTTTTCGGTAATTCCAGCTCCGGGATTTGGGTCACGTCGCAT
          ATACTATCGCCACATCAGCTGTTCGGTAATTCCAGACTAGGGATTCGACTTACCTCACAA
          ATCCTACCCCCGCAACACGTGTTCGGTAATTCCAGCTTCGGCATCCGGCTGACCTCACAC
          ATACTCCCGCCACAACAGCTTTTGGGTAATTCCAGGTTCGGGATCCGGCTCACCTCACAT
          ATACTATCCCCACAACAGCTGTTCGGTAATCCGAGCTTCGGGATCCGGGTCGCCAGACAA
          ATACTATCTCCACAAGAGCTGTTCGGTAATTCCAGATTCGGGATCCGGGTAACCTCACAT
          ATATTTTCGCCCCATCAGCTATTCGGAAATTCCAGATTAGGGATCCGGGTAGCGTCTCCT
          ATTATCGCTCCGCACCACTTGTTCGGGAAATCCATGTTGGGAATACGTGTCACCTCTTCT
          TTCATCTCTCCACACCATTTTTTCGGGAACTCAAGCTTCGGTGTTCGGGTCACCTCTCCT
          TTTATCTCTCCACACCATTTTTTCGGGAACTCAAGATTCGGTGTTCGTGTCACCTCTCCT
          TTTATCTCTCCACACCATTTTTTTGGGAACTCAAGATTCGGTGTTCGTGTCACCTCTCCT
          ATATTCCCACCCCAGAATTTATTAGGAAACTCCAGTTTTGGAATGTGTATAACTTCTCCT
          ATACTGCCCACACACCAAATCTTCGGAAACTCTAGACTCGGGATTCGCGTAACATCTCCT
          ATACTCTCTCCCCACCAAGTGTTCGGTAACTCCAGGTTCGGGATATGTATCACCTCTCCT
          ATTCTCCCCTCCCAACAAGTCTTCGGGTACTCCAGGTTTGGCATGTGTGTCACCTCTCCT
          ATTCTCTCTTCCCAACACGTCTTCGGTTACTCCAGGTTTGGGATATGTGTCACCTCTCCT
          ATTCCATCCCCCCAACATGGCCTCGGTTACTCCAGGTTCGGAATATGTGTCACCTCTCCT
          ATTCTGTCCCCCCAGCATGTGTTTGGTAACTCCCGGGTAGGTATTTGGGTTACCCCCCCG

          TTGTCGAAATCTATACAAAGCCGCCGGCCACCTAGATGGTGCAGGGAATACGCCCCTGTA
          GTTTCGAAATCTTCGCATAGGAGCCGTCCCTCGTGGTGCTGCCGTTAATACGCTACTGGC
          GTCCCCAAATCTTCACACAGCCGAGGCCCGTCGGGATGGCGTCGTTATTTCGCGCCAGGC
          GTCTCCAAATCCTCAGATAGACGCGGACCGTCAGGATGGTGTCGGTATTATGCTCCCCGA
          GTCTCCAAATCATCACATAGACGAGGGCCTTCGGGATGGTGTCGGTATTACGCGGTTGGC
          GTGTCAAAATCGTCCCATAGACGTCGGCCATCGAGATGCTGCAGGTATTACGCCCCTGGC
          GTATCGAAATCTTCTCATATTCGGCACCCATCGAGGAGGTGCAGGTAATGCGCCCCAGGC
          CTGTCGAAAGCGTCAAATAGTCGGCGTCCTTCAAGATGGATCACGTATTATGCGCGTGGC
          GTGTCGAAATCTTCAGACCGGCGACGGCCGTCGTGGTTGTGGAGGTAATACGCCCCTGGG
          GTGTCGAACTCTCCGCAGCGGCCAAGGCCGGCCCGAAAGTGGAGATTATACGCACCTGGG
          GTCTCAAAATCGTCACAGCGGCGACGGCCGCCGCGATGGCGGAGGTACTATGCGCCCGGG
          GTATCGAAGTCTTCCCATAGGCGACGGCCCTCGCGATGGTGGCGGTAATACGCCCATGGC
          GTGGCAAACTCCTCACAAAGGCGTCGATCGCCTGGATCCTGGTGGTACTATGCGCCAGGA
          GTGTCGAATTCTTTCCATAGACGACGACCGTCTGGCTGTGGGAGGTAATACGCCCCTGGT
          GCGTCTAAAACTTCTTATAGTCGGCGGCCTTCTCGATGTGGTAGTTAATACGCGCCTGGC
          ATCTCGAAGTCCTCGCATAGGCGACGTCCGGCTAGATGGTGGAGGTACGACGCCCCAGGC
          CTGTCGTATTCCCCGCAAAGGCGGCGAGCAGCTAGGTGGCGGAGTTATGATGCGCCTGGG
          CTGTCGGAATCATCGCATAGGCGACGACCGGCTAGTTGCCGTAGATATGACGTGCCTGGC
          CACTCGGATTCTTCGCACAGGCGGCGACCGGCGAGTTGCCGGAGACATGACACGCCTGGC
          CTGTCGGAGACTTCGCACAGGCGGCGTCCGGCAAGATGGCGGAGTTATGACGCGCCTGGC
          CTGACGGAGACTTCACATAGACGACGGCCGGCTGGCTGGCGTAGATATGAATCGCCTGAT
          CTGACGGATTCTTCGCACAGGCGACGGACGGCCTGCTGGTGTAGGGATGAAGCGCCTGAG
          TTCTCTGATCCCTCGCATAGGCGGCGGCCAGCTAGCTGGAGTAGCTATGAAGCGCCCGGA
          TTTTCGGATCCCTCGCATGGCCGACGTCCAGCTAGCTGGAGTAGGTACGACGCGCCCGGC
          TTGACTGATACCACGCAGAGGCGACGATCAGCTACTTGGAGGAGGTCCGATGCGCCGGGC
          TTGTCGGATCCCTCTCATAGGCGTCGGTCAGCTAGTTGGAGTAGGTCAGACCCGCCCCGC
          ATGTCAGACTCGTCTCATAGGAGTCGGCCAGCTAGTTGTAGTAGTTATGATGCGCCCGGA
          TTTTCGGAGTCGCCTCATAGAATGCGGCACGCTAGTTGCAGTAGGTATGACCCCGCCGGC
          TTGTCGGATTCCTCTCATAGCAGAGGGCCAGCTAGTTGGGGTTGGTATGATGCTCACGGC
          CTATCTCACTCCTCGCAAACTCGCCGCCCGGCTAGTTGCAGCAGGCATGAAGCGCCCGGC
          TTATCTCATTCGGCGCATAGGCGACGGCCGGCTGGGTGGAGTAGTTACGATGCGCCTGGC
          CTTTCGGATTCCTCGCCTTGGCGACGCCGGGCGAGTTGGTGCAGTTATTATGCACCTCGT
          CAGTCGGATTCTTCTCATTGGCGGCGGGGGGCTAATTGCTGGAGGTATGAAGCTCCAGGT
          CTGTCAGATTCCTCGCAGTGGCGGCGGCGGGCTAGATGTTGCAGGTATGAAGCACTTTGG
          ATCTCTGATTCGTCGCGATGCCGCCGTCGGGCTAGTTGGTGCAAGTATGAGGCGGCTGGA
          CTTTCTGATTCGTCTCATTACCGACGGCGGGCTAGTTGGTGCAACTATGAAGTGGCTCGA
          ATTTCTAAATCTTCCCAGAGTCGGCGTCCCTCAAGGTGCTGCAGGTATTATGCCTCACGC
          ATCTCAAGTTCGTCCCAAAGACGACGTATGTCAAGATGCTGCAGGTATTACGCCCCCCGA
          ATCTCAAAATCTTCCCAAAGACGTCGGCTGGCAAGTTGCTGCAGCTATTACGCCACCCGA
          ATATCTAAATCTTCCCAAAGACGACGGCTGTCGAGTTGCTGCAGGTATCACGCTCCCCGA
          ATCTGTAAATCCTCTCAAAGCCGACGGCTGTCAAGTTGCTGCGGATATTACGCCGCCCGA
          ATCTCTAAATCTTCCCAAAGACGACGGCTGTCGAGTCGTCGTAGCTATCACGCCCCCCGG
          ATCTCTAAATCTTCTCAAAGACGGCGGCTGTCAAGTTGCTGCAGCTATTACGCTCCCCGC
          ATCTCTAACTCTTCCCAACGACGACGGCCATCGAGTTGGCGTAGTTATGACGCGCCGCGT
          GTTTCGAAGTCGTCGCACAGGGGACGGCCCTCGGGGGCGTGCAGATAATACTCCCCGGGT
          GTGTGGAAGTCTCCGCATAGGGGACGGCCGCCGGGGTGCTGTAGATAATACACTTCAGGA
          GTGTGGAAGTCTCCGCATAGGGGACGGCCGCCGGGGTGCTGTAGATAAAACACTTCAGGA
          GTGTGGAAGTCCCCGCATAGGGGACGGCCGCCGGGGTGCTGTAGATAAAACACTTCAGGA
          GTGTCTAAATACTCTCACAGACGCCGGCCCTGGAGTTGGCGCAGTTAAGACGCCCCCGGC
          TTAGCGAAATCGTCGCAGAGACGCCGGCCGTCCAGATGCTGCAGGGAATACGCACCTGGG
          TTGTCCAAATCTATACATAGCCGCCGACCTTCTAGGTGGTGCAGGTAATACGGACCAGTC
          TTGTCAAACTCAATCCAAAGGAGTCGGCCGTCTAGATGTTGCAGGTAATACGCTCCAGCC
          TTGTCAAACTCAATACAAAGGAGTCGGCCGTCGAGATGGTGCAGCTAATACGCCCCAGTC
          CTGTCCAACTCTATACAAAGCAGTCGACCATCTAGATGGTGGAGGTAATATGCCCCTGTG
          TTGTCGAATTCTATTCTTTGCTGGCGCCCGCCGAGATGGTGCAGGTAATAGGCACCTGTC

          GTCTAGGCTCTCGTTTATCTTCGAACTGAGGTAACTGGAGATGACCCCCGGCGCTCGATG
          TTGTATTCACTGATGTATCTGAGAACGGACGAGGTGAGATATGATCCCCTGGGCACGATA
          GTTCATTCCCTCAAGAAGATAAGTACCAACGAAGCGAGATATGAGCCTCGGGGTCCGAAA
          GTATATTCAGCAATGAACATCAGGACGTACGAAGCGAGATATGACCCTCCCGGTACGAAA
          GTATATTCACTGATGAAAATCAGTACCAACGAAGCGAGATATGACCCTCCGGGTACAAAA
          GTATATTCACTAGTCCACCACCGCACGGACGAAGCTAGATACGACACCAGTGGAACGATG
          GTGGATTCCCTGATCTACCTCGGAACCCACGATGCTAGCTATGATCCTGGAGGAACCATT
          GTATACTCTCTCGTATACCTCCGTCCTCAGGAAGCAAGATACAACCCTCGCGGGACGATT
          GTGTATGCCCTTGCGTACCTCCGGAGTGATGAAACTCGATACGATCCTCGTGGAACGATA
          GTGTATTATCTTCTCTACCTGCGTAGCGAAGAAGCTAGAGATGAGCCTCGAGGAGCGATT
          GTGTATTCTCTTGTGTACGTGCGTAGGGAGGAAGCTAGATATGACCCTCGCGGTACGATC
          GTCTATTCTTTGGTGAACGTTCGCCGCGATGTAGCGAGATATGAAACTCGGAGAACGTTC
          CTGTATTCTATGGTATACCTGGGAGTAGATGTAGCTGGACAGGACCCCCGAGGACCGACG
          GTAAATTCGCTGGTCCACCTCCGAACCGAATACGCTAGAAAGGACCCGTGGGGAACGACT
          GTGTATCCTCTGGTCTACCTCCGACCCTACCACGCTAGCTATGATCCCCGTATAACGATT
          GTCTATTCTCTGGTCTATGTTCGAACAGATGAAGCTCGGGACGAGCCCCGGGGATCAATG
          GTCTATTCCCTGGTATACGTACGTACCGAAGAAGCACGAGCTGAAGCTCGGGGATCAACT
          GTATATGCTCTGGTATACTATAGACCGGAGCAAGCACGAGCCGAACCCCGGAGATCATCT
          GTCTATTCACTGGTATACGTACGAACCGACGAAGCACGTCCTGACCCCCGGGGATCAGCT
          GTCTATTCACTTTTATACGTACGAACGGAAGAAGCACGAGCAGAGCCCCGGGGATCAACT
          GTATATTCACTGGTGTACGTTCGATCACAGGAAGATCGAGAGGACGCCTGTGCCTCGATT
          GTCTATTCACTGGTATACGTTCGAACGGAGGAAGCCCGAGAGGACGCCCGGGGCTCAATG
          GTGTATTCACTGGTGTACGTTGTAACGGATGAAGCGCGCGATGACCCGCGGGGATCCATC
          GTCTTTTCGCTGGTGTACGTTGTAACGGATGAAGCGCGCGAGGATCCAAGGGGACCCCTC
          GTATACACGCTGTTTTACGTTGTAACGGAAGATGCGCGAGAGGACCCCCGCGGATCAAGT
          GTCTACGCACTGGTTTACGTTGTGACGGAGGAAGCGCGAGACGACCCTCGGGGATCCATC
          GTCTATTCACTCATGTACGTGGGAACGGAAGAAGCTCGAGAGGACCCCCGGGGGTCAATC
          GTCTATTCTCTTGTTTACGTAGGCACGGAAGTAGCGCGCGAGGAGCCCCGAGGATCTATC
          GTCTATTCACTGGTTTACGTTGGAACTGAAGAAGCCCGAGAGGACGCCCGCGGATCAATC
          GTCTATCCACTGATGTATGCTGGAGCGGATGAAGCGCGTGATGATCCACGAGGTCCTTTG
          GTATATCCGCTAGTACACGTCGGTACAGAAGAAGCGCGAGAAGACCCTCGTGGTCCCCTC
          ATATATTCTTTGGTTTACGTTCGAGCGGAAGAAGCCCGGGACGACCCCCGGGGATCAATT
          GTATACTCTCTGGTTTATGTTGGATGCGAAAAAGCGCGAGAGGACTCACGTGCATCAATT
          GTATATTCTCTGTTTTACGTTGGAGCCGACAAAGCGCGAGACGACTCTCGGGCATCTATT
          GTTTACTCTCTGGTCTACTTTGGAGCGGAAAACGCGCGAGACGAGCCCCGAGGATCAATG
          CTCGACTCGCTGGTGCACGTCGGGGCGGAAAAAGCGCGAGAGGACAGCCGTGGATCAATT
          GTCTACTCCCTCGTATATGTTCGAACCGACGAGTCTCGTGATGACCCCCAAGGCTCCATA
          GTCTATTCCCTGGTATATGTTCGAACAGACGATCCTCTGGACGACGCCCATGACTCAATT
          GTCTACTCTCTGGTGTATGTTCGGACAGACGAGCCTCGTGACGACCCACAAGGCTCCATT
          GTCTACTCTCTGGTTAATGTTCGAACAGACGACCCTCATCACGACCCCCATGGCTCTTTC
          TTCTACTCTCTGGTATATGTGCGACCAGATGAGCCTCATGACGACCCTGATGGGTCTATT
          GTCTACTCGCTGGTCTACGTTCCAACAGAGGAAGCTCGTGACGACGCCCATAGCTCCATT
          GTCTACGCTCTTGTCTATGTTCGGACAGAGGAGGCTCGTGACGACGCCCATAGGTCCATG
          GTCAACTCACTGGCATATGTTCGGACAGACGATGCTCGTGACGAACCCCAGGTATCCGTT
          GTGCACTCTCTGGTGTACCTTCGAACCGACGAAGCAAGTGAGGACCCCCGCTCTTCGTTT
          GTGTATTCGCTTGTCCACCTTCGAACCGATGAAGCTAGGGATCACCCCCGCGCGTCCTTG
          GTGTATTCGGTTGTCGACGTTCGAACCGACGAAGCTAGGGATCACCCCCGCGCGTCCTTG
          GTCTATTCGGTTGTCGACGTTCGAACCGACGAAGCTAGGGATCACCCCCGCGCGTCCTTG
          GTTTTTCCTAAGGTAAAGCTTCGAACCAACGACGCGAGGGTCAAACCGCGGGGCTCCCTT
          GCTTATTCTCTGGTGTACCTTCGAACAGACGAAGCTAGAGACGACCCCAGGAGATCCATA
          GTGTAGGCTTTAGTTTATCTACGAACTGACGAAGCTAGGGTGGACCCCCGGGGTTGGATG
          GTATACGCTCTCGTTTATCTGCGAGCGGAAGAACTTGGAGAGGACCCCCGATGGTCGATT
          GTATATGCTCGAGTCTATCTGCGAACCGAGGAGCCGGGTGATGACCCCCGAGGGTCGATG
          GTCTAGACACTCGTTTATCGGCGGACAAACGAACCTGGCGATCAGCCCCGGGGATCCATG
          GTCTAGGCCCTCGTTTACCTCCGGACTGAGGAGGCTGGAGATGACCCCCGCGGCTCGATG

          GCCAAATGTTACTAC
          GCAAAATGTCCCTAT
          GCCAAGGGTCCCTAC
          GCGAAAAGTGCAAAT
          GCGAAAAGACCCTAC
          GCGAAATGCCCCCAA
          GAGAAGTGTCCCTAT
          GCTAAGTGCGCCTAG
          CCGAAGTGTTCCTAC
          GCGAATCGTTCCCAC
          GCAAATTGTTTTTAC
          GGGAAGTGTTCGTAA
          GCCAACTGTTCATAC
          GCGAACTGCGCTTAC
          GCAAAATGTTCGGCC
          ACCCAGTGTCCCGAC
          ACGAAGTGTCCCGAT
          GCCAAGTGGTCTGGT
          GCAAAGTGGCCCGAA
          GCCAAATGTTCCGAA
          GTCAAGTGTCCCGAG
          ACCAAGTGTCCCGAG
          GCCAAGTGTCCCGAT
          GCCAAGTGCCCCGAT
          GCGAAGAGGCCCGAA
          GCACAGTGGCCTGAA
          GCCAACTGCCCGCAT
          GCTAAATGCCCAGAT
          GCAAAGTGCCCAGAA
          GCAAACGGCCCAGAT
          GCCAAGTGGCCCGAA
          GCCAAGAGTACGGAT
          GCCGAATGTACGGAT
          GCTAAATGTTCGGAT
          GCCAAGTGTCCTGAT
          GCCAAGTGGCCGGAT
          GCAAAGTGGCCGTAC
          GCCATGTGTCCGTAC
          GCAAATTGGCCCTAC
          GCAAAGTGGCCATAC
          GCAGAGTGGCCGTAC
          GCCAAGTGTCCGTAC
          GCGAAGTGGCCTTAC
          GCAAAGTGTCCCTAC
          GCAAAGTGTACATAC
          GCCAAGTGTCCCGAT
          GCCAAGTGTCCCGAT
          GCCAAGTGTCCCGAT
          GCCGAAGGGGCGTAG
          GCTAACTGTCCGTAC
          GCCAAATGTTCCTAC
          GCCGAGAGTTCACAA
          GCCAAATGTTCCCAC
          GCCAAATGCTCATAA
          GCAAATTGTTCCTAG

