 55 603
Haliotis_ AACGACGTCCGTGTTTCCCTCCAACTATATAATGCACGCCTACTCGAAGGCCACAAACCG
Chiton_ol AACGACTTCCGTGTATCAGTGGATCTACATAATCCACGAATTCTTGTAGGTTATAAAACC
Chaetoder AAAGAGGTCCGTGTGCCAGTGGAATTGTATAAAGCTAGGATACTTGTAGGTTATAAGGCG
Greenland AAAGACGTCCGTATGCCAGTCGAATTGTATAAAGCGAGGATACTTGTAGGGGATAAGGCA
Neomenia_ AAAAACGTCCGTGTACCAGTCGATTTGTACAAAGCCAGGATACTTGTAGGGTATAAGGCA
Gadila_to AACGTTGTCCTGGTATCTGTAGACCTTTATAATGCCCGCATTCTTGTAAGTTACAAGCCT
Laevipili AAGGACGTTCGAGTATCAGTGGACCTATACAATGCCAGTCTTCTAGTCGGGTATAAACCT
Octopus_v AATGAAGTCGGTATATCGGTCGTACTATACTACGCTAGAATTCTCGTCGACTATAAAACT
Mercenari GGAGTGGTCCGTGTGTCAGTCGAGCTATATCAAGCACGTCTACTTGATGGGTATAATCCA
Myochama_ GACGACGTACGGGTATCCTTAGAACTATATGAAGCACGGATGTTTGATCGGTATCACCCT
Astarte_s GACGACTTACGTGTATCAGTAGAACTATACCACGCACGAATACTTCAAGGATATAAACCT
Neotrigon AACAACGTACGTGTATCAGAAGATCTGCAGCAAGCACGAATGCTTGAAGGCTATAAACCT
Pinctada_ AACGAGGTACATGTATCAGTAGAGCTGGATAATGCTGGAATCATAGAGGGGTATAAACCA
Solemya_v AACGAGATCCGTGTATCAGTCGACTTCAATAATGCACGGATACGGATAGGGTATAAACCT
Ennucula_ AACAAAATCCGTGTGTCAGTTGATCTATATAATGCACGAATCGTGGTAGGGTATAAGCCT
Doris_ker AACGAGGTCCGGGTGTCATTCGAACTGTATAAGCCGCGTATCCTAGTCGGGCGTAAACCT
Pleurobra AAAGGGGTTCGAGTATCATTCGAACTCTATAACCCGGGTATGCTAGTGGGGTGTAAACCC
Fiona_pin CAAGGCGTCCGAGTATCCTTACACCTAGATAACGCGGGGATCCTAGTTGGATTCAAACCC
Bathydori CATGGGGTTCGAGTATCATTTGAAATATATAACCCCGGAATCCTCGTTGGTAGTAAACCG
Architect CACGGCGGCCGAGTCTCGTTCCAAATATATAACCCGGGGATCCTTGTTGGGTGTGAAACC
Rissoella ATTGGGATGCGCGTTTCATTCAAACTATACAAGCCGTGGATGCTTGTAGGGTGTAAACCC
Hydatina_ ATCGGAGTTCGAGTATCCTTCGAACTCTACAATCCGGGGATACTAGTCGGCGGTAAACAA
Ophicarde AACGGCGTGCGCGCAGCATTCGACCTATATAATGCGGGTCTCCTAGTCGGATGCAAACCT
Onchidell ATAGGCATCCGCGTATCACTCGACCTATATAATGCGGGTCTCCTAGTCGGGTGGAAACCG
Microhedy AAAGGGGTGCGTGTCTCGTTCGAGCTACATAATGCCGGTCTACTAGTCGGGTGTAAACTT
Strubelli AACGGGGTCCGCGTATCGTTCGAACTAAATAATGCAGGTCTCCTAGTCTGCTGTAAACCG
Phallomed AACGCGGTGGGCGTGTCATTCGAACTAGATAATGCAGGAATCCTAGTGGGGTGCAAACCT
Turbonill AAAGGTGTGCGTGTATCATTCGAATTATACAAAGCAGGAATTCTCGTAGGGTGTAAACCG
Siphonari AACCGAGTGCGCGTATCATTCGAACTATACAATGCGGGAATCCTGGTCGGCGGAAGAACT
Biomphala AACGGGGTGCCCGTTTCCTTGGTACTAGATAATACGGGAATTCGAGTGGGGCCTAAACCG
Oxynoe_vi AACGGGGTGCGTATATCATTCGTGCTGTACAATCCGGGCATCCTGGTCGGGTGTAAACCT
Tylodina_ AACAGGATACGCGTATCATTGAAACTATATAAACCGGGAATCCTAGTCGGGTGTAATCCT
Aplysia_c AAAGGAGTACGGGTTTCATTCGAAGTATATGATCCGGGAATTCTCGTGAGGTGCAAAGCT
Clione_an AACGGGGAAAGCGTGTCATTCGAAGTATATGATCCGGGAATCCTAGTCAGGTGTAACGCT
Haminoea_ AACGGAATACGGGTATCTTTCAAAGTATACGAGCCGAGGCTTCTGGTGGGGTGTAACGCG
Philine_a AATGGTATACGAGTATCTTTGAAAGTGTATGATCCTAGACTACTGGTCCGGTGGAATGCG
Hinea_bra AATAAGGTCCGTGTTTCAGTTGAACTCTATCACCCGCGAATCCGTGTTCGGGACAAACCT
Janthina_ AATGAGGTTCGTGTTTCAGTGGAACTATATCATCGGCGGATTCTAGTACGCTACAACCCA
Rubyspira AATGAGGTCCGTCTTTCAGTTGAACTATATCATCCGCGGATTCTCGTCCGGTACAAACCT
Littorina AATAAGGTCCGTGTTTCAGTCGAACTATATCATGCGCGGCTTCTCGTACGGTACAAACCT
Polinices AAGGAGGTCCGTGTTTCAGTTGAACTATATCAACCGCGGCTTCTCGTCCGCTACCAACCT
Urosalpin AAAGATGTACGCGTTTCAGTTGATGTATATCATCCGCGAAGAATCGTCCGATATATTCCT
Ilyanassa AACAACATCCGCGTATCAGTTGAACTATATGATCCGCGTATGCTCGTCCGGTATAATCCC
Pomacea_d AACGAGTTACGGGTTTCGCAGGATCTATATAGTCCACGAATCCTCGTCCGGCCCAACCCT
Nerita_pe AACGACGTTGGGGTGTCCGTCGTATTGTACAAGCCACGAGGGCTGATAAGGCATAACCCC
Pyropelta AATGACGTGCGTGTTTCGGTCGACGTTTACAATCCAGGAATCCTGGTCAGGCACAAACCC
Titiscani AATGACGTGTGTGTTTCAGTCGACGTTTACAATCCAGGAATCCTGGTGAGGCACAAACCC
Paralepet AATGACGTGTGTGTTTCAGTCGACGTTTACAATCCAGGAATCCTGGTGAGTCACAAACCC
Lottia_gi AAGGATGTCCGGATTTCTATCGAATCACATAATCCACGCGTTTTCGTGGGGAACAAATCT
Perotroch AATGACGTGCGTGTTTCGGTCGAGCTATATAATGCGCGGATAGTGGTGGGTTACAAATCA
Granata_i AACGATATCGGGGTTTCTGTGCAACTATATAAAGCGCGGCTAATCGTAGGCCACAACCCG
Prothalot AACGACGTGAGTGTTTCCGAGCAACTATATACAGCACGACTACTTGTAGGCCAAAAACCA
Monodonta AACGACGTCAGAGTTTCGGACCAACTTTATAAAGCACGACTACTCGTAGGCCAAAAACCG
Phasianel AATGACGTCCGTCTTTCGGTCCAGCTATATAATGCACGACTACTTGTCGGACACAAAGCA
Lepetodri AACGACGTACGCGTATCCGTTCAACTATATAATGCACGACTACTGGAACGCCATGAGCCG

          TTTAGACATCGCCGATCTTGCCATCAAATACAAGCGTCTTCTATTAGCTGATCCCGATGT
          GTCAGCCGACGGCGTTCTAACCGCCATCTACACGCATCGTCTATGAGATGATTTCGTTGT
          GTGAGACAGCGACGTACGCACCGACCAAGACACGCCTCGTCCATTAGCAGATTTCGTCGA
          TTAAGACATCACGGGTCCCACCGTCCTATACAGGCGTCGTCAATCAGGTGGTTGCGTCGA
          TTGAGACAACAACGGTCGCACCGTCCGATATCGGCGTCGTCTATCAGGTCATTACGTCGA
          GTAAGACCACGTCGCTCGGGCCGTGAGCTACACGCGTCATCTATAAGATGTTTCGGTTGG
          GTCAGACAACGGAGTGCACGTGGCAAAGTGCAAGCTTGGTCTATTAGCTGTTTCCGCTGG
          GTAAGACATCGACCCACTCGGCGCCAGGTGCAAGCACCATCTGTCAGCTGTTTGCGATGG
          TTAAGTTACCGGCGTACCCCCCGGCAGTTGCATGCCTCCTCCATTAGCAGATTGCGCGGG
          TTAAGACACGGACGTACGTGCCGGCAGATGGAAGCTTCCTCTATGAGCTGATTCCGATGG
          GTGCGACAGCGACGTACGCGACGCCAGATGCAAGCTTCATCTATTAGAAGATTGCGCCGG
          GTTAGACAACGACCTACATGGCGCCATGTTCAAACCTCCTCTATGAGCTGAGTCCGATGG
          ATCAGGCAACGTCGTTCATGCCGCCAGATTCAAGCGTCGTCAATAAGCTGATTCCGCAGA
          GTTAGACAGAGAAGTTCGTGGCGCCTGATTCAAGCGTCATCCATTAGTTGATTCCGCGGG
          GTCCGAAACCGCCGTTCTTGCCGGCAGAATCAAGCGTCGTCCATTAGAGGATTAGGCCGC
          TCGAGACAAAGCGACTCGTGCCGACACATTCAATTATCTGCGACGAGATGATTTCGATGC
          TTTAGAAATCGAGGCTCGTGTCGAAAACTGCAAGCGTTTGCTATCAGTTGGTTTCGATGG
          TTTAGGCAACGGGGCTCCTTCCGCAAGATCCATGCGTCAGCCATCAGTTGATTACGTTGG
          TTTAGACAACGCGGATCGTGCCGAAAAATGCAAGCGTCTCCTCTCAGTTGTTTTCGGTGG
          TTTGGACAACGTCGGGCGTGGCGCAACATGCAAGCGTCTGCTATGAGCTGCTTTCGGTGG
          TTTAGGCAGCGCGGGTCTTGCCGCAACATCCAGGCTGCCGCAATCAGTTGGTTTAGATGG
          TTTAGGGAGCGCGGATCGTGCCGAAAAATGCAGGCGTCTGCTATTAGTTGATTTCGATGG
          CTAAGTCAACGGGGCCCGTACCGGAAAATGCACGCTTCTGCTATGTGCTGAGTCCGCTGG
          CTTAGGCAAAGGGGCTCGTACTGGAAAATACACGCGTCTGCTATGAGTTGATTCCGATGG
          CTTAGGCAACGGGGCTCGTACATGAAAGTAAACGCGTCTTCGATAAGTTTATTACTATGG
          CTTAGGGAACGGGGCTCGTATAGGGAAGTACACGCGTCTGCTATTAGCTGATTCCGGTGG
          CTTAGGCAACGGGGCTCATACCGGAAGGTTCACGCGTCTGCTATTAGCTGATTCCGTAGG
          CTCAGGCAACGGGGCTCGTACCGTAAAGTTCAGGCGTCAGCTATTAGTTGGTTCCGATGG
          CTTAGGCAACGTGGCTCGTACTGGAAAGTACACGCGTCAGCAATAAGTTGATTCCGTTGG
          CTTAGGCAACGCGGCTCCTACCGCAAAATACACGCGTCTGCTATGAGTTGATTTCTTTGG
          CTTAGGCAACGGGGCTCGTATCGAAAAATCCACGCGCCTGCTATTAGATGGTTTCGTTGG
          CTTAGACACCGGGGCTCGTACCGGAAAATGCACGCGTCGGCTATTAGTTGATTTCGGTGG
          CTTAGGCAACATGGATCCAACCGGAAAATGCAGGCGTCTGCGATTAGATGATTCCGTTGC
          CTCAGACAACAAAGACCAAAACGCAATATGCAGGCGTCTGCCATAAGTTGATTCCGAGGC
          CTAAGACAACGGGGATCGTACCGCAAGATGCAAGCGTCTACCATTAGTAGTTTCCGATGG
          CTGAGACAAAGGGGATCGTATCGCAAAATTCATGTGTCTGCCATTAGTAGATTCCGATGG
          GTTAGTCATCGCCGTTCTTGCCGTCAATTGCAAGTGTCATCTATGAGCTGATCCCGGTGG
          GTGAGTCATCGCCGGTCGTGGAGTCATTTGCAAATGTCATCTATTAGCTGATTCCGATGG
          GTCAGTCATCGCGGTTCCTGCAGTCAAGTGCAAGTGTCATCTATTAGCCGATTCCGTTGG
          GTCAGTCATCGCCGTTCATGCCGTGATTTGCACGTTTCATCTATTAGGTGATTGCGTTGG
          GTCAGTCATCGCCGTTCGTGCCGTGATTTTCATGTGTCATCGATTAGGTGCTTACGTTGT
          GTTAGCCATCGCCGTTCCTGCCGTCATTTTCAAGTGTCATCTATTAGTTGATTCCGATGG
          GTCAGCCATCGACGTCCCTGCCGCCATTTGCAATTGGCCTCTATTAGTTGCTTCCGGTGG
          GTAAGTCATCGCGGTTCGTGCCGTCATTTCCACGTATCCTCTATTAGCTGATTGAGATGG
          GTAAGACAACGCCGCCCATGGCGCCAATTACAAGCGTCAGCTCTTAGGTGATTAGGGTGG
          GTAAGACAACGGCGCTCGTGCCGCCAAATTCAAACATCGGCGCTTAGGTGGTTACGGTGC
          GTAAGACAACGGCGCTCGTGCCGCCAAATTCAAACATCGGCACTTAGGTGGTTACGGTGC
          GTAAGACAACGGCGCTCGTGCCGCCAAATTCAAACATCGGCACTTAGGTGGTTACGCTGC
          GTCAGACATCGTCGGTCGCGACGCCACATACAATCGTCGTCCTTAAGCAGCTTCCGATCC
          GTTGGACATCGCCGCTCGTGCCGACATATTCAAGCGTCGTCTAGTCGCTGATTCCGATGT
          ATGAGTCATCGCAGTTCTTGCCATAAAACACAAGCATCCTCTATCAGATGTTCGCGATGT
          ATAAGCCAACGCCACTTGTGGCATCAAATACAAGCATCTTCTATCAGCTGATCCCGGTGT
          ATTCGCCAACGCCTCTTTTGCCATCAAATACAAGCATCTTCTATGAGCTGATCCCGATGT
          ATTAGACATCGTCTATCGTGCCATCAAATACAAGCATCTTCTATTAGCTGATCCCGCTGT
          ATTAGCTATCGTCGATCTTGCCAAAAAATACAAGCGGCTTCAATGCGCTGATCCCGATGC

          CAAGCATGATCTAGAGGACGAAAGGGATCTGATGCAGTTAGCACCACGTGTCAACGGACC
          TATATTTGCTCAAGGGGCCGACATAGTGCATATTCTGTAAGCACGACGAGTCAATGCACA
          AATATATGTACAAGCGTGCGACAGAGCACAGACTCTGTTAGAGCGACCTGGCATTGGATG
          AATATCTGGACAAGTGGCCTTGATAGCGAAGATTCGGTTAGAGCCACCTGGCATTGGACA
          AATGTTTGTACTAGTGGCCGACATAGCACGGATTCTGTTAGAGCCACGTGGCATTGCACG
          AATGTGAGTTCTAGAGGTGGGCAACGAGCAGAATCCGTTAGCGCGTCATGTCTATACACC
          AAAGTATGTGCAAGTAGACACCAACGCACTGAATCTGTTAGGATTTCCTGGCACCGCACA
          AAAGTATGTACCAGTAGCCCGCACCGAACAAATTCCGTTGGCACGACTCGACATCGGACG
          AATGTGTGTACAAGGGGTCGCCAACGTGGTGAGAAAGTCAGCGCGCCTTGCCATCGCACT
          AATGTGTGTACCAGGGGTCGCCAACGTGCAGATCCGGTCAGTTCGACGTGGCAACGTACC
          AAAGTGTGTAGGAGGGGTCGCCAACAAACTGAGTCCGTCAGTACGACCTGTCATCGTACT
          AATGTATGGACGGGTGGACGACAACTACCAGATTCTATTAGTACGACCTGTCATCGAACA
          AATATATGCACGAGTGAACGTGAACGTCCTGATTCTGTAAGAACTACCTGTCAACGTACA
          AAGGTATGTACAAGAGGACGGCAAAGATCAGATTCTGTTCGAACGCCCTGTCAGTGGACG
          CATATATGTGCCAGAGGTCGACAACGAACACAGTCGGTTAGGACGACCAGTCAACGTACT
          CAAGTTCGATCGAGCGGCCGGAAAAGATCAGAATCAGTTAGAACTACTAGACAACGTAGG
          CATGTATGATCAAGTTGCCGGCAGAGCTCAAACTCGGTTAGGACAGCTTGCGAACGTAGA
          CATCTCCGATCTAGGAGCCGGCAGGGGTCAGAGCCTGTCAGGACAACATGTCAAAGTAGA
          AATGTGTGACCTAGTTGTAGGCAGAGACCCGAATCCTTGCGGACTACCTGTCAACGAAGA
          CATGTGTGATCAAGTTGCAGCCAGAGACCAGAATCCGTTAGTACTACAAGCCGCGGAAGT
          CATGTTTGCTCGAGTGTCCGGCAAAGATCCGATTCAGTTAGGACTACTTGCGAACGCAGG
          CATGTCTGATCGAGAGGACGCCACAGATCAGAATCAGTTAGGACTACTTGCCAACGCAGA
          CAAGTTTGATCAAGCGGACGCCCGAGGTCAGAATCAGTTAGTACTACATGCCAACGTAGA
          CATGTTTGATCGAGCGGACGGCCGAGCTCAGAATCCATTAGGCCTACATGCCAACGCAGT
          AATTTCTGTTCGAGAGGACGGCACAGCTCAGAATCAGCTATGACTACGTGCCAAGGCCGA
          CATGTTTGATCGCGCGGTCGGCAGACGTCGGAATCCGTTAAGACTACATGCCAACGCAGA
          CATGTTTGAACAAGTAGACGTCAGAGCTCAGATTCGGTTAGGACTGCCTGCCAACGCAGA
          TATGTTTGAACGAGTGGACGTCAGAGCTCCGACTCGGTTAGGACTACATGTCAACGCCGG
          CACGTTTGAACGAGTGGACGTCGGAGATCAGATTCGGTTAGGACTACATGGCAACGTAGA
          CTCGTCTGAACGAGTGGCAGCCAGAGATCTGAATCCGTCAGCACTCCTTGCCACTGCAGC
          CAGGTCTGATCGAGAGGACGGGAAAGATCAGAATCAGTGAGGACTACTCGCGAACGCAGA
          CAAGTCTGATCGAGTGGACGGCAGAGCACAGAACCCCTTAGGACTTCTTGCCAGCGAAGG
          CAGGTATGATCAAGTGGATGGCAGAGATCAGAATCGGTCAGGACTACCTGCCAGCGAAGC
          CAGGGTTGATCGAGAGGAAGGCACAGATTAGAATCCGTCAGGACCACCTGCCAGCGAAGC
          CACGTCTGATCCAGAGGACGGCAGAGATCCGAATCCGTTAGGACTACTTGCCACCGAAGT
          CAACTCTGATCGAGTGGACGTCAAAGATCCGAATCAGTTAGAACTACATGCCACCGAAGG
          CAGGACCGATCAAGTGGTCGGCAAAGTTCAGAATCAGTTAGGACAACCTGTCCGCGCAGG
          CACGGCTGATCGAGTGGACGGCAAGGATCTGAGTCCGTTAGAACACCGAGCCAGCGCAGG
          CACGGCTGATCGAGCGGACGGCAGAGTTCAGATTCAGTAAGAACAACAAGTCAACGAAGG
          CACGGCTGATCGAGTGGACGGCACAGATCAGACTCAGTTTGTACAACTAGTGAACGCAGG
          CACGGCTGATCGTGCGGACGGCAAAGATCAGATTCAGTGTGCACGACTAGTCAACGGTGG
          CACGTCAGATCGAGAGGCTGCCAAAGATCAGAGTCAGTGAGAACAACTTGTCAACGCAGA
          CACGTCTGATCGAGCGGATGCCAACGATCAGACTCAGTTAGAACAACTTGTCACCGCAGG
          CAAGTCTGCTCAAGTGGACGGCAAAGAACAGATCCCGTTAGGACAACTTGTAAGCGCAGA
          CAAGTATGATCAAGTGGACGCCAGAGTTCTGAATCCGTCAGAACCACGTGGCACAGCAGT
          CAAGTATGGTCGAGTGGACGGCAAAGATCAGAATCAGTTAGAACGACGTGGCACAGTACC
          CAAGTATGGTCGAGTGGACGGCACAGATCAGATTCAGTTAGAACGACGTGGCACAGTACC
          CAAGTATGGTCAAGTGGACGGCAAAGATCAGATTCAGTTAGAACGACGTGGCACCGTACC
          CAAATATGTTCACGCGGTCGGCACAGCTCAGATTACGTGAGCACACCTCGTAATCGAACA
          GAAGTATGTTCCAGCGGACGGGAATGATCAAATTCAGTTAGAACACCATGTCAACGGACC
          CAAGTGTGAGCTCCTGGACGAGAATGATCAGATTCAGTTAGAACCACATGTCAACGGACC
          CAAGTCTGGTCAAGTGGACGTGAATGAGCAGATTCAGTTAGAACTACATGTCAACGGACC
          CAGGTGCGTTCAAGAGGGAGAGGTGGTTCGGATTCAGTTAGAACCACATGTCAACGGACC
          CAAGTATGATCAAGTGGACGAGAATGATCGGATTCAGTTAGAACCACATGTCAACGCACC
          CAAGTATGATCAAGCGGTCGAGATTGGTCTTACTCGGTTAGGACCACCTGTCAACGGCCC

          ATTCAACCCAGTCCTTGCTCATTTTATTTCTAAGTTGGGACTGAGAGTAAAGAAAACTGG
          ATTAAGCCGAGCCCGAGCTCGGTTTATGGAGAAGTGCGTACTGAGAGTAAAGAAAATTGG
          ATTAATCCGAGGGCGTGTCCGTTGAATTTAGACGTTGGTACAGACAGATATGAATACTGG
          ATTAATCCCAGGGCTTGCCCATTGTATTTACATCTGGGTCCGGATAGGTACCAAAACTGG
          ATTAATCCCAGGGCTAGCCCAGTGTTTTTAGAGGTGGGTGCAGACAGATATCATCACGGG
          ATTGAGCCCAGGCCGTGCTCATTCTATTTATATGTCGGTACGGACAGACACGATAACCGC
          ATTAAACCTAGACCTTGCACATTCTATTTCGATGTGGGTACAGACAGCCATGATAAGTGT
          ATTAAGCCTAGATCCTGCTCATTATATTTGGATGTTGGTACGGAGAGCAATGAAAACTGG
          ATCAAACCGAGAACCTGCCCATTTTATTTAGAGTTTGGATCACACAGCAAAGACAAGTGG
          ATAAAACCGAGAACGTGCCCATTGTATATTGAAGTTGGATCAGAAAGCAATGACGACTGG
          ATCAAGCCTAGGCCCTTCTCATTATATTTAGAGCTCGGATCGGAGAGGAACGATAACTGG
          ATGAAGCCGAGAACTTGGTCATTTAATTTCGACGTTGGTGCAGAGAGCAACGAAAAGAGG
          ATTAACCCGGGAACTTGCTCATTTTATCTACACATAGGGACAAAACGCAACGAAAACTGG
          ATAAAACCCAGTGCCAGCTCCTTCTATTTTGAAGTGGGAACAGAGAGCAACGAAGAGTGG
          ATAAATCCAAGCGCTGGCTCATTGTATTTTGAAGTCGGAACAGAGAGGGACGAAAAGTGG
          ATGGAACCGAGGCCAAGCTCATTTTACTCTAACGTTGGCACCTACAGAGATGATAAGCGG
          ATTAATCCGCGGCCTAGTACTTTGAAATCAAAAGTTAGTTCTTATAGGGAGCATAACAGG
          ATTAAACCGCGACCTAGCTCGTTAAATGCACAAGTGAGTTCATATAGGGAACACAACAGG
          ATTAAACCACGCACTTGCTCTTTTAATTCAAAAGTAATCTCAGACAGGGTACATAAGAGC
          ATTAAACCGCGCCCTTGGCCCTTCAACTCAAATGTGAGTTCATACAGCGAACACAATAGG
          CTGAATCCGAGGCCTAGTTTATTCAACTCACATGTCAGGTCATACAGAGAGTATGAGCGG
          ATTAAGCCGCGACCTAGCTCATTAAACTCCAAAGTGAGTTCATACAGTGAACATGAGAGG
          ATTAAACCTCGACCAAGCTCCTTCCACTCAAAATTTAGTACATACAGGGAACAGGAAAGC
          ATTAAACCTCGACCCAGGTCATTGTATTCAAAAGTTAGTACATACAGAGATCATGAGAGG
          GTTAACCCCCGCCCCACGTCATTCCACTCGAAGGTTAGTACATACAGGGAACATGAAAGG
          ATTAAGCCTCGACCCAGCTCTTTCCACTCAAAAGTTAGTACATACAGCCAACAGGAGAGG
          ATTCATCCTCGACCCAGGTCATTTTACTCTAAAGTTAGTACATACAGAGAACACGATAGG
          ATAAAACCTCGACCCAGCTCATTCTACACGAAAGTTAGTACATACAGAGACCATGAAAGG
          ATCAAGCCTCGACCCAGTTCATTCTACACAAAAGTTAGTACGTACAGAGATCATGAAGGG
          ATAAAACCACGATCCAGCTCATTATACTCAAAAGTTAGAACTTACAGCGAAAACGAGAGG
          CTTAAACCCCGACCAAGTTCGTTATACTCAAAACTCAGTACATACAGGGACCACGAGAGG
          ATTAAGCCTCGTCCTAGCTCTTTTTACTCAAATGTTAGGTCACACAGGGAACATGATAGG
          ATCAAGCCTCGACCTAGGTCTCTGTGGTCAAATGTTAGTTCCTACAGGGATCACGCAAGA
          ATCAAGTCTCGCGCTAGCTCTCTATGCTCGAATGTAAGTTCTTACAGTGAGCATGAAAGG
          ATTAAACCACGAACGAGCTCTTTCTACTCCAAAGTTAGTTCATACAGGGAACATGAGAGC
          TTGAAGCCACGCCCCAGCTCTTTCTACCCTAAAGTTAGTTCTTACAGGGAACATCATAGA
          ATCAAAGCTAGACCTAGCTCGATCTACGTAGACCTTGGTACGGATAGCGAGGAAAAGTGG
          ATTAAACCTAGACCAAGCTCTATCTACGTAGAAGTTGGTACGGATAGCGATAAAAACTGG
          ATAAAAGCTAGACCTAGATCTATCTACGTAGAAGTTGGTACGGGTAGCGACAACAAGTGG
          ATCAAACCTAGACCTAGTTCAATCTACGTAGGAGTTGGTACGGATCGCGACAAAAACTGG
          ATTAAACCTAGACCTAGATCTATCTACGTAGGAGTTGGTACGGATCGAGACAACAACTGG
          ATAAAACTTAGACCTAGCTCTATATACGTAGAAGTTTGTACGGATAGCGAGGAAAATTGG
          ATGAATCTTAGACGTAGCTCTATCTACGTAAATATTGGTACGGATAGTGAAAAAAACTGG
          TTTAAGCCCAGACCTAGCTCTCTATACGTAGAAGTTGGGACGGCCAGCGAGGACAAATGG
          ATAAATCCGGGCCCGTGCTCTTTCTATTTAGAAGTAGGGACTGACAGCGAAGAAAACTGG
          ATTAATCCCAGAGCGGGCTCATTCTATTTAGATGTTGGGACTGAGAGCGACGAAAACTGC
          ATTAATCCCAGAGCCGGCTCATTCGATTTAGATGTGGGGACTGAGAGCGACGAAAACTGC
          ATTAATCCCAGAGCCGGCTCGTTCGATTTTGATGTGGGGACTGAGAGCGACGAAAACTGC
          TTTAATACTAGAAAGTGGTCTTTTTATATCGACCTCGGGAACTACAGCGAAGATAAATGG
          ATACACCCGAGTCCTTGCTCATGCTATCTAGAAGTAGGGACAGACAGCCAAGAAAGCTGT
          ATCCAGCCGAGACCTTGCCCCTTCTATTTTTAAGTTGGGACACAAAGCAAAGATAAAGGG
          ATGCACCCCAGACCATGCTCAATCTATATCTATGTCGGGACCGAGAGCATCGAAAAGCGT
          ATGCACCCCAGACCATGCTCACTCTATTTTTATGTCGGAACCGCCAGCAAAGAAAACCGG
          ATTCACCCCAGTCCGAGCTCATTCTATTTCTATGTTTGTACGGAGAGCAAAGAAAACGGG
          ATTCATCCCAGACCTTGCTCATCCTATTTCTACGTTGGGACCGAAAGCAAACAAAAATGG

          TTGGCGGTTGGAAATCATAGTTGGTTTGACTGGCAATTGTACGAACAACAGTTGCGAGGA
          TTCGCAGTGAGCAAAAAAAGCTGTCTCGAATGCCAGGTGTATCTCCACCATTTGCCAGGA
          ATGGCAGTGGGGAATGATAGGTGGCCAGACTGTCACGTGTGTGTCCAGCATTTGACGGGA
          ATGGCCCTAGGCAACGACAGGGGGCCAGAATGCCACGTAAGCGTCCATCAATTGCCTGGA
          ACGGCCCTAGGCCACGATAGGTGGCCAGAGTGCCACGTAAGCGTCCACCAGTTGCCGGGT
          TTCGCGCTCCGTGAAAATAGATGTCTAGAAGGCCAGCTATACGTCCACCACGTGCCCGGA
          ATCTCGCTCGGACAACATGGTTGTCTTGACCGCCAATTGTTCGTACATCATATTCCGGGT
          TTGACTCTGAGTAACAAAAGGCGCCTGGTCTGTCACTTGTACGTATACCATATACCGGGC
          ATAGCACTCGGTAATAATAGTTGGCTAGAACGCCACTTGTACGTGGAGCATTTGCCGGGC
          GTAGCCCTTGATAATAACAGTTGTTTTGATTGGCATTTGTACGTGCAGCAATTATCCGGG
          TTAGCGCTAGGTAATAACAGGTGTCTCGTATGCGACTTGTACGTGCAACAATTGCCTGGG
          TTATCACTCGGCAATGATAGTTGCCTAGAATGCCTTTTGTACGTTCAACAATTGCCCGGC
          CTCGCCCTCTGTAATCAGTGGTGTGTGGACGGCCACTTCTACGTACACCAGTTGCCGGGG
          TTGGCCCTGCGAAAGAAAAGTTGGCTAGAATGCCACATTTCCGTACAACAATTGCCGGGC
          TTAGCCCTTGGGAATAATAGCGGTCTGGATCGACAATTGTACGTGCATCATTTACCTGGG
          TTAGCCCTTGGGAAGAAAAGCTGTGTAAACTGGCATTTGTACAATTACCACTTGCCGGGG
          CTGGCTCCCGGTAAAGATAGTTGTGTAAAATGTCATTTATACGATCCAAATTTGCCGGGC
          TTGGCATTAGGGAATAATAGTTGTGTAAAATGCCAGTTGTACGACCACCAATTTCCGGGA
          TTGGCCCTGGGGAAAAATACTTGTGTGAAATGCCATTTGTACGAACAGCAATTCCCAGGC
          TTGGCCCTGGGGAAGAATAGTTGTGTGAATTGCAACTTGTACGAACACCAATTGCCGGGA
          TTTGCTCTCGGGTACAAGAGTTGTATGAACGGCCATTTTTATGAACAACATTTGTCGGGC
          CTTCCACTCGGGTACAACAGTTGTGTAAAAGGACATTTGTACGATCAGCACTTGCCCGGA
          TTCGCCCTCGGGTATTACAGTTGTGTAAAGTGTCAATTCTACGAACACCAATTGCCTGGC
          TTCGCGCTCGGATATGACAGTTGTGTAAAAAGTCCATTTTACGAACATGAATTTCCGGGT
          TTCGCACTCGGCTATTACAGATGTGTAAAATGTCAATTTTACGATAACCAATTGCCTGGA
          TTCGCCCTCGGGTATGAGAGTGGTGTAAAATGTCAACTTGACGAAAACCAATTGCCGGGT
          TTCGCCCTGCGTTATGAGAGATGTGTAAAAGGTCAATTCTACGAACACGATTTGCCGGGT
          TTTGCACTCGGGTATGACAGTGGTGTTAAATGTCAATTTTACGAACACCATCTGCCGCGT
          TTCGCCCTCGGGTATGACAGCTGTGTCAAATGTCAGTTTTACGATCACCAGTTGCCGGGT
          TTCGCCCTTGGGTATAACAGTTGTGTAAATTGTCATTTGTATGAACACCATTTGCCAGGC
          TTCGCCCTCGGGTACAACAAGAGTGTAAAGTGGCAGTTTTATGAACACCAACTGCCGGGA
          GAAGCCCTCTGTCATAGAAGTCGTGTAATTGGAAATGTGTGCGAGCACCAATTTCCGGGG
          TATGCCCACTGTCATAGCAGTTGGGTAAAGTGGCATATATACGAACACCATGTGCCCGGG
          TATGCCCTTTGGCATAGCAGTTGGGTAAACTGGCACTTTTACGACCACCAATTGCCGGGA
          TATGCGCTCTGGGATAGGAGTTGCGTAAACGGCCATTTTTATGAACACCATTTGCCCAGA
          TATGCACTATGGGATAGCAGTTGCTTCAAATGTCATTTCCCTGAGCACCAATTGCCGGGA
          TTCCCCCTTCGGCAAAACAGCTGTGTTGAGTGGCATTTATACGACCACCAGGTGACAGCC
          TTTGCCCTTCGTAAGAATAGCTGTGTAGAGTGTCATTGCTACGACCATCAATTTCCGGCC
          GTGGCCCTTCGTAAGAATAGCTGTGTAGAGTGTCATTGGTACGACCACCAAATACCGGCG
          CTCGCTCTTCGTACCAATAGCTGTGTAGAGTGTCAGTGGTACGACCACCAATTTCCGGCC
          TTCACTCTTCGTAATAATAGCTGTGTAGAGTGTCCTTGGAACCACCACCAATTTCCGGCT
          TTCGCCCTACGTAAGAAAGGCGGAGTAGAATGTCACTTTTACGACCACCAATTTCCTGCC
          TGCGCTCTTCGTAACAATAGCTGTGTAGAATGTCATATTTACGACCAGCAATTACCTGAC
          TTCCCGATCCGCAAGAAAAATTGTGTGGAGTGTCAATTTTACGAACATCAATTGCGGGGA
          TTAGCCCTCGGGAATAATAGATGTGTAGACTGCCATTTTTACGAACAAGATATGTCGGGA
          TTCGCCCTTGGGAATAATAGACGAGGCGACTGCGATTTTGATGAACAACATTTCCCGGGA
          TTCGCCCTTGGGAATAATAGACGAGGCGACTGCGATTTTGATGAACAACATTTCCCGGGA
          TTCGCCCTGGGGAATAATAGACGAGGCGACTGCGATTTTGATGAACAACATTTCCCGGGA
          GTGGCACTCGTGAATAATGGCAGTTTAGACTGCCACATTTACGAACACCAATTGCCCTGG
          TTGGCCCTCGGTAATAATAGTTGTTTAGAATGCCAATTGTACGACCACCACTTGCCGGGT
          TTGGCCCTGGGAAATCATAGTTGCCTTGAATGTCATTTCTACGAATACCATTTGCGGGGA
          TTAGCCCTTGCAAATAATAGTTGGTCTGACTGGCAATTTTACGATGATCAGTTGCGAGGA
          TTAGCCCTTGGAAATAATAGTTGGTTGGACTGGGATTTGTACGATTACCAGTTGCGAGGA
          TCGGCGCTTGGAGATGATAGTTGGTTCGACTGGCAATTGTACGATCACCAGTTTCGAGGA
          TTGGCCCTAGGAAATAAAAGTTGCTTTGATTGGCAGTTCTACGAACAGCAGTTGCGTGGA

          CATGAGTCTGTCAGCAAGGATTGCCCTTCAAGCCCTGAGAAAAGGACTGAAAGTCAAGAG
          GATGAGTCCGTGCGTAAGGAATGGCCGTCAAGTACCGAGCGAAGAACTCATTATCAGAAG
          TATGATTCCTACCGACACCATAGCCGTACTAGGTCAAACCGGAGCACTCAATATCAGGAT
          TATGATTCCTACAGACACGATAGGCCATCTAGGTCCGACCGGAGCACTCACTATAAGGAT
          TATGATTCCTACCGGGACGATAGGCCCTCTATGGCAGAGAGGTGCACTCAGTATCAAGAT
          TATGATTCTATCCGCAAGGATCGTTCGTCGAGCTCTCACCAAAGCACTGAAAAACAGGAT
          TATGAGGCCACCCGGAAGGAATTTCCCTCAAGCACGGACGTAGGTACGGAATATCAACAA
          CAAGAGTCCATAAGGCAGACATGGCCCACTAGTACTGAGCGTAGTACGGAACAGCAGGAA
          AACGAGTCAATGGGCAAAGACAGTCCGTCAATCACTGTGCGAAGGACTGAACAACAGGAG
          AACGAGGCAATGGGCAACGACGGGCCATCAAGGCCTGTCCGAAGCATAGAACACCATGAG
          AAAGGTTCCATCGGCAAAAAGTGTCCGTCAAGTACTGTTGGAAGGACAGATCAGCACGAG
          AACGAGTCCATTCGCAAAGATTGTCCGTCCAGGACTGTGCGAAGGACAGAACACCAAGAG
          TACGAATCCCTTCGTAAGCATTGGCCTTCAAGCACCGTCCGTAGGGTTGAACATCATGAC
          TACCATTCGATTCGCAAGGATTGCCCGCCGAGCACGGTCCGAGGAACTGATGATGATGAT
          TACGAGTCCATTCGCAAGGAATGCCCATCAAGCACTGTACGTACGACAGAACACGATGAG
          TACGAAGCCATGCGCAACGATCGCCGATCGAGCCCCGCTCAAAGTACCGAGTATCCGGAA
          TACGACGCCATTCGAAATGAAAGCCGTTCGAGTCCTGCTCAGAGCACGGAGTATCCAAAA
          TACGATTCTATTCGCAAGGATTGGCGTTCGAGCCCCGCCCAAAGCACGGACTATCCAAAA
          TACGATTCTATTCGTAATGACTGCCGTTCGAGGCCTGCTCAAAGCACAGAATATCCGGAA
          TACGACTCCATTCGCAATGAGTGCCGTTCGAGGCCTGCTCAAAGTACACAATATCCCGAA
          GATGAGTCGGGTCGGAACGACTGGCGCTCGAGGCCTGCACAATGCACAGACGATCCCGAA
          GACGATTCCATTCACAACGATTGGCGATCAAGTCCTGCACATAGAACCCAAAATCCAGAA
          TACGAGTCGATGCGCAATGAGTGGCGATCTAGGCCTGCTCAAAGCACCGATTATCCAGAT
          TACGAGCCCGTCCGCAATCAGGGGGGATCGAGGCCTTCTCAAAGCACAGATTATTCAGAT
          TACGAGTCCATACGAAATGATTGGCGATCTAGGCCTTCTCAAAGGTCCGAATATCCTGAT
          TACGAGTCCATTCGAAACGATTGGCGCACGCGGCCTTCTCAGAGATCCGAAGATCCAGAT
          TACGAGTCAATTTGCAACAATTCGCGATCGAGGCCTTCTCAAAGCACTGATTACTCTGAT
          CACGAGTCCATTCGCAATTATAGGCGCTCAAGGCCTTCTCAAAGGCCCGATTATTCGGAT
          TACGAGTCCATTCGGAATGAATGGCGATCGAGGCCTTCTCATAGCACCGACTACCCAGAT
          TACGATTCCATACGCAAGGATTGCCGATCGTGGCCTTCCCAATGCACTGATTATCCAGAT
          TACGATTCTATTCGGAATGATAGGCGCTCGAGACCTTCTCAAAGCACCGAATATACAGAT
          TACGACTCGATGCGCAACGGTTGGCGCTCGAGGACTGCTCAAAGCACCGAATATCCCGAG
          TACGAGTCCATTCGCAATGATCGGCGCTCGCGCCCTGCTCACAGCACAGAATATCCAAAA
          TACGAGCTCATGCGCAATGAGTGGCGCTCCTGCCCGGCTCACAGCGCTGACTATCCAAAA
          TACGACTCGATTCGCAATGATTCGCGTTCGAGACCGGCTAAAAGCACCGAATATCCAGAA
          TTCGAGTCCATTCGCAATGATTCGCGATCAAGGCCTGCTCAAAGTACGCAATATCCCAAA
          TACGATTCCATTCGCAAAGAATGGCCGTCGAATCCTGAACAGAGGACGGAATATCCGGAA
          TACGATACCATTCGCAACGAATGCGCATCGAGTCCTGAGCACAGTATTGATTCTCCAGAA
          TACGATTCCATTCGGAAAGAATGGGCGTCGAGTCCAGAATACAGCACTGATTATCCAGAA
          TACGATTCCATTCGCAAAGAATGGGCGTCGAGTCCGGAACACTGTACTGATTATCCCGAA
          TTCGAATCAATTAGCAACGAATGTGCGTCTAGTCCAGAACACTGTACTGATTATCCCGAA
          TACGATCCTATTCGAAAAAAATGGTCCGCGAGTCCTGAGCACAGCACTGAATATCCAGAA
          TACGATCCGATCCGCAAAGACTGGGCGTCGAGTCCTGAACACAGTACTGAATATCCAGAA
          TACGATTCCATTCGCAAAGAGTGGCCGTCGAGTCCTGAACAGAGCATGGAATATCCAGAT
          GATGACTCAATTGGTAAGGATTGGCCGCCAAGGGCAGATCATAGTACCGAATATCAAGAA
          CATGACTCCATTCGTAAGGAGCGGCCGCCAAGCCCTGATCACAGGACCGATTATCAAGAA
          CATGACTCTATTCGGAACGAGCGGCCGCCAAGCCCTGATCACAGGACCGATTATCAAGAA
          CAGGACTCTATTCGGAACGAGCGGCCACCAAGCCCTGATCACAGGACCGATTATCAAGAA
          TATGAGCCTATGCGTCAGTATTGGCCATCAAGTCCTAAGCAAAGTAGTGAATGTAATGAC
          TATGAGTCCATTCGCAAGGATTGGACGTCAAGCCCTGATCAAAGCACGGAATGTCAAGAC
          CATGAGTCTATGAGCGAGGATCGGCCATCAAGGCCTGAGCGTAGGACTGAAAGCCAAGAG
          CACGAGTCCATCAGCAAGGACTGTTCGTCCAGGCCAGAACAAAGCACTAAAAGCCAAGAG
          CACGAAACGATCAGCAACGATTGGCCGTCAAGCCCAGAGCAAAGCACTGAAAGCCAAGAA
          CATGAATCAATCTGTAACGATTGGACGTCAAGCCCGGAGCAAAGCACTCAAAGCCAAGAG
          CATGAATCGATTAGCAAGCATTGCCCGTCAAGCTCTGAGCAAAGGACTAAAAGCCAACAT

          TGTGTGTACCATCACTCCAGTGTCCGAACCAACCCGAGCCCCCATCGAACGGGACGGGCA
          TGTTCATACCAACATTCCTCACAACGCACGGATCCGAGCCATCATCGCACATGTCGGGCA
          GGCTCATATCCACATTCCAGGGTACGAACAAAACCTAGCCACCACCGAACGTGTCGCCCT
          GGTCCATACCAACATTCCAGGGTAAGAACAGAGTCTAGCCACCACAGAACGTGTCGCGCT
          GGCCCATACCAACATTCGAGGGTACGAACAGAGCCTAGCCAACACAGAACGTGTCGAGCT
          GGGACACACAATCCGTTAAGGGTCCGTCCCAATTCCAGGCAAAACGGTACAAGTTGGGCG
          CGGGCATACCAGCTCGCTAGTGTACGCCCAGATCCCTGCCATCATCGCACATGGCAAGCA
          TGGGCTTACCATCTCTCCAGCGGCCGATCAAATACTAGCCAGCATCGCACATGGTGTCCA
          TGCGCATACCAATATTCTAGGGTCGGCACAAATCCCACGCACCAGCGGACTTGGCGGACA
          AGAGCGTACCAATACTCCAGCGTCCGAACGTATCCGGGGTATCACCGAACATGGTGGGCA
          TGGGCATACTATCACCCCAGGGTCCGGACAAATCCCAGGCAGCATCGGACGTGGCGTGCA
          TGTCCAAACCATGATTCGAGAGTCCGGACAAAACCCAGCCACTATCGGACCTGGCGAGCA
          TGGGCATACCCTCATTCCAGGGTGCGAACAAAACCCAGGGAGCAGCGCACATGCAGTGCG
          TGTGCATGCCATCATTCGAGCGTCGGAACAAAGTCGCGACATCACAGAACTTGCCGGGCG
          CGCGCGTACCATTATTCCAGTCTCCGCACCAAACTGTGGCAACACAGAACATGTCGGGCA
          CGTGCGTACCACCACTCCAGGGTGCGAACAAATGCTAGACAGCAGAGAACCTGGAGTGCT
          TGTGCGAACCAGCACGCAAGTGTCCGAACTAAAGCGCGGCACGATAGCACTTGCCGCGCG
          CGGGCTTACGATCACACCAGCGTCCGAACAAAACCTAGACAGGATAGAACTTGTCGCGCA
          TGTGCCAAGCATCACACTAGTGTCCGAACAAAAGCGAGTCAAGATAGAACTTGGCGTGCT
          TGTGCTTACCACCACACAAGGGTTCGAACAAAAGCGAGACACGAAAGAACTTGCCGTGCT
          TGCCCAAACGGTCAGGCCAGCGTGCGAACTAAGGCGAGGCACGAGAGGACCTGCCGCCCT
          TGCGCTAACCGTCAGTCCAGGGTCCGAACGAAGGCGAGCCACGATAGAACCTGCCGCGCT
          TGGGCGAACCATCACTCACGGGTTCGAACCAAGGCGAGGCAGGAAAGAACCTGCCGAGCA
          TGCGCTAAATATCACTCGAGGGTGCGAACGAAGGCCAAACATGAAAGAACCCGGCGACCA
          TGGGCTTACCAACAATCGAGTGTCCGAACGAAGGCGAGCCACGAGAGAACGTGCGGGGCG
          TGGGCTAACCAACACTCGAGTGTACGAACGAAGGCGAGACACGAGAGAACCGGACGAGCC
          TGGGCCAAACATCACGCAAGTGTTCGAACTAAGGCGAGACACGATAGTCCCTGCCGAGCA
          TGGGCCAACCATCACTCCAAGGTCCGAACAAAGGCGAGACACGATAGAGCCTGCCGAGCA
          TGCGCTAACCATCACTCGAGGGTCCGCACAAAGGCTAGACAAGAGAGAACCAGCCGACCA
          TGGGCAGAACACCACGCCAGGGTCCGAACAAAGGCGTGTCAAGACGGAACCTGCCGAGCA
          TGGGCTAACCATCACTCCAGAGTAAGAACAAAGGCAAGACACGAAAGAACCTGTCGGGCC
          AGGGCGAAACATCAATCCAGAGTGCGCACAAACGCAAGACACGATAGAACCTGCCGCGCA
          TGCGCTAATCAACAATCCAGCGTAGGAACGGAGACAAGACACGATAGAACCTGGCGAGCA
          TGTGCTAATCAAGACTCGAGAGTCGGAACAAATACAAGTCAAGATAGAACCTGTCCTGCA
          TGTTCTAACCAACAATCCAGCCTCGGAACAAATGCAAGACACGATAGAACCTGTCGCGCC
          GGTGCTAACCAACAATCCAGCCTCCGTACAAAGGCCAGACAAGATAGCTCTAGCCGCGCC
          TGCGCATACCACCTCTCCAGTGTTCGTACGAATCCGAGTCACCATCGGACCAGGCGGGCA
          TGTGCCTACCACCTCTCCAGGGTTCGAACGAATACAAGTGACCAACGAACCGGGGGAGCA
          TGTGCATACCATCTCTCTAGGGTTCGATCGAATCCGAGAGACTATCGAACGGGGCGAGCA
          TGTGCATACCAACTCTCAAGGGTACGCACGAATCCGCGTGACCATCGAACCGGGCGACCA
          TGTACATACCATCTCTCAAGGGTCCGGACGAATCCGAGTGAGCATCGAACCGGGCGAGCT
          TGTGCATACCACCTCTCCAGGGTTCGAACAAATCCGCGGCACTATCGAACCGGGCGGGCA
          TGTGCATACCACCTCTCCAGGGTTCGATCGAAGCCGAGACACCAACGAACCAGGCGGGCA
          TGTGCATACCATCTGTCGAGGGTACGGACGAATCCGACACACCAGCGGCCGTGGCGCGCA
          TGTGCTTACCAGCAGTCGAGTGTGCGGACAAATCCAAGCCACCAGCGAAGCTGCCGGGCA
          TGTGCATACCATCACTCCAGCGTGCGCACGAACCCTGGATACCGGCGGACCTGCCGTGTA
          TGTGCATACCATCAGTCAAGCGTGCGCACAAACCCTGGACACCGGCGGACCTGCCGTGTA
          TGCGCATACCACCAGTCAAGCGTGCGCACAAACCCTGGACACCGGCGGACCTGCCGTGTA
          TCTGCATATCACTACTCTAGTGTCCGTACAAATCCCAGTCAACATCGAGCCTGGCGGGCG
          TGCGTATACCATCAGTCGAGGGTCCGAATAAATCCGAGCCACCAGCGCACCTGGCGGGCA
          TGCGTTTACCACCACCCCAGATTCCGAACAAAGCCGAGCCACCATCGAACATGGCGTGCA
          TGTGTATATCATCAGTCCAGGGTCCGGACAAAGCCGAGCCACCATCGGACTTGGCGATCA
          TGGTTATATCATCACTCCAGGGTCCGAACAAAACCAAGACACCATCGGACTTGGCTGTCA
          TGTGTATATCATCAATCCAGAGTGCGCACTTATCCGAGTCACTATCGTACATGGCGGGCC
          TGCGTGAACCATCACTCCTGGGTACGAACAAATCCAAGCCAGCATCGAACGTGACGGTCA

          GGCTAAAGTGCTGTGGGACCTGGCGGGCATAGTCCTGGCCAATGCTTGTGCTCTGTACAT
          AGCTAAAATGCCGTGGGGCCTGGCGGCACCAGCCCAGGCCAGAGCTTCTGTTCATTTTAT
          GGCTACAATGCCGTGGGGCCCGGCAGGACCAGATCGGGCCGATGGATTTGCTCCTTATAC
          GGCTACCATGCCGTGGTGCCTGGGAGGGCCAGAGCGGGTGGATGGATTTGTTCCATAGAT
          GGCTATCACGCCGTTGGACCTGGGAGCACCAGAGCCGGGCGATGGATTTGCACGTTATAT
          GGTTAACGTCCGGTGGGCCCGGGCCGGCCCAGTCCAGGCCAATGTGCATGCTCGGTCCAC
          GGCAAACGAACTGTAGGACCAGGGGGAGCCAGCCCTGGCCACAGTTTATGCCCCTTGTAT
          GGCTAACGTGCGATCCGACAAGGCGGGCCTAGACCCTGTCAAAGTTTGTGGTCAGTGTAC
          GGTTATAGGGCGGCGGGGCCAGGTGGCCCCAGCGACAGCCATAGCTTTCTTTCCGTTTAT
          GGACACAGCGCGGTGGGCCCTGGCGGCCCCAGACCCGGCAAAAGTTTAGGTTCTGAGTAT
          CGTTATAGCGCTGTGGGGCCCGGTGGGCCTAGGTCCGGTCATACCTTTCGTTCCGTGTGT
          GGTTACAGAGCGGTAGGCCCTGGTGGCCCCAGACCACGCCACAGTTTATGTTCCATTTAT
          GGTTAAAGTTCCGTGGGCCCTGGAGGACCGTGCCCCGGGCATAGTTTTTGTTGCGTGTAT
          CGGTAAAGTGTGGTTGGCCATGGCGGCCCTAGCCCCGGCCATAGCTTATGTTCAGTGAAA
          GGGTAAAGTGCTGTGGGACCTAGTGGCCCTAGCCCCGGCCATAGACTCTGCTCGGAGTAC
          GGCTACGGACCGTGTGGCACTGGTGGACACAGACCTGGCCAATGTTTATGTTCGGTCCAG
          GGCAAAAGCGCCGTAGGTCCAGGCAGGCAGAGGCCTGGACACTGGGTGTCATCTTTCAAT
          GGATACAGGGCGGGCGGCCCCTGGGACCACGGGGCAGGACACTGGGATTGTCCATTCAAT
          GGCTAAAGGGACGTTGGCCCCGGGGGTCACAGGCCTGGACAGTGGGTTTGCTCTTTCAAG
          GGATAAAGCGCCGTAGGCCCCGGGGGCCAAAGGCCTGGACACCGGGTCTGTTCGTTTAAC
          GGACATAGTGCTGTGGGGCCAGGCGGCCAGCGGCCAGGATACTGCGTATGTGCTTTGAAT
          GGGCAAAGACACGTAGGCACCGGCGGCCAGAGGCCCGGACACTGCGTGTGCGCTTTAACT
          GGCTAACGGGCCGTAGGCGCCGGCGGCGATAGGCTTGGACACGACGTCTGCTCGTTCAAT
          GGATAACGGGCCGTAGGCCCCGGCGGCCAGAGGCCCGGACAATGCCTGTGCACGTTCAAT
          GGGTAAAGGGCCCTAGGCCCCGGTGGCCAGAGGCCTGCACACTGGGTGTGTTCATTAAAT
          GGCTAAAGGGCCCTACGACCCGGGGGACAGAGACCTGGGCACTGCGTGTGTTCCGTAAAT
          GGCTAAAGCGCTGTAGGCCCCTGCGGTCAGAGGCCTGGACACTGCGTTTGTTCGTTGTAT
          GGCTACAGGGCAGTTGGACCCTGCGGACAGAGGCCAGAACAATGCGTTTGTTCGTTCAAT
          GGCTATAGGGCAGTCGGCCCCGGGGGACAGAGCCCCGGACATTGCGTTTGTTCGCTCAAT
          GGCTAAAGGGCCGTTGGCCCCGGGGGACAGAGTCCTGGACACGGAGTTTGTTCGTTCAAT
          GGCTAAAGGGCCGTAGGCCCCGAGGGCCAGAGGCCTGGACACTGCATATGGTCGTTCAAC
          GGCTAAAGTGCGGTAGAACCCGGCGGACAGAGGCCAGGACACTGCGTGTGTTCGTTAAAA
          GGATAAAGGGCCGTAGGCCTGGGACGCCAGATGTCCGGACACTGCGTGAACTCCTTCAAT
          GGATAAAGGGCCGTATGCCTAGGTTGCCAGAGGCCTGGACACTGGCTCTGTTCGTTCTAT
          GGCTAAAGAACCGTAGGCCCCGGCGGCCACGGACATCGTCATTGCATGTGTTCGTTCAAC
          GGCTAAAGCACGGTAGGCCCGGGCGACCACAGACCTGGACAATGCATGTGTTCTTTCGAC
          GGATAACGTGCTGTCGGACCTGGTGGGCACAGTCCCGGACAGTGGTTATGGTCCGTTCAC
          GGTTAAAGCGCTGTTGGACCCGGTGGGAACAGTCCTGGACATTGGTTCTGGCCCTTGCAA
          GGATAAAGCGCCGTAGGCGCTGGTGGGCATAGTTCGGGGCAATGGTTATGGTCGTTGCAC
          GGATAAAGCGCTGTGGGACCCGGTTGGCACAGTCCTGGACAATGGTTCTGGTCGGTGCAC
          GGATAAAGTGCTGTTGGACCAGGTGGTCACAGTCCGGGACAATGGTTCTGGTCATTGCAG
          GGATAAAGTGCAGTTGGACCTGGATGGCACAGTCCGGGACAATGGTTCTGTCCCGTGCAG
          GGCTAAAGTGCTGTTGGAGCTAGAGGACACAGTCCGGGTCAGTGGTTGTGGTCCGTGCAT
          CGATAAAGTGCTGTAGGACCGGGTGGGCACAGCCCTGGCCAATGGTTCTGGTCCGTGCAA
          GGCTACAGGGCAGTTGGACCTGGCGGGCATAGCCCCGGTGAAAGCGTATGTTCGGTGCAG
          GGCTATAGTGCGGTTGGCCCCGGCGGTCATAGCCCTGGTGAGAGCTTCTGTTCCGTGCAG
          GGCTATAGTGCGGTTGGCCCCGGCCGTCATAGCCCTGGTGAGAGTTTCTGTTCCGTGCAG
          GGCTATAGTGCGGTTGGCCCGGGCCGACATAGCCCTGGTGAGAGCTTCTGTTCCGTGCAG
          AGCAAATGGTCTGTGGGCCTTGGGGGCCATAGCCCTGGCCGGCGCTTACGTTCAGTACAT
          GGTTAAAGTGCCCTGGGACTTGGAGGGCATAGGCCGGGCAGAAGTGTATGCTCCGTGCAT
          GGTTAAATTGCCTTTGGACCAGGAGGGCATAGTCCTGGTCATCGCTTGTGGCCCGTCCAT
          GGCGAAAGTGCTCTGGGGCCAGGAGGACATAGCGCTGGCCACTACTTGTGCTCCGTACAT
          GGCGAGAGTGCGGTGGGACCAGGAGGCCAAAGTGCTGGCCAATGGTTGTGGTACTTACAT
          CGCGAAAGTGCTGTGGGTCCTGGAGGACATAGGGCCGGCCAATGCTTCCGGTCCGTGCAT
          GGTTAACGTGCTGTGGGACCTGGCAGACAAAGTCTTGGCCAATGCATGTGGTTAGTGCAT

          CGGACAGTGGGACCATAAAGATGTGAGGAAGGTAGAGAAGAACAGCAGAACCACGTCGTA
          CAATCTGTCGGTCCATAAGTGTATGACGACAGTAGAGATTCTCACCAAAGGCAGGTAGTC
          CAAAGAGTTGGACTGTAAAGATGTCCTGAAGGGAGATCTCAACACCAGAAGCAGTTGGTG
          CAAACAGTAGGACCCAATGGATGTCATGATGGGAGAGATCAGCACCATAAGCATTATGTG
          CAGACAGTAGGACCATAAGGGTGTCATCAAGGCGGAGAGCAGCACCAGAAGCAGTACGTG
          CAAACGTTTGGCCCATACGGACGTCAAGAGGGTCGACAATATCAGCGGAAGCAAGGAGTT
          CAAACAGTTGGACCATAAAGATGCGATTACGGGAGCGATGATAAGCAGAAACAGGTGGTG
          CAAACAGTTCGACCCTACAGCTGTGATGAGTGGAGACACGAAAAGCAGAAAATGGTCGTG
          CATAGTGTTGGCCCGTACATGTGTGACCAAGGGAGTGACCAGCAGCAAAATCACGTGTTC
          CAAATCGTTGGACCGCACATAGGCGAGGAAGGTAGAGAGGATCAGCAGAAGGACATTGTC
          AAAACTGTGGGTCCGTACATATGTGAGGATGGGAGAGAAGATGAGCATGAGCACGTCCTG
          CAAACAGTGGGTCCGTACAGGTGTGACGACGGTGGAGAAGATCAGCAGAAGCACGTGGTG
          CAAACGGTCGGACCCTAAAGCTGCGACGAAGGTTGTGAGGATCAGCATAAAGACGTTGTC
          CATACAGTTGAGCCATATAGATGGCATGAAGGACGAGATGATCAGCAGAATCAGGTCGTG
          CAAACCGTTGTTCCGTATAGGTGCGACGAAGGGAGAGAAGAACAGCAACAGCATGTCGTG
          AAAACGGTGGGCCCATTAAGGTGTGAGAAAGGTAGAGACGATCAGCAAAAATATGTCGTG
          AAAACTGTAGGCTCATTTGATTGTGACAACGGTAGTGACGCGCACCAAAATCACGTTGTC
          AACACTGTAGGATCATTGGATTGCGAGGAATGGAGGGACGATCACCAAAACCACGTCGTC
          AAAACGGTCGGATCATTGGAGGGGAATAAATGGAGAGAGGAGCAGCAAAACCACATCGTC
          AAAACTGTCGGGTCGTTGGAGGGGGAGAAATGGAGTGTCGAGCATCAAAACGAAGTAGTC
          CGGACAGTAGGATCCTTCGATTGTCACAATTGGGCTGATGATCAGCAAAACCACGGCGTT
          GAAACATTAGGCTCATTAGAGTGTTACAACAGGGGCGACGATCATCAAAATCACGTGGTT
          AAGACGGTTGGATCATTAGTGTGTTACAAATGGAGTGATGAACAGCAATACCAGGTGGTA
          AAAACGGTTGGATCATTAGTGTGTTACAAGTGCAGGGAAAATCAGCAAAACCAGGTAGTA
          AACGCAATTGGATCATTGGTATGTTATAACTGGGGTGATGATCAGCATAACCACGTGGTA
          AACACTGTTGGGTCGCTAATGTGTTACAAAAGGAGAGATGAACACCAAAACCAGTTCGTT
          AATACTGTTGGATCATTGGTCTGTTACAAATGGAGAGAAGATCAGCAAAACCAGTTGGTA
          TATACAGTCGGATCATTGGTGTGTTACAAGCGGAGAGACGATCAGCATAACCAGTTTGTC
          AAGACTGTTGGATCATTAGTCTGTTCCAAATGGAGAGAAGAGCATCAATACCAATCGGTC
          AATACGGTTGGGTCCCTAGTTTGTGACAAATTCAGAGAATATCAACAAAACCACGTGGTT
          AATACAGTTGGATCCGTTGTCTGTTACAAATGGAGAGAGGATCAGCAAAACCACGTCGTC
          AAAACAGTAGTATTCTTTGTGTCTTACAACTGGAGCGACGATCAGCAAAAGCATGTTGTA
          AAAACTGTTGGCTCCTTGATGTGTTACAAATGGAGAGAGGATCAGCAAAAGCAGGTAGTT
          AATACAGTGGGTTCTTTTGTAAGTTATAAATGGAGAGAGGATCAGCAAAAGGACGTTGTA
          AACACTGTAGGATCCTTGGTCTGTTACAACTGGAGAGAAGATCAGCAAAATCACGTTGTA
          ACCTCTGTACGATCGTTAGTCTGTTACAAATGGAGAGATGAATTGCACAAGCACGTGGTG
          CTTACTGTTGGGCCATTAAGATGTGAGAAAGGCAGAGACGATCAGCAGAATAATGTCGTG
          CAAACAGTTGGACCCTTAAGATGTGACAACGGCAGAGATGACCACCATAACCAGGTAGTG
          CAGACTGTTGGATCATTAAGATGTGACAAAGGCAGAGACGACCACCATAACCATGTCGTG
          CAGACACTCCGACCATTAAGATGGGACAAAGGCAGCCACGACCAGCATAATGATCTCGTG
          CAGACAGTTCGACCATTAAGATGTGACAAAGGGAGCGACGACCAGCATAATCACGTCGTG
          CATACAGTAGGCCCATTCAGATGTGACAAAGGCAGAGACGATCATCAGTATCAAGTTGTG
          CAGCCTGTTGGCCCATTCAGGTGTTACAAAGGCAGATACGAGCAGCAGAAACAAGTCGTG
          CATACCGTTGGTCCATTGAGATGGGACAAAGGCGGAGACGATCAGCAGAACCATGTCTTC
          CAAACACTGGGGGCGTAAAGAGTGGAGAAAGGGAGCGACGATCAGCAGAACCACGTGGTG
          CAAACACTGGGGGCCTAAAGAGGTGAAGATGGCAGCGAAGATCAGCATAAACACGTGGTG
          CAAACACTGGGGGCCTAAAGAGGTGAAGATGGCAGCGAAGATCAGCATAAACACGTGGTG
          CAAACACTGGGGGCCTACAGAGGTGAAGATGGCAGCGAAGATCAGCACAAACACGTGGTG
          CAAACAGTGGGGCCGAATAGATGTGACGAAGGCAGAGAAGAAGAGCACAAACAGGTAGTC
          CAAACGGTAGGCGCTTAAAGATGTGATTACGGGAGCGATGAACATCAGAACCACGTCGTG
          CGTACAGTCGGACCCTAAAGTTGTGACGACGGGAGGGAAAAACAGCAGAACCACGTCGTG
          CGGACTGTGAGACCATAAAGCTGCGAAGAAGGGAGTGAAAAACAGCAGAAATATGTCGTG
          CGGACAGTGAGACCATAAAGGTGTGAAGACGGGAGAGAAAAGCAGCAGAAGCATGTCGTG
          CGTACAGTGAGACCATAAAGCTGTGAGGAAGGGAGTGAAGATCAGCAGAAGCAAGTCGTA
          CGGACAGTTGGAACGTAAAGATGTGATAAGAGTGGGGATGATCAACATAAGCACGTCGTA

          TAACACGCACTAGACCGGTCGTAACGTCGCCACTCCAGCCATACAAGCTTTCGTACCCTC
          TACCAGTACCTTCAACGTTCGTACCGTCGTTACCCCACTCATCCATGCTTGCGGGCTATC
          CACTATGATCTTGAGCGTTCTTACCGGCGGTCTACTAGGCATCCCTGCGTGTGTACCATT
          CACCATGATATTCATCGTTCAAACCGGGGGTATCCGAGTCATCCTTGCTTGCGGGCTATC
          CACCAAGATCTTCAACGCTCCTACCGGCGGTATCCCAGTCATCCTTGCTTCCGGGCAATG
          TACCAGGACCTGCAGTGTGCTTATCGACGGTACCCCAGGTATCCATGCCTGCGCGCAATC
          TACCAGGAGCTCCACTGTTCTTACCGCCGGTACCCCAGCGAGCCAAGCATGCGCGCGATT
          CATCAAGATCTGCACCGAATTGACGGACGGTACCCAAGGCAGCCCTTCTTACGGACAACT
          TATAAGGAGCTCCACCGTGCAGATCGATGGTACCGAAGGCATCCATGGTTACGAGCGATC
          TATCAGGATCTTCACCGTTCTTACCGCCGGTACACGGGTCATCCCTGCTTACGTGCAATC
          TACCAAGATCTCCACCGTTCACACCGAAGGTGCCCGAGAAATCCATGCTTACGCGCTATC
          TACCAGGATCTCCACCGTTCTTATCGACGGTATCCCAGGCATCCGTGTTTTCGCGCCATA
          TACCAAGATCTTCAGCGTTCTTACCGAAGGTATCCTAGGCAACCATGCTTACGAGCAATA
          AACCAGGATCTTCAACGTTCGTACCGGCGGTATCCGAGCCATCCTTGCGTGCGCCCTATT
          TACCAGTATCTGCACCGTTCTGACCGTCGTTACCCCAGTCAACCATGCTTACGCGCTCTT
          AAACAGGATCTCCACCGTGCTTACCGGGGGTACCCCAGACAGTCACGCTTGTGCGCACTC
          TAACAGGAATTCCAGCGGGCATACGGAGGGTATCCGCGTCACTCACGTTTCCGGACGCTG
          TATCATGAGTTGCAACGGGCTTACAGGGGGTACCCGCGTCACTCCCGCTTTCGTACACTA
          TAACAGCAATTGCAGCGGGCGTACCGGGGGTACCCGCGGCACTCACGCTTGCGTACGCTC
          TAACATGAATTGCAGGGCGCCTACCGGGGTTACCCGCGGCACTCACGTTTGCGTACGCTC
          TAACAAGAATGTGAGCGATCCTACCGCGCGTATCCCCGCCAGTCCGGTCTTCGGACGCTG
          TAACACAAATTGCAGGGGCCTTACCGGGGGTACCCCCGCCAAGCACGTTTACGTACCGTC
          TAACAAAAATTGCAGCGTTCGTACCGGGGGTACCTCCGAAAATCACGGTTGCGAACGCTG
          TAACAGAACTTGCAGCGTTCGTACCGGGGGTACCCCCGAAACTCCCGAATGCGGTCATTG
          TACCAGAATTTTCATCGTTCGTACCGCGGGTACCCCCGGAACCCACGTTTCCGTACGCTC
          TAACAGAAATTTCACCGTTCGTACCGCGGGTACCCCCGAAACTCTCGCTTGCGTACGATC
          TAACAGAAATTGCAACGTTCTTACCGGGGCTATCCCGGAAACACACGCTTGCGTACGCTT
          TAACACGAATTGCAGCGGTCTTACCCAGGATATCCCCGAAACTCACGCTTGCGCACACTT
          TAACAGCAATTTCAGCGTGCTTACCGGGGGTACCCGCGAAACTCACGTTTGCGCAGGCTT
          TACCATAATTTGAAACGTTCTTACCGAGAATATCCCCGACACTCACGGTGGCGAACACTC
          TACCAGAATTTGCAGCGTTCTTACCGGGGGTACCCCCGCCAATCAGGCTTGCGCACTCTC
          TAACACAAAATGCATCGGTCTTACCGTGGATACCCCCGCCACTCTCGCTTGCGTCCAATT
          TATCATAAATTGCATAGGTTATACCGGGGGTACCCCCGCAACGCACGCTTGCGTACGCTC
          TATCAGAAGTTGCATCGGTTATATCGTGGGTACCCCCGACACGCAAGCTTGCGAGCACTC
          TATCAGAAATTGCAGCGGTCTTACCGCAGTCACCCCCGTCAATCACGCTTGCGTACGCTC
          TATCACAACTTTCTCCGCTCTTACCGGAGGCACCCCCGACAGTCACGCATGCGTACGCTC
          TACCAGGAACTTCATCGACCATACCGTCGGTACCAACGCCACGCACGGTTAAGGACTCTA
          TAACAGGAACTACAGCGGCCCTACGGGCGATACCCTCGTCATGCACGGGTGAGCTCACTA
          TAACATGAACTTCAACGACCTTACCGGCGCTACCCACGCCACGCACGATTGAGCACTCTA
          TAACAGGACCTCCATCGACCAAACCGGCGGTACCCACGTCAGGCGCGGTTGAGCACTCTA
          CAACAGGAACTTCATCGACCTTACCGGCGGTACCCACGCCAGGCACGGTTAAGCACTCTA
          TAACAGGAACTTCATCGACCTTACCGACAGTACCCACGCAACGCACGGTTTAGTACTCTG
          TAACAGGAACTGCATCGACCCTACCGACGGTACCCACGCCACGCGCGGTTTAGCACTCTA
          TATCAGGAACTTCAGCGACCTTACGGGCGGTACCCTAGGCACACACGCTTGCGTACACTA
          TAAGAGGATCTTCACCGATCGAACCGTCGATACCCCTGGCACTCATGGTTCCGCACTCTA
          TAACAGGAACTTCACCGTTCTTACCGACGGTACCCCAGGCACTCATGGTTGCGCACTCTA
          TAACAGGAACTTCAGCGTTCTTACCGACGGTACCCCAGGCACTCATGGTTGCGCACTCTA
          TAACAGGAACTTCAGCGTTCTTACCGACGGTACCCCAGGCACCCATGGTTGCGCACTCTA
          TAACTGGAGCTGCACCGTTCTTATCGGCGGTATAACAGGTACACTTGGTTGCGCACTCTC
          TAACAGGAACTCCAACGCTCGTATCGGCGGTACCCCAGCCAAACGTGCATGCGCACTCTC
          TAACAGGAACTGCATCGCTCGTATCGACGCTACTCCAGCCACACATGCTGGCGTACCCTC
          TAACGGGAACTTCACGGCTCGGATCGACTTTATTCAAGCCACACATGCTTTCGTACGCTG
          TAACGGGAACTTCACTGCTCGTAACGACGGTATACCCGCCACACAAGTTTCCGTACGCTC
          TAACAGGATCTCAACCGCTCGTAACGCCGGTATTCCAGACACACATGCTTTCGTATGTTC
          TAACAGGAATTTCACGGGTCGTAACGACGCCACTCCGGCCAAACATGCTTTCATAGCCTC

          GCG
          GAC
          GAT
          GAT
          GAG
          GGT
          GCT
          GCC
          GCG
          GCC
          GCA
          GCT
          GCG
          GCG
          GCA
          GCT
          GCA
          GCT
          GCA
          GCC
          GCT
          GCA
          ACG
          GCA
          GCG
          GCA
          GCA
          GCA
          GCC
          GCT
          GCA
          GCA
          GCA
          GGA
          GCA
          GCA
          GCG
          GCG
          GCG
          GCG
          GCC
          GCA
          GCG
          GCC
          GCC
          GCT
          GCT
          GCT
          GCG
          GCG
          GCC
          GCC
          GCC
          GCC
          GCC

