#
# transmissim
# main parameters

main:
	seed: 6

modules:
	network: 1
	phylogeny: 1
	sequence: 1

programs:
	viraltreeprogram: simphy_mac64
	readsprogram: ./art_illumina

output:
	phylogenyout: ../tests/
	sequenceout: ../tests/reference

network:
	contact: 0
	transmission: 1
	R0: 1.87
	numberofhosts: 200
	duration: 730
	rateimportcase: 0

phylogeny:
	viraltree: 0
	birthrate: 0.1
	deathrate: 0.1

sequence:
	reads: 1
	rootsequence: hiv-db.fasta
	sequencingsystem: MSv3
	readlength: 250
	coverage: 10